// Code generated by ent, DO NOT EDIT.

package alertsession

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the alertsession type in the database.
	Label = "alert_session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "session_id"
	// FieldAlertData holds the string denoting the alert_data field in the database.
	FieldAlertData = "alert_data"
	// FieldAgentType holds the string denoting the agent_type field in the database.
	FieldAgentType = "agent_type"
	// FieldAlertType holds the string denoting the alert_type field in the database.
	FieldAlertType = "alert_type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldFinalAnalysis holds the string denoting the final_analysis field in the database.
	FieldFinalAnalysis = "final_analysis"
	// FieldExecutiveSummary holds the string denoting the executive_summary field in the database.
	FieldExecutiveSummary = "executive_summary"
	// FieldExecutiveSummaryError holds the string denoting the executive_summary_error field in the database.
	FieldExecutiveSummaryError = "executive_summary_error"
	// FieldSessionMetadata holds the string denoting the session_metadata field in the database.
	FieldSessionMetadata = "session_metadata"
	// FieldAuthor holds the string denoting the author field in the database.
	FieldAuthor = "author"
	// FieldRunbookURL holds the string denoting the runbook_url field in the database.
	FieldRunbookURL = "runbook_url"
	// FieldMcpSelection holds the string denoting the mcp_selection field in the database.
	FieldMcpSelection = "mcp_selection"
	// FieldChainID holds the string denoting the chain_id field in the database.
	FieldChainID = "chain_id"
	// FieldCurrentStageIndex holds the string denoting the current_stage_index field in the database.
	FieldCurrentStageIndex = "current_stage_index"
	// FieldCurrentStageID holds the string denoting the current_stage_id field in the database.
	FieldCurrentStageID = "current_stage_id"
	// FieldPodID holds the string denoting the pod_id field in the database.
	FieldPodID = "pod_id"
	// FieldLastInteractionAt holds the string denoting the last_interaction_at field in the database.
	FieldLastInteractionAt = "last_interaction_at"
	// FieldSlackMessageFingerprint holds the string denoting the slack_message_fingerprint field in the database.
	FieldSlackMessageFingerprint = "slack_message_fingerprint"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldReviewStatus holds the string denoting the review_status field in the database.
	FieldReviewStatus = "review_status"
	// FieldAssignee holds the string denoting the assignee field in the database.
	FieldAssignee = "assignee"
	// FieldAssignedAt holds the string denoting the assigned_at field in the database.
	FieldAssignedAt = "assigned_at"
	// FieldResolvedAt holds the string denoting the resolved_at field in the database.
	FieldResolvedAt = "resolved_at"
	// FieldResolutionReason holds the string denoting the resolution_reason field in the database.
	FieldResolutionReason = "resolution_reason"
	// FieldResolutionNote holds the string denoting the resolution_note field in the database.
	FieldResolutionNote = "resolution_note"
	// EdgeStages holds the string denoting the stages edge name in mutations.
	EdgeStages = "stages"
	// EdgeAgentExecutions holds the string denoting the agent_executions edge name in mutations.
	EdgeAgentExecutions = "agent_executions"
	// EdgeTimelineEvents holds the string denoting the timeline_events edge name in mutations.
	EdgeTimelineEvents = "timeline_events"
	// EdgeMessages holds the string denoting the messages edge name in mutations.
	EdgeMessages = "messages"
	// EdgeLlmInteractions holds the string denoting the llm_interactions edge name in mutations.
	EdgeLlmInteractions = "llm_interactions"
	// EdgeMcpInteractions holds the string denoting the mcp_interactions edge name in mutations.
	EdgeMcpInteractions = "mcp_interactions"
	// EdgeEvents holds the string denoting the events edge name in mutations.
	EdgeEvents = "events"
	// EdgeChat holds the string denoting the chat edge name in mutations.
	EdgeChat = "chat"
	// EdgeSessionScores holds the string denoting the session_scores edge name in mutations.
	EdgeSessionScores = "session_scores"
	// EdgeReviewActivities holds the string denoting the review_activities edge name in mutations.
	EdgeReviewActivities = "review_activities"
	// StageFieldID holds the string denoting the ID field of the Stage.
	StageFieldID = "stage_id"
	// AgentExecutionFieldID holds the string denoting the ID field of the AgentExecution.
	AgentExecutionFieldID = "execution_id"
	// TimelineEventFieldID holds the string denoting the ID field of the TimelineEvent.
	TimelineEventFieldID = "event_id"
	// MessageFieldID holds the string denoting the ID field of the Message.
	MessageFieldID = "message_id"
	// LLMInteractionFieldID holds the string denoting the ID field of the LLMInteraction.
	LLMInteractionFieldID = "interaction_id"
	// MCPInteractionFieldID holds the string denoting the ID field of the MCPInteraction.
	MCPInteractionFieldID = "interaction_id"
	// EventFieldID holds the string denoting the ID field of the Event.
	EventFieldID = "id"
	// ChatFieldID holds the string denoting the ID field of the Chat.
	ChatFieldID = "chat_id"
	// SessionScoreFieldID holds the string denoting the ID field of the SessionScore.
	SessionScoreFieldID = "score_id"
	// SessionReviewActivityFieldID holds the string denoting the ID field of the SessionReviewActivity.
	SessionReviewActivityFieldID = "activity_id"
	// Table holds the table name of the alertsession in the database.
	Table = "alert_sessions"
	// StagesTable is the table that holds the stages relation/edge.
	StagesTable = "stages"
	// StagesInverseTable is the table name for the Stage entity.
	// It exists in this package in order to avoid circular dependency with the "stage" package.
	StagesInverseTable = "stages"
	// StagesColumn is the table column denoting the stages relation/edge.
	StagesColumn = "session_id"
	// AgentExecutionsTable is the table that holds the agent_executions relation/edge.
	AgentExecutionsTable = "agent_executions"
	// AgentExecutionsInverseTable is the table name for the AgentExecution entity.
	// It exists in this package in order to avoid circular dependency with the "agentexecution" package.
	AgentExecutionsInverseTable = "agent_executions"
	// AgentExecutionsColumn is the table column denoting the agent_executions relation/edge.
	AgentExecutionsColumn = "session_id"
	// TimelineEventsTable is the table that holds the timeline_events relation/edge.
	TimelineEventsTable = "timeline_events"
	// TimelineEventsInverseTable is the table name for the TimelineEvent entity.
	// It exists in this package in order to avoid circular dependency with the "timelineevent" package.
	TimelineEventsInverseTable = "timeline_events"
	// TimelineEventsColumn is the table column denoting the timeline_events relation/edge.
	TimelineEventsColumn = "session_id"
	// MessagesTable is the table that holds the messages relation/edge.
	MessagesTable = "messages"
	// MessagesInverseTable is the table name for the Message entity.
	// It exists in this package in order to avoid circular dependency with the "message" package.
	MessagesInverseTable = "messages"
	// MessagesColumn is the table column denoting the messages relation/edge.
	MessagesColumn = "session_id"
	// LlmInteractionsTable is the table that holds the llm_interactions relation/edge.
	LlmInteractionsTable = "llm_interactions"
	// LlmInteractionsInverseTable is the table name for the LLMInteraction entity.
	// It exists in this package in order to avoid circular dependency with the "llminteraction" package.
	LlmInteractionsInverseTable = "llm_interactions"
	// LlmInteractionsColumn is the table column denoting the llm_interactions relation/edge.
	LlmInteractionsColumn = "session_id"
	// McpInteractionsTable is the table that holds the mcp_interactions relation/edge.
	McpInteractionsTable = "mcp_interactions"
	// McpInteractionsInverseTable is the table name for the MCPInteraction entity.
	// It exists in this package in order to avoid circular dependency with the "mcpinteraction" package.
	McpInteractionsInverseTable = "mcp_interactions"
	// McpInteractionsColumn is the table column denoting the mcp_interactions relation/edge.
	McpInteractionsColumn = "session_id"
	// EventsTable is the table that holds the events relation/edge.
	EventsTable = "events"
	// EventsInverseTable is the table name for the Event entity.
	// It exists in this package in order to avoid circular dependency with the "event" package.
	EventsInverseTable = "events"
	// EventsColumn is the table column denoting the events relation/edge.
	EventsColumn = "session_id"
	// ChatTable is the table that holds the chat relation/edge.
	ChatTable = "chats"
	// ChatInverseTable is the table name for the Chat entity.
	// It exists in this package in order to avoid circular dependency with the "chat" package.
	ChatInverseTable = "chats"
	// ChatColumn is the table column denoting the chat relation/edge.
	ChatColumn = "session_id"
	// SessionScoresTable is the table that holds the session_scores relation/edge.
	SessionScoresTable = "session_scores"
	// SessionScoresInverseTable is the table name for the SessionScore entity.
	// It exists in this package in order to avoid circular dependency with the "sessionscore" package.
	SessionScoresInverseTable = "session_scores"
	// SessionScoresColumn is the table column denoting the session_scores relation/edge.
	SessionScoresColumn = "session_id"
	// ReviewActivitiesTable is the table that holds the review_activities relation/edge.
	ReviewActivitiesTable = "session_review_activities"
	// ReviewActivitiesInverseTable is the table name for the SessionReviewActivity entity.
	// It exists in this package in order to avoid circular dependency with the "sessionreviewactivity" package.
	ReviewActivitiesInverseTable = "session_review_activities"
	// ReviewActivitiesColumn is the table column denoting the review_activities relation/edge.
	ReviewActivitiesColumn = "session_id"
)

// Columns holds all SQL columns for alertsession fields.
var Columns = []string{
	FieldID,
	FieldAlertData,
	FieldAgentType,
	FieldAlertType,
	FieldStatus,
	FieldCreatedAt,
	FieldStartedAt,
	FieldCompletedAt,
	FieldErrorMessage,
	FieldFinalAnalysis,
	FieldExecutiveSummary,
	FieldExecutiveSummaryError,
	FieldSessionMetadata,
	FieldAuthor,
	FieldRunbookURL,
	FieldMcpSelection,
	FieldChainID,
	FieldCurrentStageIndex,
	FieldCurrentStageID,
	FieldPodID,
	FieldLastInteractionAt,
	FieldSlackMessageFingerprint,
	FieldDeletedAt,
	FieldReviewStatus,
	FieldAssignee,
	FieldAssignedAt,
	FieldResolvedAt,
	FieldResolutionReason,
	FieldResolutionNote,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending    Status = "pending"
	StatusInProgress Status = "in_progress"
	StatusCancelling Status = "cancelling"
	StatusCompleted  Status = "completed"
	StatusFailed     Status = "failed"
	StatusCancelled  Status = "cancelled"
	StatusTimedOut   Status = "timed_out"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusInProgress, StatusCancelling, StatusCompleted, StatusFailed, StatusCancelled, StatusTimedOut:
		return nil
	default:
		return fmt.Errorf("alertsession: invalid enum value for status field: %q", s)
	}
}

// ReviewStatus defines the type for the "review_status" enum field.
type ReviewStatus string

// ReviewStatus values.
const (
	ReviewStatusNeedsReview ReviewStatus = "needs_review"
	ReviewStatusInProgress  ReviewStatus = "in_progress"
	ReviewStatusResolved    ReviewStatus = "resolved"
)

func (rs ReviewStatus) String() string {
	return string(rs)
}

// ReviewStatusValidator is a validator for the "review_status" field enum values. It is called by the builders before save.
func ReviewStatusValidator(rs ReviewStatus) error {
	switch rs {
	case ReviewStatusNeedsReview, ReviewStatusInProgress, ReviewStatusResolved:
		return nil
	default:
		return fmt.Errorf("alertsession: invalid enum value for review_status field: %q", rs)
	}
}

// ResolutionReason defines the type for the "resolution_reason" enum field.
type ResolutionReason string

// ResolutionReason values.
const (
	ResolutionReasonActioned  ResolutionReason = "actioned"
	ResolutionReasonDismissed ResolutionReason = "dismissed"
)

func (rr ResolutionReason) String() string {
	return string(rr)
}

// ResolutionReasonValidator is a validator for the "resolution_reason" field enum values. It is called by the builders before save.
func ResolutionReasonValidator(rr ResolutionReason) error {
	switch rr {
	case ResolutionReasonActioned, ResolutionReasonDismissed:
		return nil
	default:
		return fmt.Errorf("alertsession: invalid enum value for resolution_reason field: %q", rr)
	}
}

// OrderOption defines the ordering options for the AlertSession queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAlertData orders the results by the alert_data field.
func ByAlertData(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlertData, opts...).ToFunc()
}

// ByAgentType orders the results by the agent_type field.
func ByAgentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentType, opts...).ToFunc()
}

// ByAlertType orders the results by the alert_type field.
func ByAlertType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlertType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByFinalAnalysis orders the results by the final_analysis field.
func ByFinalAnalysis(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinalAnalysis, opts...).ToFunc()
}

// ByExecutiveSummary orders the results by the executive_summary field.
func ByExecutiveSummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExecutiveSummary, opts...).ToFunc()
}

// ByExecutiveSummaryError orders the results by the executive_summary_error field.
func ByExecutiveSummaryError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExecutiveSummaryError, opts...).ToFunc()
}

// ByAuthor orders the results by the author field.
func ByAuthor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthor, opts...).ToFunc()
}

// ByRunbookURL orders the results by the runbook_url field.
func ByRunbookURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunbookURL, opts...).ToFunc()
}

// ByChainID orders the results by the chain_id field.
func ByChainID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChainID, opts...).ToFunc()
}

// ByCurrentStageIndex orders the results by the current_stage_index field.
func ByCurrentStageIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentStageIndex, opts...).ToFunc()
}

// ByCurrentStageID orders the results by the current_stage_id field.
func ByCurrentStageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentStageID, opts...).ToFunc()
}

// ByPodID orders the results by the pod_id field.
func ByPodID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPodID, opts...).ToFunc()
}

// ByLastInteractionAt orders the results by the last_interaction_at field.
func ByLastInteractionAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastInteractionAt, opts...).ToFunc()
}

// BySlackMessageFingerprint orders the results by the slack_message_fingerprint field.
func BySlackMessageFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlackMessageFingerprint, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByReviewStatus orders the results by the review_status field.
func ByReviewStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewStatus, opts...).ToFunc()
}

// ByAssignee orders the results by the assignee field.
func ByAssignee(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssignee, opts...).ToFunc()
}

// ByAssignedAt orders the results by the assigned_at field.
func ByAssignedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssignedAt, opts...).ToFunc()
}

// ByResolvedAt orders the results by the resolved_at field.
func ByResolvedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolvedAt, opts...).ToFunc()
}

// ByResolutionReason orders the results by the resolution_reason field.
func ByResolutionReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolutionReason, opts...).ToFunc()
}

// ByResolutionNote orders the results by the resolution_note field.
func ByResolutionNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolutionNote, opts...).ToFunc()
}

// ByStagesCount orders the results by stages count.
func ByStagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newStagesStep(), opts...)
	}
}

// ByStages orders the results by stages terms.
func ByStages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAgentExecutionsCount orders the results by agent_executions count.
func ByAgentExecutionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAgentExecutionsStep(), opts...)
	}
}

// ByAgentExecutions orders the results by agent_executions terms.
func ByAgentExecutions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAgentExecutionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTimelineEventsCount orders the results by timeline_events count.
func ByTimelineEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTimelineEventsStep(), opts...)
	}
}

// ByTimelineEvents orders the results by timeline_events terms.
func ByTimelineEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTimelineEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByMessagesCount orders the results by messages count.
func ByMessagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMessagesStep(), opts...)
	}
}

// ByMessages orders the results by messages terms.
func ByMessages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMessagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByLlmInteractionsCount orders the results by llm_interactions count.
func ByLlmInteractionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLlmInteractionsStep(), opts...)
	}
}

// ByLlmInteractions orders the results by llm_interactions terms.
func ByLlmInteractions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLlmInteractionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByMcpInteractionsCount orders the results by mcp_interactions count.
func ByMcpInteractionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMcpInteractionsStep(), opts...)
	}
}

// ByMcpInteractions orders the results by mcp_interactions terms.
func ByMcpInteractions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMcpInteractionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEventsCount orders the results by events count.
func ByEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEventsStep(), opts...)
	}
}

// ByEvents orders the results by events terms.
func ByEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByChatField orders the results by chat field.
func ByChatField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChatStep(), sql.OrderByField(field, opts...))
	}
}

// BySessionScoresCount orders the results by session_scores count.
func BySessionScoresCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSessionScoresStep(), opts...)
	}
}

// BySessionScores orders the results by session_scores terms.
func BySessionScores(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionScoresStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByReviewActivitiesCount orders the results by review_activities count.
func ByReviewActivitiesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReviewActivitiesStep(), opts...)
	}
}

// ByReviewActivities orders the results by review_activities terms.
func ByReviewActivities(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReviewActivitiesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newStagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StagesInverseTable, StageFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, StagesTable, StagesColumn),
	)
}
func newAgentExecutionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AgentExecutionsInverseTable, AgentExecutionFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AgentExecutionsTable, AgentExecutionsColumn),
	)
}
func newTimelineEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TimelineEventsInverseTable, TimelineEventFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TimelineEventsTable, TimelineEventsColumn),
	)
}
func newMessagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MessagesInverseTable, MessageFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
	)
}
func newLlmInteractionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LlmInteractionsInverseTable, LLMInteractionFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LlmInteractionsTable, LlmInteractionsColumn),
	)
}
func newMcpInteractionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(McpInteractionsInverseTable, MCPInteractionFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, McpInteractionsTable, McpInteractionsColumn),
	)
}
func newEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EventsInverseTable, EventFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
	)
}
func newChatStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChatInverseTable, ChatFieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, ChatTable, ChatColumn),
	)
}
func newSessionScoresStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionScoresInverseTable, SessionScoreFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SessionScoresTable, SessionScoresColumn),
	)
}
func newReviewActivitiesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReviewActivitiesInverseTable, SessionReviewActivityFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ReviewActivitiesTable, ReviewActivitiesColumn),
	)
}
