// Code generated by ent, DO NOT EDIT.

package sessionscore

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/codeready-toolchain/tarsy/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldContainsFold(FieldID, id))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEQ(FieldSessionID, v))
}

// PromptHash applies equality check predicate on the "prompt_hash" field. It's identical to PromptHashEQ.
func PromptHash(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEQ(FieldPromptHash, v))
}

// TotalScore applies equality check predicate on the "total_score" field. It's identical to TotalScoreEQ.
func TotalScore(v int) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEQ(FieldTotalScore, v))
}

// ScoreAnalysis applies equality check predicate on the "score_analysis" field. It's identical to ScoreAnalysisEQ.
func ScoreAnalysis(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEQ(FieldScoreAnalysis, v))
}

// ToolImprovementReport applies equality check predicate on the "tool_improvement_report" field. It's identical to ToolImprovementReportEQ.
func ToolImprovementReport(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEQ(FieldToolImprovementReport, v))
}

// ScoreTriggeredBy applies equality check predicate on the "score_triggered_by" field. It's identical to ScoreTriggeredByEQ.
func ScoreTriggeredBy(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEQ(FieldScoreTriggeredBy, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEQ(FieldCompletedAt, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEQ(FieldErrorMessage, v))
}

// StageID applies equality check predicate on the "stage_id" field. It's identical to StageIDEQ.
func StageID(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEQ(FieldStageID, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldContainsFold(FieldSessionID, v))
}

// PromptHashEQ applies the EQ predicate on the "prompt_hash" field.
func PromptHashEQ(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEQ(FieldPromptHash, v))
}

// PromptHashNEQ applies the NEQ predicate on the "prompt_hash" field.
func PromptHashNEQ(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNEQ(FieldPromptHash, v))
}

// PromptHashIn applies the In predicate on the "prompt_hash" field.
func PromptHashIn(vs ...string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldIn(FieldPromptHash, vs...))
}

// PromptHashNotIn applies the NotIn predicate on the "prompt_hash" field.
func PromptHashNotIn(vs ...string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNotIn(FieldPromptHash, vs...))
}

// PromptHashGT applies the GT predicate on the "prompt_hash" field.
func PromptHashGT(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldGT(FieldPromptHash, v))
}

// PromptHashGTE applies the GTE predicate on the "prompt_hash" field.
func PromptHashGTE(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldGTE(FieldPromptHash, v))
}

// PromptHashLT applies the LT predicate on the "prompt_hash" field.
func PromptHashLT(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldLT(FieldPromptHash, v))
}

// PromptHashLTE applies the LTE predicate on the "prompt_hash" field.
func PromptHashLTE(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldLTE(FieldPromptHash, v))
}

// PromptHashContains applies the Contains predicate on the "prompt_hash" field.
func PromptHashContains(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldContains(FieldPromptHash, v))
}

// PromptHashHasPrefix applies the HasPrefix predicate on the "prompt_hash" field.
func PromptHashHasPrefix(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldHasPrefix(FieldPromptHash, v))
}

// PromptHashHasSuffix applies the HasSuffix predicate on the "prompt_hash" field.
func PromptHashHasSuffix(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldHasSuffix(FieldPromptHash, v))
}

// PromptHashIsNil applies the IsNil predicate on the "prompt_hash" field.
func PromptHashIsNil() predicate.SessionScore {
	return predicate.SessionScore(sql.FieldIsNull(FieldPromptHash))
}

// PromptHashNotNil applies the NotNil predicate on the "prompt_hash" field.
func PromptHashNotNil() predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNotNull(FieldPromptHash))
}

// PromptHashEqualFold applies the EqualFold predicate on the "prompt_hash" field.
func PromptHashEqualFold(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEqualFold(FieldPromptHash, v))
}

// PromptHashContainsFold applies the ContainsFold predicate on the "prompt_hash" field.
func PromptHashContainsFold(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldContainsFold(FieldPromptHash, v))
}

// TotalScoreEQ applies the EQ predicate on the "total_score" field.
func TotalScoreEQ(v int) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEQ(FieldTotalScore, v))
}

// TotalScoreNEQ applies the NEQ predicate on the "total_score" field.
func TotalScoreNEQ(v int) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNEQ(FieldTotalScore, v))
}

// TotalScoreIn applies the In predicate on the "total_score" field.
func TotalScoreIn(vs ...int) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldIn(FieldTotalScore, vs...))
}

// TotalScoreNotIn applies the NotIn predicate on the "total_score" field.
func TotalScoreNotIn(vs ...int) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNotIn(FieldTotalScore, vs...))
}

// TotalScoreGT applies the GT predicate on the "total_score" field.
func TotalScoreGT(v int) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldGT(FieldTotalScore, v))
}

// TotalScoreGTE applies the GTE predicate on the "total_score" field.
func TotalScoreGTE(v int) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldGTE(FieldTotalScore, v))
}

// TotalScoreLT applies the LT predicate on the "total_score" field.
func TotalScoreLT(v int) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldLT(FieldTotalScore, v))
}

// TotalScoreLTE applies the LTE predicate on the "total_score" field.
func TotalScoreLTE(v int) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldLTE(FieldTotalScore, v))
}

// TotalScoreIsNil applies the IsNil predicate on the "total_score" field.
func TotalScoreIsNil() predicate.SessionScore {
	return predicate.SessionScore(sql.FieldIsNull(FieldTotalScore))
}

// TotalScoreNotNil applies the NotNil predicate on the "total_score" field.
func TotalScoreNotNil() predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNotNull(FieldTotalScore))
}

// ScoreAnalysisEQ applies the EQ predicate on the "score_analysis" field.
func ScoreAnalysisEQ(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEQ(FieldScoreAnalysis, v))
}

// ScoreAnalysisNEQ applies the NEQ predicate on the "score_analysis" field.
func ScoreAnalysisNEQ(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNEQ(FieldScoreAnalysis, v))
}

// ScoreAnalysisIn applies the In predicate on the "score_analysis" field.
func ScoreAnalysisIn(vs ...string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldIn(FieldScoreAnalysis, vs...))
}

// ScoreAnalysisNotIn applies the NotIn predicate on the "score_analysis" field.
func ScoreAnalysisNotIn(vs ...string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNotIn(FieldScoreAnalysis, vs...))
}

// ScoreAnalysisGT applies the GT predicate on the "score_analysis" field.
func ScoreAnalysisGT(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldGT(FieldScoreAnalysis, v))
}

// ScoreAnalysisGTE applies the GTE predicate on the "score_analysis" field.
func ScoreAnalysisGTE(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldGTE(FieldScoreAnalysis, v))
}

// ScoreAnalysisLT applies the LT predicate on the "score_analysis" field.
func ScoreAnalysisLT(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldLT(FieldScoreAnalysis, v))
}

// ScoreAnalysisLTE applies the LTE predicate on the "score_analysis" field.
func ScoreAnalysisLTE(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldLTE(FieldScoreAnalysis, v))
}

// ScoreAnalysisContains applies the Contains predicate on the "score_analysis" field.
func ScoreAnalysisContains(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldContains(FieldScoreAnalysis, v))
}

// ScoreAnalysisHasPrefix applies the HasPrefix predicate on the "score_analysis" field.
func ScoreAnalysisHasPrefix(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldHasPrefix(FieldScoreAnalysis, v))
}

// ScoreAnalysisHasSuffix applies the HasSuffix predicate on the "score_analysis" field.
func ScoreAnalysisHasSuffix(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldHasSuffix(FieldScoreAnalysis, v))
}

// ScoreAnalysisIsNil applies the IsNil predicate on the "score_analysis" field.
func ScoreAnalysisIsNil() predicate.SessionScore {
	return predicate.SessionScore(sql.FieldIsNull(FieldScoreAnalysis))
}

// ScoreAnalysisNotNil applies the NotNil predicate on the "score_analysis" field.
func ScoreAnalysisNotNil() predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNotNull(FieldScoreAnalysis))
}

// ScoreAnalysisEqualFold applies the EqualFold predicate on the "score_analysis" field.
func ScoreAnalysisEqualFold(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEqualFold(FieldScoreAnalysis, v))
}

// ScoreAnalysisContainsFold applies the ContainsFold predicate on the "score_analysis" field.
func ScoreAnalysisContainsFold(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldContainsFold(FieldScoreAnalysis, v))
}

// ToolImprovementReportEQ applies the EQ predicate on the "tool_improvement_report" field.
func ToolImprovementReportEQ(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEQ(FieldToolImprovementReport, v))
}

// ToolImprovementReportNEQ applies the NEQ predicate on the "tool_improvement_report" field.
func ToolImprovementReportNEQ(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNEQ(FieldToolImprovementReport, v))
}

// ToolImprovementReportIn applies the In predicate on the "tool_improvement_report" field.
func ToolImprovementReportIn(vs ...string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldIn(FieldToolImprovementReport, vs...))
}

// ToolImprovementReportNotIn applies the NotIn predicate on the "tool_improvement_report" field.
func ToolImprovementReportNotIn(vs ...string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNotIn(FieldToolImprovementReport, vs...))
}

// ToolImprovementReportGT applies the GT predicate on the "tool_improvement_report" field.
func ToolImprovementReportGT(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldGT(FieldToolImprovementReport, v))
}

// ToolImprovementReportGTE applies the GTE predicate on the "tool_improvement_report" field.
func ToolImprovementReportGTE(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldGTE(FieldToolImprovementReport, v))
}

// ToolImprovementReportLT applies the LT predicate on the "tool_improvement_report" field.
func ToolImprovementReportLT(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldLT(FieldToolImprovementReport, v))
}

// ToolImprovementReportLTE applies the LTE predicate on the "tool_improvement_report" field.
func ToolImprovementReportLTE(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldLTE(FieldToolImprovementReport, v))
}

// ToolImprovementReportContains applies the Contains predicate on the "tool_improvement_report" field.
func ToolImprovementReportContains(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldContains(FieldToolImprovementReport, v))
}

// ToolImprovementReportHasPrefix applies the HasPrefix predicate on the "tool_improvement_report" field.
func ToolImprovementReportHasPrefix(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldHasPrefix(FieldToolImprovementReport, v))
}

// ToolImprovementReportHasSuffix applies the HasSuffix predicate on the "tool_improvement_report" field.
func ToolImprovementReportHasSuffix(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldHasSuffix(FieldToolImprovementReport, v))
}

// ToolImprovementReportIsNil applies the IsNil predicate on the "tool_improvement_report" field.
func ToolImprovementReportIsNil() predicate.SessionScore {
	return predicate.SessionScore(sql.FieldIsNull(FieldToolImprovementReport))
}

// ToolImprovementReportNotNil applies the NotNil predicate on the "tool_improvement_report" field.
func ToolImprovementReportNotNil() predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNotNull(FieldToolImprovementReport))
}

// ToolImprovementReportEqualFold applies the EqualFold predicate on the "tool_improvement_report" field.
func ToolImprovementReportEqualFold(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEqualFold(FieldToolImprovementReport, v))
}

// ToolImprovementReportContainsFold applies the ContainsFold predicate on the "tool_improvement_report" field.
func ToolImprovementReportContainsFold(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldContainsFold(FieldToolImprovementReport, v))
}

// FailureTagsIsNil applies the IsNil predicate on the "failure_tags" field.
func FailureTagsIsNil() predicate.SessionScore {
	return predicate.SessionScore(sql.FieldIsNull(FieldFailureTags))
}

// FailureTagsNotNil applies the NotNil predicate on the "failure_tags" field.
func FailureTagsNotNil() predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNotNull(FieldFailureTags))
}

// ScoreTriggeredByEQ applies the EQ predicate on the "score_triggered_by" field.
func ScoreTriggeredByEQ(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEQ(FieldScoreTriggeredBy, v))
}

// ScoreTriggeredByNEQ applies the NEQ predicate on the "score_triggered_by" field.
func ScoreTriggeredByNEQ(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNEQ(FieldScoreTriggeredBy, v))
}

// ScoreTriggeredByIn applies the In predicate on the "score_triggered_by" field.
func ScoreTriggeredByIn(vs ...string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldIn(FieldScoreTriggeredBy, vs...))
}

// ScoreTriggeredByNotIn applies the NotIn predicate on the "score_triggered_by" field.
func ScoreTriggeredByNotIn(vs ...string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNotIn(FieldScoreTriggeredBy, vs...))
}

// ScoreTriggeredByGT applies the GT predicate on the "score_triggered_by" field.
func ScoreTriggeredByGT(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldGT(FieldScoreTriggeredBy, v))
}

// ScoreTriggeredByGTE applies the GTE predicate on the "score_triggered_by" field.
func ScoreTriggeredByGTE(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldGTE(FieldScoreTriggeredBy, v))
}

// ScoreTriggeredByLT applies the LT predicate on the "score_triggered_by" field.
func ScoreTriggeredByLT(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldLT(FieldScoreTriggeredBy, v))
}

// ScoreTriggeredByLTE applies the LTE predicate on the "score_triggered_by" field.
func ScoreTriggeredByLTE(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldLTE(FieldScoreTriggeredBy, v))
}

// ScoreTriggeredByContains applies the Contains predicate on the "score_triggered_by" field.
func ScoreTriggeredByContains(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldContains(FieldScoreTriggeredBy, v))
}

// ScoreTriggeredByHasPrefix applies the HasPrefix predicate on the "score_triggered_by" field.
func ScoreTriggeredByHasPrefix(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldHasPrefix(FieldScoreTriggeredBy, v))
}

// ScoreTriggeredByHasSuffix applies the HasSuffix predicate on the "score_triggered_by" field.
func ScoreTriggeredByHasSuffix(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldHasSuffix(FieldScoreTriggeredBy, v))
}

// ScoreTriggeredByEqualFold applies the EqualFold predicate on the "score_triggered_by" field.
func ScoreTriggeredByEqualFold(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEqualFold(FieldScoreTriggeredBy, v))
}

// ScoreTriggeredByContainsFold applies the ContainsFold predicate on the "score_triggered_by" field.
func ScoreTriggeredByContainsFold(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldContainsFold(FieldScoreTriggeredBy, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNotIn(FieldStatus, vs...))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldLTE(FieldStartedAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.SessionScore {
	return predicate.SessionScore(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNotNull(FieldCompletedAt))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.SessionScore {
	return predicate.SessionScore(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldContainsFold(FieldErrorMessage, v))
}

// StageIDEQ applies the EQ predicate on the "stage_id" field.
func StageIDEQ(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEQ(FieldStageID, v))
}

// StageIDNEQ applies the NEQ predicate on the "stage_id" field.
func StageIDNEQ(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNEQ(FieldStageID, v))
}

// StageIDIn applies the In predicate on the "stage_id" field.
func StageIDIn(vs ...string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldIn(FieldStageID, vs...))
}

// StageIDNotIn applies the NotIn predicate on the "stage_id" field.
func StageIDNotIn(vs ...string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNotIn(FieldStageID, vs...))
}

// StageIDGT applies the GT predicate on the "stage_id" field.
func StageIDGT(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldGT(FieldStageID, v))
}

// StageIDGTE applies the GTE predicate on the "stage_id" field.
func StageIDGTE(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldGTE(FieldStageID, v))
}

// StageIDLT applies the LT predicate on the "stage_id" field.
func StageIDLT(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldLT(FieldStageID, v))
}

// StageIDLTE applies the LTE predicate on the "stage_id" field.
func StageIDLTE(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldLTE(FieldStageID, v))
}

// StageIDContains applies the Contains predicate on the "stage_id" field.
func StageIDContains(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldContains(FieldStageID, v))
}

// StageIDHasPrefix applies the HasPrefix predicate on the "stage_id" field.
func StageIDHasPrefix(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldHasPrefix(FieldStageID, v))
}

// StageIDHasSuffix applies the HasSuffix predicate on the "stage_id" field.
func StageIDHasSuffix(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldHasSuffix(FieldStageID, v))
}

// StageIDIsNil applies the IsNil predicate on the "stage_id" field.
func StageIDIsNil() predicate.SessionScore {
	return predicate.SessionScore(sql.FieldIsNull(FieldStageID))
}

// StageIDNotNil applies the NotNil predicate on the "stage_id" field.
func StageIDNotNil() predicate.SessionScore {
	return predicate.SessionScore(sql.FieldNotNull(FieldStageID))
}

// StageIDEqualFold applies the EqualFold predicate on the "stage_id" field.
func StageIDEqualFold(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldEqualFold(FieldStageID, v))
}

// StageIDContainsFold applies the ContainsFold predicate on the "stage_id" field.
func StageIDContainsFold(v string) predicate.SessionScore {
	return predicate.SessionScore(sql.FieldContainsFold(FieldStageID, v))
}

// HasSession applies the HasEdge predicate on the "session" edge.
func HasSession() predicate.SessionScore {
	return predicate.SessionScore(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionWith applies the HasEdge predicate on the "session" edge with a given conditions (other predicates).
func HasSessionWith(preds ...predicate.AlertSession) predicate.SessionScore {
	return predicate.SessionScore(func(s *sql.Selector) {
		step := newSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStage applies the HasEdge predicate on the "stage" edge.
func HasStage() predicate.SessionScore {
	return predicate.SessionScore(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, StageTable, StageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStageWith applies the HasEdge predicate on the "stage" edge with a given conditions (other predicates).
func HasStageWith(preds ...predicate.Stage) predicate.SessionScore {
	return predicate.SessionScore(func(s *sql.Selector) {
		step := newStageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SessionScore) predicate.SessionScore {
	return predicate.SessionScore(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SessionScore) predicate.SessionScore {
	return predicate.SessionScore(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SessionScore) predicate.SessionScore {
	return predicate.SessionScore(sql.NotPredicates(p))
}
