// Code generated by ent, DO NOT EDIT.

package sessionreviewactivity

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the sessionreviewactivity type in the database.
	Label = "session_review_activity"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "activity_id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldActor holds the string denoting the actor field in the database.
	FieldActor = "actor"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldFromStatus holds the string denoting the from_status field in the database.
	FieldFromStatus = "from_status"
	// FieldToStatus holds the string denoting the to_status field in the database.
	FieldToStatus = "to_status"
	// FieldResolutionReason holds the string denoting the resolution_reason field in the database.
	FieldResolutionReason = "resolution_reason"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeSession holds the string denoting the session edge name in mutations.
	EdgeSession = "session"
	// AlertSessionFieldID holds the string denoting the ID field of the AlertSession.
	AlertSessionFieldID = "session_id"
	// Table holds the table name of the sessionreviewactivity in the database.
	Table = "session_review_activities"
	// SessionTable is the table that holds the session relation/edge.
	SessionTable = "session_review_activities"
	// SessionInverseTable is the table name for the AlertSession entity.
	// It exists in this package in order to avoid circular dependency with the "alertsession" package.
	SessionInverseTable = "alert_sessions"
	// SessionColumn is the table column denoting the session relation/edge.
	SessionColumn = "session_id"
)

// Columns holds all SQL columns for sessionreviewactivity fields.
var Columns = []string{
	FieldID,
	FieldSessionID,
	FieldActor,
	FieldAction,
	FieldFromStatus,
	FieldToStatus,
	FieldResolutionReason,
	FieldNote,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// Action defines the type for the "action" enum field.
type Action string

// Action values.
const (
	ActionClaim   Action = "claim"
	ActionUnclaim Action = "unclaim"
	ActionResolve Action = "resolve"
	ActionReopen  Action = "reopen"
)

func (a Action) String() string {
	return string(a)
}

// ActionValidator is a validator for the "action" field enum values. It is called by the builders before save.
func ActionValidator(a Action) error {
	switch a {
	case ActionClaim, ActionUnclaim, ActionResolve, ActionReopen:
		return nil
	default:
		return fmt.Errorf("sessionreviewactivity: invalid enum value for action field: %q", a)
	}
}

// FromStatus defines the type for the "from_status" enum field.
type FromStatus string

// FromStatus values.
const (
	FromStatusNeedsReview FromStatus = "needs_review"
	FromStatusInProgress  FromStatus = "in_progress"
	FromStatusResolved    FromStatus = "resolved"
)

func (fs FromStatus) String() string {
	return string(fs)
}

// FromStatusValidator is a validator for the "from_status" field enum values. It is called by the builders before save.
func FromStatusValidator(fs FromStatus) error {
	switch fs {
	case FromStatusNeedsReview, FromStatusInProgress, FromStatusResolved:
		return nil
	default:
		return fmt.Errorf("sessionreviewactivity: invalid enum value for from_status field: %q", fs)
	}
}

// ToStatus defines the type for the "to_status" enum field.
type ToStatus string

// ToStatus values.
const (
	ToStatusNeedsReview ToStatus = "needs_review"
	ToStatusInProgress  ToStatus = "in_progress"
	ToStatusResolved    ToStatus = "resolved"
)

func (ts ToStatus) String() string {
	return string(ts)
}

// ToStatusValidator is a validator for the "to_status" field enum values. It is called by the builders before save.
func ToStatusValidator(ts ToStatus) error {
	switch ts {
	case ToStatusNeedsReview, ToStatusInProgress, ToStatusResolved:
		return nil
	default:
		return fmt.Errorf("sessionreviewactivity: invalid enum value for to_status field: %q", ts)
	}
}

// ResolutionReason defines the type for the "resolution_reason" enum field.
type ResolutionReason string

// ResolutionReason values.
const (
	ResolutionReasonActioned  ResolutionReason = "actioned"
	ResolutionReasonDismissed ResolutionReason = "dismissed"
)

func (rr ResolutionReason) String() string {
	return string(rr)
}

// ResolutionReasonValidator is a validator for the "resolution_reason" field enum values. It is called by the builders before save.
func ResolutionReasonValidator(rr ResolutionReason) error {
	switch rr {
	case ResolutionReasonActioned, ResolutionReasonDismissed:
		return nil
	default:
		return fmt.Errorf("sessionreviewactivity: invalid enum value for resolution_reason field: %q", rr)
	}
}

// OrderOption defines the ordering options for the SessionReviewActivity queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByActor orders the results by the actor field.
func ByActor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActor, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByFromStatus orders the results by the from_status field.
func ByFromStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromStatus, opts...).ToFunc()
}

// ByToStatus orders the results by the to_status field.
func ByToStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToStatus, opts...).ToFunc()
}

// ByResolutionReason orders the results by the resolution_reason field.
func ByResolutionReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolutionReason, opts...).ToFunc()
}

// ByNote orders the results by the note field.
func ByNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNote, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// BySessionField orders the results by session field.
func BySessionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionStep(), sql.OrderByField(field, opts...))
	}
}
func newSessionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionInverseTable, AlertSessionFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
	)
}
