// Code generated by ent, DO NOT EDIT.

package llminteraction

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the llminteraction type in the database.
	Label = "llm_interaction"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "interaction_id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldStageID holds the string denoting the stage_id field in the database.
	FieldStageID = "stage_id"
	// FieldExecutionID holds the string denoting the execution_id field in the database.
	FieldExecutionID = "execution_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldInteractionType holds the string denoting the interaction_type field in the database.
	FieldInteractionType = "interaction_type"
	// FieldModelName holds the string denoting the model_name field in the database.
	FieldModelName = "model_name"
	// FieldLastMessageID holds the string denoting the last_message_id field in the database.
	FieldLastMessageID = "last_message_id"
	// FieldLlmRequest holds the string denoting the llm_request field in the database.
	FieldLlmRequest = "llm_request"
	// FieldLlmResponse holds the string denoting the llm_response field in the database.
	FieldLlmResponse = "llm_response"
	// FieldThinkingContent holds the string denoting the thinking_content field in the database.
	FieldThinkingContent = "thinking_content"
	// FieldResponseMetadata holds the string denoting the response_metadata field in the database.
	FieldResponseMetadata = "response_metadata"
	// FieldInputTokens holds the string denoting the input_tokens field in the database.
	FieldInputTokens = "input_tokens"
	// FieldOutputTokens holds the string denoting the output_tokens field in the database.
	FieldOutputTokens = "output_tokens"
	// FieldTotalTokens holds the string denoting the total_tokens field in the database.
	FieldTotalTokens = "total_tokens"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// EdgeSession holds the string denoting the session edge name in mutations.
	EdgeSession = "session"
	// EdgeStage holds the string denoting the stage edge name in mutations.
	EdgeStage = "stage"
	// EdgeAgentExecution holds the string denoting the agent_execution edge name in mutations.
	EdgeAgentExecution = "agent_execution"
	// EdgeLastMessage holds the string denoting the last_message edge name in mutations.
	EdgeLastMessage = "last_message"
	// EdgeTimelineEvents holds the string denoting the timeline_events edge name in mutations.
	EdgeTimelineEvents = "timeline_events"
	// AlertSessionFieldID holds the string denoting the ID field of the AlertSession.
	AlertSessionFieldID = "session_id"
	// StageFieldID holds the string denoting the ID field of the Stage.
	StageFieldID = "stage_id"
	// AgentExecutionFieldID holds the string denoting the ID field of the AgentExecution.
	AgentExecutionFieldID = "execution_id"
	// MessageFieldID holds the string denoting the ID field of the Message.
	MessageFieldID = "message_id"
	// TimelineEventFieldID holds the string denoting the ID field of the TimelineEvent.
	TimelineEventFieldID = "event_id"
	// Table holds the table name of the llminteraction in the database.
	Table = "llm_interactions"
	// SessionTable is the table that holds the session relation/edge.
	SessionTable = "llm_interactions"
	// SessionInverseTable is the table name for the AlertSession entity.
	// It exists in this package in order to avoid circular dependency with the "alertsession" package.
	SessionInverseTable = "alert_sessions"
	// SessionColumn is the table column denoting the session relation/edge.
	SessionColumn = "session_id"
	// StageTable is the table that holds the stage relation/edge.
	StageTable = "llm_interactions"
	// StageInverseTable is the table name for the Stage entity.
	// It exists in this package in order to avoid circular dependency with the "stage" package.
	StageInverseTable = "stages"
	// StageColumn is the table column denoting the stage relation/edge.
	StageColumn = "stage_id"
	// AgentExecutionTable is the table that holds the agent_execution relation/edge.
	AgentExecutionTable = "llm_interactions"
	// AgentExecutionInverseTable is the table name for the AgentExecution entity.
	// It exists in this package in order to avoid circular dependency with the "agentexecution" package.
	AgentExecutionInverseTable = "agent_executions"
	// AgentExecutionColumn is the table column denoting the agent_execution relation/edge.
	AgentExecutionColumn = "execution_id"
	// LastMessageTable is the table that holds the last_message relation/edge.
	LastMessageTable = "llm_interactions"
	// LastMessageInverseTable is the table name for the Message entity.
	// It exists in this package in order to avoid circular dependency with the "message" package.
	LastMessageInverseTable = "messages"
	// LastMessageColumn is the table column denoting the last_message relation/edge.
	LastMessageColumn = "last_message_id"
	// TimelineEventsTable is the table that holds the timeline_events relation/edge.
	TimelineEventsTable = "timeline_events"
	// TimelineEventsInverseTable is the table name for the TimelineEvent entity.
	// It exists in this package in order to avoid circular dependency with the "timelineevent" package.
	TimelineEventsInverseTable = "timeline_events"
	// TimelineEventsColumn is the table column denoting the timeline_events relation/edge.
	TimelineEventsColumn = "llm_interaction_id"
)

// Columns holds all SQL columns for llminteraction fields.
var Columns = []string{
	FieldID,
	FieldSessionID,
	FieldStageID,
	FieldExecutionID,
	FieldCreatedAt,
	FieldInteractionType,
	FieldModelName,
	FieldLastMessageID,
	FieldLlmRequest,
	FieldLlmResponse,
	FieldThinkingContent,
	FieldResponseMetadata,
	FieldInputTokens,
	FieldOutputTokens,
	FieldTotalTokens,
	FieldDurationMs,
	FieldErrorMessage,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// InteractionType defines the type for the "interaction_type" enum field.
type InteractionType string

// InteractionType values.
const (
	InteractionTypeIteration        InteractionType = "iteration"
	InteractionTypeFinalAnalysis    InteractionType = "final_analysis"
	InteractionTypeExecutiveSummary InteractionType = "executive_summary"
	InteractionTypeChatResponse     InteractionType = "chat_response"
	InteractionTypeSummarization    InteractionType = "summarization"
	InteractionTypeSynthesis        InteractionType = "synthesis"
	InteractionTypeForcedConclusion InteractionType = "forced_conclusion"
	InteractionTypeScoring          InteractionType = "scoring"
	InteractionTypeMemoryExtraction InteractionType = "memory_extraction"
)

func (it InteractionType) String() string {
	return string(it)
}

// InteractionTypeValidator is a validator for the "interaction_type" field enum values. It is called by the builders before save.
func InteractionTypeValidator(it InteractionType) error {
	switch it {
	case InteractionTypeIteration, InteractionTypeFinalAnalysis, InteractionTypeExecutiveSummary, InteractionTypeChatResponse, InteractionTypeSummarization, InteractionTypeSynthesis, InteractionTypeForcedConclusion, InteractionTypeScoring, InteractionTypeMemoryExtraction:
		return nil
	default:
		return fmt.Errorf("llminteraction: invalid enum value for interaction_type field: %q", it)
	}
}

// OrderOption defines the ordering options for the LLMInteraction queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByStageID orders the results by the stage_id field.
func ByStageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStageID, opts...).ToFunc()
}

// ByExecutionID orders the results by the execution_id field.
func ByExecutionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExecutionID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByInteractionType orders the results by the interaction_type field.
func ByInteractionType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInteractionType, opts...).ToFunc()
}

// ByModelName orders the results by the model_name field.
func ByModelName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelName, opts...).ToFunc()
}

// ByLastMessageID orders the results by the last_message_id field.
func ByLastMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastMessageID, opts...).ToFunc()
}

// ByThinkingContent orders the results by the thinking_content field.
func ByThinkingContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThinkingContent, opts...).ToFunc()
}

// ByInputTokens orders the results by the input_tokens field.
func ByInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokens, opts...).ToFunc()
}

// ByOutputTokens orders the results by the output_tokens field.
func ByOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTokens, opts...).ToFunc()
}

// ByTotalTokens orders the results by the total_tokens field.
func ByTotalTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalTokens, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// BySessionField orders the results by session field.
func BySessionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionStep(), sql.OrderByField(field, opts...))
	}
}

// ByStageField orders the results by stage field.
func ByStageField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStageStep(), sql.OrderByField(field, opts...))
	}
}

// ByAgentExecutionField orders the results by agent_execution field.
func ByAgentExecutionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAgentExecutionStep(), sql.OrderByField(field, opts...))
	}
}

// ByLastMessageField orders the results by last_message field.
func ByLastMessageField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLastMessageStep(), sql.OrderByField(field, opts...))
	}
}

// ByTimelineEventsCount orders the results by timeline_events count.
func ByTimelineEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTimelineEventsStep(), opts...)
	}
}

// ByTimelineEvents orders the results by timeline_events terms.
func ByTimelineEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTimelineEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSessionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionInverseTable, AlertSessionFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
	)
}
func newStageStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StageInverseTable, StageFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, StageTable, StageColumn),
	)
}
func newAgentExecutionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AgentExecutionInverseTable, AgentExecutionFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AgentExecutionTable, AgentExecutionColumn),
	)
}
func newLastMessageStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LastMessageInverseTable, MessageFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LastMessageTable, LastMessageColumn),
	)
}
func newTimelineEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TimelineEventsInverseTable, TimelineEventFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TimelineEventsTable, TimelineEventsColumn),
	)
}
