// Code generated by ent, DO NOT EDIT.

package investigationmemory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/codeready-toolchain/tarsy/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldContainsFold(FieldID, id))
}

// Project applies equality check predicate on the "project" field. It's identical to ProjectEQ.
func Project(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldProject, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldContent, v))
}

// Confidence applies equality check predicate on the "confidence" field. It's identical to ConfidenceEQ.
func Confidence(v float64) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldConfidence, v))
}

// SeenCount applies equality check predicate on the "seen_count" field. It's identical to SeenCountEQ.
func SeenCount(v int) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldSeenCount, v))
}

// SourceSessionID applies equality check predicate on the "source_session_id" field. It's identical to SourceSessionIDEQ.
func SourceSessionID(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldSourceSessionID, v))
}

// AlertType applies equality check predicate on the "alert_type" field. It's identical to AlertTypeEQ.
func AlertType(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldAlertType, v))
}

// ChainID applies equality check predicate on the "chain_id" field. It's identical to ChainIDEQ.
func ChainID(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldChainID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldUpdatedAt, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldLastSeenAt, v))
}

// Deprecated applies equality check predicate on the "deprecated" field. It's identical to DeprecatedEQ.
func Deprecated(v bool) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldDeprecated, v))
}

// ProjectEQ applies the EQ predicate on the "project" field.
func ProjectEQ(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldProject, v))
}

// ProjectNEQ applies the NEQ predicate on the "project" field.
func ProjectNEQ(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNEQ(FieldProject, v))
}

// ProjectIn applies the In predicate on the "project" field.
func ProjectIn(vs ...string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldIn(FieldProject, vs...))
}

// ProjectNotIn applies the NotIn predicate on the "project" field.
func ProjectNotIn(vs ...string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNotIn(FieldProject, vs...))
}

// ProjectGT applies the GT predicate on the "project" field.
func ProjectGT(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldGT(FieldProject, v))
}

// ProjectGTE applies the GTE predicate on the "project" field.
func ProjectGTE(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldGTE(FieldProject, v))
}

// ProjectLT applies the LT predicate on the "project" field.
func ProjectLT(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldLT(FieldProject, v))
}

// ProjectLTE applies the LTE predicate on the "project" field.
func ProjectLTE(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldLTE(FieldProject, v))
}

// ProjectContains applies the Contains predicate on the "project" field.
func ProjectContains(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldContains(FieldProject, v))
}

// ProjectHasPrefix applies the HasPrefix predicate on the "project" field.
func ProjectHasPrefix(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldHasPrefix(FieldProject, v))
}

// ProjectHasSuffix applies the HasSuffix predicate on the "project" field.
func ProjectHasSuffix(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldHasSuffix(FieldProject, v))
}

// ProjectEqualFold applies the EqualFold predicate on the "project" field.
func ProjectEqualFold(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEqualFold(FieldProject, v))
}

// ProjectContainsFold applies the ContainsFold predicate on the "project" field.
func ProjectContainsFold(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldContainsFold(FieldProject, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldContainsFold(FieldContent, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v Category) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v Category) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...Category) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...Category) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNotIn(FieldCategory, vs...))
}

// ValenceEQ applies the EQ predicate on the "valence" field.
func ValenceEQ(v Valence) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldValence, v))
}

// ValenceNEQ applies the NEQ predicate on the "valence" field.
func ValenceNEQ(v Valence) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNEQ(FieldValence, v))
}

// ValenceIn applies the In predicate on the "valence" field.
func ValenceIn(vs ...Valence) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldIn(FieldValence, vs...))
}

// ValenceNotIn applies the NotIn predicate on the "valence" field.
func ValenceNotIn(vs ...Valence) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNotIn(FieldValence, vs...))
}

// ConfidenceEQ applies the EQ predicate on the "confidence" field.
func ConfidenceEQ(v float64) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldConfidence, v))
}

// ConfidenceNEQ applies the NEQ predicate on the "confidence" field.
func ConfidenceNEQ(v float64) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNEQ(FieldConfidence, v))
}

// ConfidenceIn applies the In predicate on the "confidence" field.
func ConfidenceIn(vs ...float64) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldIn(FieldConfidence, vs...))
}

// ConfidenceNotIn applies the NotIn predicate on the "confidence" field.
func ConfidenceNotIn(vs ...float64) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNotIn(FieldConfidence, vs...))
}

// ConfidenceGT applies the GT predicate on the "confidence" field.
func ConfidenceGT(v float64) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldGT(FieldConfidence, v))
}

// ConfidenceGTE applies the GTE predicate on the "confidence" field.
func ConfidenceGTE(v float64) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldGTE(FieldConfidence, v))
}

// ConfidenceLT applies the LT predicate on the "confidence" field.
func ConfidenceLT(v float64) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldLT(FieldConfidence, v))
}

// ConfidenceLTE applies the LTE predicate on the "confidence" field.
func ConfidenceLTE(v float64) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldLTE(FieldConfidence, v))
}

// SeenCountEQ applies the EQ predicate on the "seen_count" field.
func SeenCountEQ(v int) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldSeenCount, v))
}

// SeenCountNEQ applies the NEQ predicate on the "seen_count" field.
func SeenCountNEQ(v int) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNEQ(FieldSeenCount, v))
}

// SeenCountIn applies the In predicate on the "seen_count" field.
func SeenCountIn(vs ...int) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldIn(FieldSeenCount, vs...))
}

// SeenCountNotIn applies the NotIn predicate on the "seen_count" field.
func SeenCountNotIn(vs ...int) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNotIn(FieldSeenCount, vs...))
}

// SeenCountGT applies the GT predicate on the "seen_count" field.
func SeenCountGT(v int) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldGT(FieldSeenCount, v))
}

// SeenCountGTE applies the GTE predicate on the "seen_count" field.
func SeenCountGTE(v int) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldGTE(FieldSeenCount, v))
}

// SeenCountLT applies the LT predicate on the "seen_count" field.
func SeenCountLT(v int) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldLT(FieldSeenCount, v))
}

// SeenCountLTE applies the LTE predicate on the "seen_count" field.
func SeenCountLTE(v int) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldLTE(FieldSeenCount, v))
}

// SourceSessionIDEQ applies the EQ predicate on the "source_session_id" field.
func SourceSessionIDEQ(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldSourceSessionID, v))
}

// SourceSessionIDNEQ applies the NEQ predicate on the "source_session_id" field.
func SourceSessionIDNEQ(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNEQ(FieldSourceSessionID, v))
}

// SourceSessionIDIn applies the In predicate on the "source_session_id" field.
func SourceSessionIDIn(vs ...string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldIn(FieldSourceSessionID, vs...))
}

// SourceSessionIDNotIn applies the NotIn predicate on the "source_session_id" field.
func SourceSessionIDNotIn(vs ...string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNotIn(FieldSourceSessionID, vs...))
}

// SourceSessionIDGT applies the GT predicate on the "source_session_id" field.
func SourceSessionIDGT(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldGT(FieldSourceSessionID, v))
}

// SourceSessionIDGTE applies the GTE predicate on the "source_session_id" field.
func SourceSessionIDGTE(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldGTE(FieldSourceSessionID, v))
}

// SourceSessionIDLT applies the LT predicate on the "source_session_id" field.
func SourceSessionIDLT(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldLT(FieldSourceSessionID, v))
}

// SourceSessionIDLTE applies the LTE predicate on the "source_session_id" field.
func SourceSessionIDLTE(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldLTE(FieldSourceSessionID, v))
}

// SourceSessionIDContains applies the Contains predicate on the "source_session_id" field.
func SourceSessionIDContains(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldContains(FieldSourceSessionID, v))
}

// SourceSessionIDHasPrefix applies the HasPrefix predicate on the "source_session_id" field.
func SourceSessionIDHasPrefix(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldHasPrefix(FieldSourceSessionID, v))
}

// SourceSessionIDHasSuffix applies the HasSuffix predicate on the "source_session_id" field.
func SourceSessionIDHasSuffix(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldHasSuffix(FieldSourceSessionID, v))
}

// SourceSessionIDEqualFold applies the EqualFold predicate on the "source_session_id" field.
func SourceSessionIDEqualFold(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEqualFold(FieldSourceSessionID, v))
}

// SourceSessionIDContainsFold applies the ContainsFold predicate on the "source_session_id" field.
func SourceSessionIDContainsFold(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldContainsFold(FieldSourceSessionID, v))
}

// AlertTypeEQ applies the EQ predicate on the "alert_type" field.
func AlertTypeEQ(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldAlertType, v))
}

// AlertTypeNEQ applies the NEQ predicate on the "alert_type" field.
func AlertTypeNEQ(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNEQ(FieldAlertType, v))
}

// AlertTypeIn applies the In predicate on the "alert_type" field.
func AlertTypeIn(vs ...string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldIn(FieldAlertType, vs...))
}

// AlertTypeNotIn applies the NotIn predicate on the "alert_type" field.
func AlertTypeNotIn(vs ...string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNotIn(FieldAlertType, vs...))
}

// AlertTypeGT applies the GT predicate on the "alert_type" field.
func AlertTypeGT(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldGT(FieldAlertType, v))
}

// AlertTypeGTE applies the GTE predicate on the "alert_type" field.
func AlertTypeGTE(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldGTE(FieldAlertType, v))
}

// AlertTypeLT applies the LT predicate on the "alert_type" field.
func AlertTypeLT(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldLT(FieldAlertType, v))
}

// AlertTypeLTE applies the LTE predicate on the "alert_type" field.
func AlertTypeLTE(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldLTE(FieldAlertType, v))
}

// AlertTypeContains applies the Contains predicate on the "alert_type" field.
func AlertTypeContains(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldContains(FieldAlertType, v))
}

// AlertTypeHasPrefix applies the HasPrefix predicate on the "alert_type" field.
func AlertTypeHasPrefix(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldHasPrefix(FieldAlertType, v))
}

// AlertTypeHasSuffix applies the HasSuffix predicate on the "alert_type" field.
func AlertTypeHasSuffix(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldHasSuffix(FieldAlertType, v))
}

// AlertTypeIsNil applies the IsNil predicate on the "alert_type" field.
func AlertTypeIsNil() predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldIsNull(FieldAlertType))
}

// AlertTypeNotNil applies the NotNil predicate on the "alert_type" field.
func AlertTypeNotNil() predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNotNull(FieldAlertType))
}

// AlertTypeEqualFold applies the EqualFold predicate on the "alert_type" field.
func AlertTypeEqualFold(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEqualFold(FieldAlertType, v))
}

// AlertTypeContainsFold applies the ContainsFold predicate on the "alert_type" field.
func AlertTypeContainsFold(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldContainsFold(FieldAlertType, v))
}

// ChainIDEQ applies the EQ predicate on the "chain_id" field.
func ChainIDEQ(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldChainID, v))
}

// ChainIDNEQ applies the NEQ predicate on the "chain_id" field.
func ChainIDNEQ(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNEQ(FieldChainID, v))
}

// ChainIDIn applies the In predicate on the "chain_id" field.
func ChainIDIn(vs ...string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldIn(FieldChainID, vs...))
}

// ChainIDNotIn applies the NotIn predicate on the "chain_id" field.
func ChainIDNotIn(vs ...string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNotIn(FieldChainID, vs...))
}

// ChainIDGT applies the GT predicate on the "chain_id" field.
func ChainIDGT(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldGT(FieldChainID, v))
}

// ChainIDGTE applies the GTE predicate on the "chain_id" field.
func ChainIDGTE(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldGTE(FieldChainID, v))
}

// ChainIDLT applies the LT predicate on the "chain_id" field.
func ChainIDLT(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldLT(FieldChainID, v))
}

// ChainIDLTE applies the LTE predicate on the "chain_id" field.
func ChainIDLTE(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldLTE(FieldChainID, v))
}

// ChainIDContains applies the Contains predicate on the "chain_id" field.
func ChainIDContains(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldContains(FieldChainID, v))
}

// ChainIDHasPrefix applies the HasPrefix predicate on the "chain_id" field.
func ChainIDHasPrefix(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldHasPrefix(FieldChainID, v))
}

// ChainIDHasSuffix applies the HasSuffix predicate on the "chain_id" field.
func ChainIDHasSuffix(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldHasSuffix(FieldChainID, v))
}

// ChainIDIsNil applies the IsNil predicate on the "chain_id" field.
func ChainIDIsNil() predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldIsNull(FieldChainID))
}

// ChainIDNotNil applies the NotNil predicate on the "chain_id" field.
func ChainIDNotNil() predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNotNull(FieldChainID))
}

// ChainIDEqualFold applies the EqualFold predicate on the "chain_id" field.
func ChainIDEqualFold(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEqualFold(FieldChainID, v))
}

// ChainIDContainsFold applies the ContainsFold predicate on the "chain_id" field.
func ChainIDContainsFold(v string) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldContainsFold(FieldChainID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldLTE(FieldUpdatedAt, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldLTE(FieldLastSeenAt, v))
}

// DeprecatedEQ applies the EQ predicate on the "deprecated" field.
func DeprecatedEQ(v bool) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldEQ(FieldDeprecated, v))
}

// DeprecatedNEQ applies the NEQ predicate on the "deprecated" field.
func DeprecatedNEQ(v bool) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.FieldNEQ(FieldDeprecated, v))
}

// HasSourceSession applies the HasEdge predicate on the "source_session" edge.
func HasSourceSession() predicate.InvestigationMemory {
	return predicate.InvestigationMemory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SourceSessionTable, SourceSessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceSessionWith applies the HasEdge predicate on the "source_session" edge with a given conditions (other predicates).
func HasSourceSessionWith(preds ...predicate.AlertSession) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(func(s *sql.Selector) {
		step := newSourceSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInjectedIntoSessions applies the HasEdge predicate on the "injected_into_sessions" edge.
func HasInjectedIntoSessions() predicate.InvestigationMemory {
	return predicate.InvestigationMemory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, InjectedIntoSessionsTable, InjectedIntoSessionsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInjectedIntoSessionsWith applies the HasEdge predicate on the "injected_into_sessions" edge with a given conditions (other predicates).
func HasInjectedIntoSessionsWith(preds ...predicate.AlertSession) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(func(s *sql.Selector) {
		step := newInjectedIntoSessionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvestigationMemory) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvestigationMemory) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvestigationMemory) predicate.InvestigationMemory {
	return predicate.InvestigationMemory(sql.NotPredicates(p))
}
