// Code generated by ent, DO NOT EDIT.

package timelineevent

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the timelineevent type in the database.
	Label = "timeline_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "event_id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldStageID holds the string denoting the stage_id field in the database.
	FieldStageID = "stage_id"
	// FieldExecutionID holds the string denoting the execution_id field in the database.
	FieldExecutionID = "execution_id"
	// FieldParentExecutionID holds the string denoting the parent_execution_id field in the database.
	FieldParentExecutionID = "parent_execution_id"
	// FieldSequenceNumber holds the string denoting the sequence_number field in the database.
	FieldSequenceNumber = "sequence_number"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldLlmInteractionID holds the string denoting the llm_interaction_id field in the database.
	FieldLlmInteractionID = "llm_interaction_id"
	// FieldMcpInteractionID holds the string denoting the mcp_interaction_id field in the database.
	FieldMcpInteractionID = "mcp_interaction_id"
	// EdgeSession holds the string denoting the session edge name in mutations.
	EdgeSession = "session"
	// EdgeStage holds the string denoting the stage edge name in mutations.
	EdgeStage = "stage"
	// EdgeAgentExecution holds the string denoting the agent_execution edge name in mutations.
	EdgeAgentExecution = "agent_execution"
	// EdgeParentExecution holds the string denoting the parent_execution edge name in mutations.
	EdgeParentExecution = "parent_execution"
	// EdgeLlmInteraction holds the string denoting the llm_interaction edge name in mutations.
	EdgeLlmInteraction = "llm_interaction"
	// EdgeMcpInteraction holds the string denoting the mcp_interaction edge name in mutations.
	EdgeMcpInteraction = "mcp_interaction"
	// AlertSessionFieldID holds the string denoting the ID field of the AlertSession.
	AlertSessionFieldID = "session_id"
	// StageFieldID holds the string denoting the ID field of the Stage.
	StageFieldID = "stage_id"
	// AgentExecutionFieldID holds the string denoting the ID field of the AgentExecution.
	AgentExecutionFieldID = "execution_id"
	// LLMInteractionFieldID holds the string denoting the ID field of the LLMInteraction.
	LLMInteractionFieldID = "interaction_id"
	// MCPInteractionFieldID holds the string denoting the ID field of the MCPInteraction.
	MCPInteractionFieldID = "interaction_id"
	// Table holds the table name of the timelineevent in the database.
	Table = "timeline_events"
	// SessionTable is the table that holds the session relation/edge.
	SessionTable = "timeline_events"
	// SessionInverseTable is the table name for the AlertSession entity.
	// It exists in this package in order to avoid circular dependency with the "alertsession" package.
	SessionInverseTable = "alert_sessions"
	// SessionColumn is the table column denoting the session relation/edge.
	SessionColumn = "session_id"
	// StageTable is the table that holds the stage relation/edge.
	StageTable = "timeline_events"
	// StageInverseTable is the table name for the Stage entity.
	// It exists in this package in order to avoid circular dependency with the "stage" package.
	StageInverseTable = "stages"
	// StageColumn is the table column denoting the stage relation/edge.
	StageColumn = "stage_id"
	// AgentExecutionTable is the table that holds the agent_execution relation/edge.
	AgentExecutionTable = "timeline_events"
	// AgentExecutionInverseTable is the table name for the AgentExecution entity.
	// It exists in this package in order to avoid circular dependency with the "agentexecution" package.
	AgentExecutionInverseTable = "agent_executions"
	// AgentExecutionColumn is the table column denoting the agent_execution relation/edge.
	AgentExecutionColumn = "execution_id"
	// ParentExecutionTable is the table that holds the parent_execution relation/edge.
	ParentExecutionTable = "timeline_events"
	// ParentExecutionInverseTable is the table name for the AgentExecution entity.
	// It exists in this package in order to avoid circular dependency with the "agentexecution" package.
	ParentExecutionInverseTable = "agent_executions"
	// ParentExecutionColumn is the table column denoting the parent_execution relation/edge.
	ParentExecutionColumn = "parent_execution_id"
	// LlmInteractionTable is the table that holds the llm_interaction relation/edge.
	LlmInteractionTable = "timeline_events"
	// LlmInteractionInverseTable is the table name for the LLMInteraction entity.
	// It exists in this package in order to avoid circular dependency with the "llminteraction" package.
	LlmInteractionInverseTable = "llm_interactions"
	// LlmInteractionColumn is the table column denoting the llm_interaction relation/edge.
	LlmInteractionColumn = "llm_interaction_id"
	// McpInteractionTable is the table that holds the mcp_interaction relation/edge.
	McpInteractionTable = "timeline_events"
	// McpInteractionInverseTable is the table name for the MCPInteraction entity.
	// It exists in this package in order to avoid circular dependency with the "mcpinteraction" package.
	McpInteractionInverseTable = "mcp_interactions"
	// McpInteractionColumn is the table column denoting the mcp_interaction relation/edge.
	McpInteractionColumn = "mcp_interaction_id"
)

// Columns holds all SQL columns for timelineevent fields.
var Columns = []string{
	FieldID,
	FieldSessionID,
	FieldStageID,
	FieldExecutionID,
	FieldParentExecutionID,
	FieldSequenceNumber,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldEventType,
	FieldStatus,
	FieldContent,
	FieldMetadata,
	FieldLlmInteractionID,
	FieldMcpInteractionID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// EventType defines the type for the "event_type" enum field.
type EventType string

// EventType values.
const (
	EventTypeLlmThinking        EventType = "llm_thinking"
	EventTypeLlmResponse        EventType = "llm_response"
	EventTypeLlmToolCall        EventType = "llm_tool_call"
	EventTypeMcpToolSummary     EventType = "mcp_tool_summary"
	EventTypeError              EventType = "error"
	EventTypeUserQuestion       EventType = "user_question"
	EventTypeExecutiveSummary   EventType = "executive_summary"
	EventTypeFinalAnalysis      EventType = "final_analysis"
	EventTypeCodeExecution      EventType = "code_execution"
	EventTypeGoogleSearchResult EventType = "google_search_result"
	EventTypeURLContextResult   EventType = "url_context_result"
	EventTypeTaskAssigned       EventType = "task_assigned"
	EventTypeProviderFallback   EventType = "provider_fallback"
	EventTypeSkillLoaded        EventType = "skill_loaded"
	EventTypeMemoryInjected     EventType = "memory_injected"
)

func (et EventType) String() string {
	return string(et)
}

// EventTypeValidator is a validator for the "event_type" field enum values. It is called by the builders before save.
func EventTypeValidator(et EventType) error {
	switch et {
	case EventTypeLlmThinking, EventTypeLlmResponse, EventTypeLlmToolCall, EventTypeMcpToolSummary, EventTypeError, EventTypeUserQuestion, EventTypeExecutiveSummary, EventTypeFinalAnalysis, EventTypeCodeExecution, EventTypeGoogleSearchResult, EventTypeURLContextResult, EventTypeTaskAssigned, EventTypeProviderFallback, EventTypeSkillLoaded, EventTypeMemoryInjected:
		return nil
	default:
		return fmt.Errorf("timelineevent: invalid enum value for event_type field: %q", et)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusStreaming is the default value of the Status enum.
const DefaultStatus = StatusStreaming

// Status values.
const (
	StatusStreaming Status = "streaming"
	StatusCompleted Status = "completed"
	StatusFailed    Status = "failed"
	StatusCancelled Status = "cancelled"
	StatusTimedOut  Status = "timed_out"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusStreaming, StatusCompleted, StatusFailed, StatusCancelled, StatusTimedOut:
		return nil
	default:
		return fmt.Errorf("timelineevent: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the TimelineEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByStageID orders the results by the stage_id field.
func ByStageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStageID, opts...).ToFunc()
}

// ByExecutionID orders the results by the execution_id field.
func ByExecutionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExecutionID, opts...).ToFunc()
}

// ByParentExecutionID orders the results by the parent_execution_id field.
func ByParentExecutionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentExecutionID, opts...).ToFunc()
}

// BySequenceNumber orders the results by the sequence_number field.
func BySequenceNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSequenceNumber, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByLlmInteractionID orders the results by the llm_interaction_id field.
func ByLlmInteractionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLlmInteractionID, opts...).ToFunc()
}

// ByMcpInteractionID orders the results by the mcp_interaction_id field.
func ByMcpInteractionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMcpInteractionID, opts...).ToFunc()
}

// BySessionField orders the results by session field.
func BySessionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionStep(), sql.OrderByField(field, opts...))
	}
}

// ByStageField orders the results by stage field.
func ByStageField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStageStep(), sql.OrderByField(field, opts...))
	}
}

// ByAgentExecutionField orders the results by agent_execution field.
func ByAgentExecutionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAgentExecutionStep(), sql.OrderByField(field, opts...))
	}
}

// ByParentExecutionField orders the results by parent_execution field.
func ByParentExecutionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParentExecutionStep(), sql.OrderByField(field, opts...))
	}
}

// ByLlmInteractionField orders the results by llm_interaction field.
func ByLlmInteractionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLlmInteractionStep(), sql.OrderByField(field, opts...))
	}
}

// ByMcpInteractionField orders the results by mcp_interaction field.
func ByMcpInteractionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMcpInteractionStep(), sql.OrderByField(field, opts...))
	}
}
func newSessionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionInverseTable, AlertSessionFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
	)
}
func newStageStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StageInverseTable, StageFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, StageTable, StageColumn),
	)
}
func newAgentExecutionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AgentExecutionInverseTable, AgentExecutionFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AgentExecutionTable, AgentExecutionColumn),
	)
}
func newParentExecutionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ParentExecutionInverseTable, AgentExecutionFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ParentExecutionTable, ParentExecutionColumn),
	)
}
func newLlmInteractionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LlmInteractionInverseTable, LLMInteractionFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LlmInteractionTable, LlmInteractionColumn),
	)
}
func newMcpInteractionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(McpInteractionInverseTable, MCPInteractionFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, McpInteractionTable, McpInteractionColumn),
	)
}
