// Code generated by ent, DO NOT EDIT.

package stage

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the stage type in the database.
	Label = "stage"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "stage_id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldStageName holds the string denoting the stage_name field in the database.
	FieldStageName = "stage_name"
	// FieldStageIndex holds the string denoting the stage_index field in the database.
	FieldStageIndex = "stage_index"
	// FieldExpectedAgentCount holds the string denoting the expected_agent_count field in the database.
	FieldExpectedAgentCount = "expected_agent_count"
	// FieldParallelType holds the string denoting the parallel_type field in the database.
	FieldParallelType = "parallel_type"
	// FieldSuccessPolicy holds the string denoting the success_policy field in the database.
	FieldSuccessPolicy = "success_policy"
	// FieldStageType holds the string denoting the stage_type field in the database.
	FieldStageType = "stage_type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldChatID holds the string denoting the chat_id field in the database.
	FieldChatID = "chat_id"
	// FieldChatUserMessageID holds the string denoting the chat_user_message_id field in the database.
	FieldChatUserMessageID = "chat_user_message_id"
	// FieldReferencedStageID holds the string denoting the referenced_stage_id field in the database.
	FieldReferencedStageID = "referenced_stage_id"
	// EdgeSession holds the string denoting the session edge name in mutations.
	EdgeSession = "session"
	// EdgeAgentExecutions holds the string denoting the agent_executions edge name in mutations.
	EdgeAgentExecutions = "agent_executions"
	// EdgeTimelineEvents holds the string denoting the timeline_events edge name in mutations.
	EdgeTimelineEvents = "timeline_events"
	// EdgeMessages holds the string denoting the messages edge name in mutations.
	EdgeMessages = "messages"
	// EdgeLlmInteractions holds the string denoting the llm_interactions edge name in mutations.
	EdgeLlmInteractions = "llm_interactions"
	// EdgeMcpInteractions holds the string denoting the mcp_interactions edge name in mutations.
	EdgeMcpInteractions = "mcp_interactions"
	// EdgeChat holds the string denoting the chat edge name in mutations.
	EdgeChat = "chat"
	// EdgeChatUserMessage holds the string denoting the chat_user_message edge name in mutations.
	EdgeChatUserMessage = "chat_user_message"
	// EdgeReferencingStages holds the string denoting the referencing_stages edge name in mutations.
	EdgeReferencingStages = "referencing_stages"
	// EdgeReferencedStage holds the string denoting the referenced_stage edge name in mutations.
	EdgeReferencedStage = "referenced_stage"
	// AlertSessionFieldID holds the string denoting the ID field of the AlertSession.
	AlertSessionFieldID = "session_id"
	// AgentExecutionFieldID holds the string denoting the ID field of the AgentExecution.
	AgentExecutionFieldID = "execution_id"
	// TimelineEventFieldID holds the string denoting the ID field of the TimelineEvent.
	TimelineEventFieldID = "event_id"
	// MessageFieldID holds the string denoting the ID field of the Message.
	MessageFieldID = "message_id"
	// LLMInteractionFieldID holds the string denoting the ID field of the LLMInteraction.
	LLMInteractionFieldID = "interaction_id"
	// MCPInteractionFieldID holds the string denoting the ID field of the MCPInteraction.
	MCPInteractionFieldID = "interaction_id"
	// ChatFieldID holds the string denoting the ID field of the Chat.
	ChatFieldID = "chat_id"
	// ChatUserMessageFieldID holds the string denoting the ID field of the ChatUserMessage.
	ChatUserMessageFieldID = "message_id"
	// Table holds the table name of the stage in the database.
	Table = "stages"
	// SessionTable is the table that holds the session relation/edge.
	SessionTable = "stages"
	// SessionInverseTable is the table name for the AlertSession entity.
	// It exists in this package in order to avoid circular dependency with the "alertsession" package.
	SessionInverseTable = "alert_sessions"
	// SessionColumn is the table column denoting the session relation/edge.
	SessionColumn = "session_id"
	// AgentExecutionsTable is the table that holds the agent_executions relation/edge.
	AgentExecutionsTable = "agent_executions"
	// AgentExecutionsInverseTable is the table name for the AgentExecution entity.
	// It exists in this package in order to avoid circular dependency with the "agentexecution" package.
	AgentExecutionsInverseTable = "agent_executions"
	// AgentExecutionsColumn is the table column denoting the agent_executions relation/edge.
	AgentExecutionsColumn = "stage_id"
	// TimelineEventsTable is the table that holds the timeline_events relation/edge.
	TimelineEventsTable = "timeline_events"
	// TimelineEventsInverseTable is the table name for the TimelineEvent entity.
	// It exists in this package in order to avoid circular dependency with the "timelineevent" package.
	TimelineEventsInverseTable = "timeline_events"
	// TimelineEventsColumn is the table column denoting the timeline_events relation/edge.
	TimelineEventsColumn = "stage_id"
	// MessagesTable is the table that holds the messages relation/edge.
	MessagesTable = "messages"
	// MessagesInverseTable is the table name for the Message entity.
	// It exists in this package in order to avoid circular dependency with the "message" package.
	MessagesInverseTable = "messages"
	// MessagesColumn is the table column denoting the messages relation/edge.
	MessagesColumn = "stage_id"
	// LlmInteractionsTable is the table that holds the llm_interactions relation/edge.
	LlmInteractionsTable = "llm_interactions"
	// LlmInteractionsInverseTable is the table name for the LLMInteraction entity.
	// It exists in this package in order to avoid circular dependency with the "llminteraction" package.
	LlmInteractionsInverseTable = "llm_interactions"
	// LlmInteractionsColumn is the table column denoting the llm_interactions relation/edge.
	LlmInteractionsColumn = "stage_id"
	// McpInteractionsTable is the table that holds the mcp_interactions relation/edge.
	McpInteractionsTable = "mcp_interactions"
	// McpInteractionsInverseTable is the table name for the MCPInteraction entity.
	// It exists in this package in order to avoid circular dependency with the "mcpinteraction" package.
	McpInteractionsInverseTable = "mcp_interactions"
	// McpInteractionsColumn is the table column denoting the mcp_interactions relation/edge.
	McpInteractionsColumn = "stage_id"
	// ChatTable is the table that holds the chat relation/edge.
	ChatTable = "stages"
	// ChatInverseTable is the table name for the Chat entity.
	// It exists in this package in order to avoid circular dependency with the "chat" package.
	ChatInverseTable = "chats"
	// ChatColumn is the table column denoting the chat relation/edge.
	ChatColumn = "chat_id"
	// ChatUserMessageTable is the table that holds the chat_user_message relation/edge.
	ChatUserMessageTable = "stages"
	// ChatUserMessageInverseTable is the table name for the ChatUserMessage entity.
	// It exists in this package in order to avoid circular dependency with the "chatusermessage" package.
	ChatUserMessageInverseTable = "chat_user_messages"
	// ChatUserMessageColumn is the table column denoting the chat_user_message relation/edge.
	ChatUserMessageColumn = "chat_user_message_id"
	// ReferencingStagesTable is the table that holds the referencing_stages relation/edge.
	ReferencingStagesTable = "stages"
	// ReferencingStagesColumn is the table column denoting the referencing_stages relation/edge.
	ReferencingStagesColumn = "referenced_stage_id"
	// ReferencedStageTable is the table that holds the referenced_stage relation/edge.
	ReferencedStageTable = "stages"
	// ReferencedStageColumn is the table column denoting the referenced_stage relation/edge.
	ReferencedStageColumn = "referenced_stage_id"
)

// Columns holds all SQL columns for stage fields.
var Columns = []string{
	FieldID,
	FieldSessionID,
	FieldStageName,
	FieldStageIndex,
	FieldExpectedAgentCount,
	FieldParallelType,
	FieldSuccessPolicy,
	FieldStageType,
	FieldStatus,
	FieldStartedAt,
	FieldCompletedAt,
	FieldDurationMs,
	FieldErrorMessage,
	FieldChatID,
	FieldChatUserMessageID,
	FieldReferencedStageID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// ParallelType defines the type for the "parallel_type" enum field.
type ParallelType string

// ParallelType values.
const (
	ParallelTypeMultiAgent ParallelType = "multi_agent"
	ParallelTypeReplica    ParallelType = "replica"
)

func (pt ParallelType) String() string {
	return string(pt)
}

// ParallelTypeValidator is a validator for the "parallel_type" field enum values. It is called by the builders before save.
func ParallelTypeValidator(pt ParallelType) error {
	switch pt {
	case ParallelTypeMultiAgent, ParallelTypeReplica:
		return nil
	default:
		return fmt.Errorf("stage: invalid enum value for parallel_type field: %q", pt)
	}
}

// SuccessPolicy defines the type for the "success_policy" enum field.
type SuccessPolicy string

// SuccessPolicy values.
const (
	SuccessPolicyAll SuccessPolicy = "all"
	SuccessPolicyAny SuccessPolicy = "any"
)

func (sp SuccessPolicy) String() string {
	return string(sp)
}

// SuccessPolicyValidator is a validator for the "success_policy" field enum values. It is called by the builders before save.
func SuccessPolicyValidator(sp SuccessPolicy) error {
	switch sp {
	case SuccessPolicyAll, SuccessPolicyAny:
		return nil
	default:
		return fmt.Errorf("stage: invalid enum value for success_policy field: %q", sp)
	}
}

// StageType defines the type for the "stage_type" enum field.
type StageType string

// StageTypeInvestigation is the default value of the StageType enum.
const DefaultStageType = StageTypeInvestigation

// StageType values.
const (
	StageTypeInvestigation StageType = "investigation"
	StageTypeSynthesis     StageType = "synthesis"
	StageTypeChat          StageType = "chat"
	StageTypeExecSummary   StageType = "exec_summary"
	StageTypeScoring       StageType = "scoring"
	StageTypeAction        StageType = "action"
)

func (st StageType) String() string {
	return string(st)
}

// StageTypeValidator is a validator for the "stage_type" field enum values. It is called by the builders before save.
func StageTypeValidator(st StageType) error {
	switch st {
	case StageTypeInvestigation, StageTypeSynthesis, StageTypeChat, StageTypeExecSummary, StageTypeScoring, StageTypeAction:
		return nil
	default:
		return fmt.Errorf("stage: invalid enum value for stage_type field: %q", st)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending   Status = "pending"
	StatusActive    Status = "active"
	StatusCompleted Status = "completed"
	StatusFailed    Status = "failed"
	StatusTimedOut  Status = "timed_out"
	StatusCancelled Status = "cancelled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusActive, StatusCompleted, StatusFailed, StatusTimedOut, StatusCancelled:
		return nil
	default:
		return fmt.Errorf("stage: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Stage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByStageName orders the results by the stage_name field.
func ByStageName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStageName, opts...).ToFunc()
}

// ByStageIndex orders the results by the stage_index field.
func ByStageIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStageIndex, opts...).ToFunc()
}

// ByExpectedAgentCount orders the results by the expected_agent_count field.
func ByExpectedAgentCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpectedAgentCount, opts...).ToFunc()
}

// ByParallelType orders the results by the parallel_type field.
func ByParallelType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParallelType, opts...).ToFunc()
}

// BySuccessPolicy orders the results by the success_policy field.
func BySuccessPolicy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccessPolicy, opts...).ToFunc()
}

// ByStageType orders the results by the stage_type field.
func ByStageType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStageType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByChatID orders the results by the chat_id field.
func ByChatID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChatID, opts...).ToFunc()
}

// ByChatUserMessageID orders the results by the chat_user_message_id field.
func ByChatUserMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChatUserMessageID, opts...).ToFunc()
}

// ByReferencedStageID orders the results by the referenced_stage_id field.
func ByReferencedStageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferencedStageID, opts...).ToFunc()
}

// BySessionField orders the results by session field.
func BySessionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionStep(), sql.OrderByField(field, opts...))
	}
}

// ByAgentExecutionsCount orders the results by agent_executions count.
func ByAgentExecutionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAgentExecutionsStep(), opts...)
	}
}

// ByAgentExecutions orders the results by agent_executions terms.
func ByAgentExecutions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAgentExecutionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTimelineEventsCount orders the results by timeline_events count.
func ByTimelineEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTimelineEventsStep(), opts...)
	}
}

// ByTimelineEvents orders the results by timeline_events terms.
func ByTimelineEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTimelineEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByMessagesCount orders the results by messages count.
func ByMessagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMessagesStep(), opts...)
	}
}

// ByMessages orders the results by messages terms.
func ByMessages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMessagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByLlmInteractionsCount orders the results by llm_interactions count.
func ByLlmInteractionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLlmInteractionsStep(), opts...)
	}
}

// ByLlmInteractions orders the results by llm_interactions terms.
func ByLlmInteractions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLlmInteractionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByMcpInteractionsCount orders the results by mcp_interactions count.
func ByMcpInteractionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMcpInteractionsStep(), opts...)
	}
}

// ByMcpInteractions orders the results by mcp_interactions terms.
func ByMcpInteractions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMcpInteractionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByChatField orders the results by chat field.
func ByChatField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChatStep(), sql.OrderByField(field, opts...))
	}
}

// ByChatUserMessageField orders the results by chat_user_message field.
func ByChatUserMessageField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChatUserMessageStep(), sql.OrderByField(field, opts...))
	}
}

// ByReferencingStagesCount orders the results by referencing_stages count.
func ByReferencingStagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReferencingStagesStep(), opts...)
	}
}

// ByReferencingStages orders the results by referencing_stages terms.
func ByReferencingStages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReferencingStagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByReferencedStageField orders the results by referenced_stage field.
func ByReferencedStageField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReferencedStageStep(), sql.OrderByField(field, opts...))
	}
}
func newSessionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionInverseTable, AlertSessionFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
	)
}
func newAgentExecutionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AgentExecutionsInverseTable, AgentExecutionFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AgentExecutionsTable, AgentExecutionsColumn),
	)
}
func newTimelineEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TimelineEventsInverseTable, TimelineEventFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TimelineEventsTable, TimelineEventsColumn),
	)
}
func newMessagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MessagesInverseTable, MessageFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
	)
}
func newLlmInteractionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LlmInteractionsInverseTable, LLMInteractionFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LlmInteractionsTable, LlmInteractionsColumn),
	)
}
func newMcpInteractionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(McpInteractionsInverseTable, MCPInteractionFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, McpInteractionsTable, McpInteractionsColumn),
	)
}
func newChatStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChatInverseTable, ChatFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChatTable, ChatColumn),
	)
}
func newChatUserMessageStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChatUserMessageInverseTable, ChatUserMessageFieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, ChatUserMessageTable, ChatUserMessageColumn),
	)
}
func newReferencingStagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ReferencingStagesTable, ReferencingStagesColumn),
	)
}
func newReferencedStageStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ReferencedStageTable, ReferencedStageColumn),
	)
}
