// Code generated by ent, DO NOT EDIT.

package stage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/codeready-toolchain/tarsy/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Stage {
	return predicate.Stage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Stage {
	return predicate.Stage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Stage {
	return predicate.Stage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Stage {
	return predicate.Stage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Stage {
	return predicate.Stage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Stage {
	return predicate.Stage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Stage {
	return predicate.Stage(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Stage {
	return predicate.Stage(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Stage {
	return predicate.Stage(sql.FieldContainsFold(FieldID, id))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldSessionID, v))
}

// StageName applies equality check predicate on the "stage_name" field. It's identical to StageNameEQ.
func StageName(v string) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldStageName, v))
}

// StageIndex applies equality check predicate on the "stage_index" field. It's identical to StageIndexEQ.
func StageIndex(v int) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldStageIndex, v))
}

// ExpectedAgentCount applies equality check predicate on the "expected_agent_count" field. It's identical to ExpectedAgentCountEQ.
func ExpectedAgentCount(v int) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldExpectedAgentCount, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldCompletedAt, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldDurationMs, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldErrorMessage, v))
}

// ChatID applies equality check predicate on the "chat_id" field. It's identical to ChatIDEQ.
func ChatID(v string) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldChatID, v))
}

// ChatUserMessageID applies equality check predicate on the "chat_user_message_id" field. It's identical to ChatUserMessageIDEQ.
func ChatUserMessageID(v string) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldChatUserMessageID, v))
}

// ReferencedStageID applies equality check predicate on the "referenced_stage_id" field. It's identical to ReferencedStageIDEQ.
func ReferencedStageID(v string) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldReferencedStageID, v))
}

// ActionsExecuted applies equality check predicate on the "actions_executed" field. It's identical to ActionsExecutedEQ.
func ActionsExecuted(v bool) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldActionsExecuted, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.Stage {
	return predicate.Stage(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.Stage {
	return predicate.Stage(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.Stage {
	return predicate.Stage(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.Stage {
	return predicate.Stage(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.Stage {
	return predicate.Stage(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.Stage {
	return predicate.Stage(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.Stage {
	return predicate.Stage(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.Stage {
	return predicate.Stage(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.Stage {
	return predicate.Stage(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.Stage {
	return predicate.Stage(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.Stage {
	return predicate.Stage(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.Stage {
	return predicate.Stage(sql.FieldContainsFold(FieldSessionID, v))
}

// StageNameEQ applies the EQ predicate on the "stage_name" field.
func StageNameEQ(v string) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldStageName, v))
}

// StageNameNEQ applies the NEQ predicate on the "stage_name" field.
func StageNameNEQ(v string) predicate.Stage {
	return predicate.Stage(sql.FieldNEQ(FieldStageName, v))
}

// StageNameIn applies the In predicate on the "stage_name" field.
func StageNameIn(vs ...string) predicate.Stage {
	return predicate.Stage(sql.FieldIn(FieldStageName, vs...))
}

// StageNameNotIn applies the NotIn predicate on the "stage_name" field.
func StageNameNotIn(vs ...string) predicate.Stage {
	return predicate.Stage(sql.FieldNotIn(FieldStageName, vs...))
}

// StageNameGT applies the GT predicate on the "stage_name" field.
func StageNameGT(v string) predicate.Stage {
	return predicate.Stage(sql.FieldGT(FieldStageName, v))
}

// StageNameGTE applies the GTE predicate on the "stage_name" field.
func StageNameGTE(v string) predicate.Stage {
	return predicate.Stage(sql.FieldGTE(FieldStageName, v))
}

// StageNameLT applies the LT predicate on the "stage_name" field.
func StageNameLT(v string) predicate.Stage {
	return predicate.Stage(sql.FieldLT(FieldStageName, v))
}

// StageNameLTE applies the LTE predicate on the "stage_name" field.
func StageNameLTE(v string) predicate.Stage {
	return predicate.Stage(sql.FieldLTE(FieldStageName, v))
}

// StageNameContains applies the Contains predicate on the "stage_name" field.
func StageNameContains(v string) predicate.Stage {
	return predicate.Stage(sql.FieldContains(FieldStageName, v))
}

// StageNameHasPrefix applies the HasPrefix predicate on the "stage_name" field.
func StageNameHasPrefix(v string) predicate.Stage {
	return predicate.Stage(sql.FieldHasPrefix(FieldStageName, v))
}

// StageNameHasSuffix applies the HasSuffix predicate on the "stage_name" field.
func StageNameHasSuffix(v string) predicate.Stage {
	return predicate.Stage(sql.FieldHasSuffix(FieldStageName, v))
}

// StageNameEqualFold applies the EqualFold predicate on the "stage_name" field.
func StageNameEqualFold(v string) predicate.Stage {
	return predicate.Stage(sql.FieldEqualFold(FieldStageName, v))
}

// StageNameContainsFold applies the ContainsFold predicate on the "stage_name" field.
func StageNameContainsFold(v string) predicate.Stage {
	return predicate.Stage(sql.FieldContainsFold(FieldStageName, v))
}

// StageIndexEQ applies the EQ predicate on the "stage_index" field.
func StageIndexEQ(v int) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldStageIndex, v))
}

// StageIndexNEQ applies the NEQ predicate on the "stage_index" field.
func StageIndexNEQ(v int) predicate.Stage {
	return predicate.Stage(sql.FieldNEQ(FieldStageIndex, v))
}

// StageIndexIn applies the In predicate on the "stage_index" field.
func StageIndexIn(vs ...int) predicate.Stage {
	return predicate.Stage(sql.FieldIn(FieldStageIndex, vs...))
}

// StageIndexNotIn applies the NotIn predicate on the "stage_index" field.
func StageIndexNotIn(vs ...int) predicate.Stage {
	return predicate.Stage(sql.FieldNotIn(FieldStageIndex, vs...))
}

// StageIndexGT applies the GT predicate on the "stage_index" field.
func StageIndexGT(v int) predicate.Stage {
	return predicate.Stage(sql.FieldGT(FieldStageIndex, v))
}

// StageIndexGTE applies the GTE predicate on the "stage_index" field.
func StageIndexGTE(v int) predicate.Stage {
	return predicate.Stage(sql.FieldGTE(FieldStageIndex, v))
}

// StageIndexLT applies the LT predicate on the "stage_index" field.
func StageIndexLT(v int) predicate.Stage {
	return predicate.Stage(sql.FieldLT(FieldStageIndex, v))
}

// StageIndexLTE applies the LTE predicate on the "stage_index" field.
func StageIndexLTE(v int) predicate.Stage {
	return predicate.Stage(sql.FieldLTE(FieldStageIndex, v))
}

// ExpectedAgentCountEQ applies the EQ predicate on the "expected_agent_count" field.
func ExpectedAgentCountEQ(v int) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldExpectedAgentCount, v))
}

// ExpectedAgentCountNEQ applies the NEQ predicate on the "expected_agent_count" field.
func ExpectedAgentCountNEQ(v int) predicate.Stage {
	return predicate.Stage(sql.FieldNEQ(FieldExpectedAgentCount, v))
}

// ExpectedAgentCountIn applies the In predicate on the "expected_agent_count" field.
func ExpectedAgentCountIn(vs ...int) predicate.Stage {
	return predicate.Stage(sql.FieldIn(FieldExpectedAgentCount, vs...))
}

// ExpectedAgentCountNotIn applies the NotIn predicate on the "expected_agent_count" field.
func ExpectedAgentCountNotIn(vs ...int) predicate.Stage {
	return predicate.Stage(sql.FieldNotIn(FieldExpectedAgentCount, vs...))
}

// ExpectedAgentCountGT applies the GT predicate on the "expected_agent_count" field.
func ExpectedAgentCountGT(v int) predicate.Stage {
	return predicate.Stage(sql.FieldGT(FieldExpectedAgentCount, v))
}

// ExpectedAgentCountGTE applies the GTE predicate on the "expected_agent_count" field.
func ExpectedAgentCountGTE(v int) predicate.Stage {
	return predicate.Stage(sql.FieldGTE(FieldExpectedAgentCount, v))
}

// ExpectedAgentCountLT applies the LT predicate on the "expected_agent_count" field.
func ExpectedAgentCountLT(v int) predicate.Stage {
	return predicate.Stage(sql.FieldLT(FieldExpectedAgentCount, v))
}

// ExpectedAgentCountLTE applies the LTE predicate on the "expected_agent_count" field.
func ExpectedAgentCountLTE(v int) predicate.Stage {
	return predicate.Stage(sql.FieldLTE(FieldExpectedAgentCount, v))
}

// ParallelTypeEQ applies the EQ predicate on the "parallel_type" field.
func ParallelTypeEQ(v ParallelType) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldParallelType, v))
}

// ParallelTypeNEQ applies the NEQ predicate on the "parallel_type" field.
func ParallelTypeNEQ(v ParallelType) predicate.Stage {
	return predicate.Stage(sql.FieldNEQ(FieldParallelType, v))
}

// ParallelTypeIn applies the In predicate on the "parallel_type" field.
func ParallelTypeIn(vs ...ParallelType) predicate.Stage {
	return predicate.Stage(sql.FieldIn(FieldParallelType, vs...))
}

// ParallelTypeNotIn applies the NotIn predicate on the "parallel_type" field.
func ParallelTypeNotIn(vs ...ParallelType) predicate.Stage {
	return predicate.Stage(sql.FieldNotIn(FieldParallelType, vs...))
}

// ParallelTypeIsNil applies the IsNil predicate on the "parallel_type" field.
func ParallelTypeIsNil() predicate.Stage {
	return predicate.Stage(sql.FieldIsNull(FieldParallelType))
}

// ParallelTypeNotNil applies the NotNil predicate on the "parallel_type" field.
func ParallelTypeNotNil() predicate.Stage {
	return predicate.Stage(sql.FieldNotNull(FieldParallelType))
}

// SuccessPolicyEQ applies the EQ predicate on the "success_policy" field.
func SuccessPolicyEQ(v SuccessPolicy) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldSuccessPolicy, v))
}

// SuccessPolicyNEQ applies the NEQ predicate on the "success_policy" field.
func SuccessPolicyNEQ(v SuccessPolicy) predicate.Stage {
	return predicate.Stage(sql.FieldNEQ(FieldSuccessPolicy, v))
}

// SuccessPolicyIn applies the In predicate on the "success_policy" field.
func SuccessPolicyIn(vs ...SuccessPolicy) predicate.Stage {
	return predicate.Stage(sql.FieldIn(FieldSuccessPolicy, vs...))
}

// SuccessPolicyNotIn applies the NotIn predicate on the "success_policy" field.
func SuccessPolicyNotIn(vs ...SuccessPolicy) predicate.Stage {
	return predicate.Stage(sql.FieldNotIn(FieldSuccessPolicy, vs...))
}

// SuccessPolicyIsNil applies the IsNil predicate on the "success_policy" field.
func SuccessPolicyIsNil() predicate.Stage {
	return predicate.Stage(sql.FieldIsNull(FieldSuccessPolicy))
}

// SuccessPolicyNotNil applies the NotNil predicate on the "success_policy" field.
func SuccessPolicyNotNil() predicate.Stage {
	return predicate.Stage(sql.FieldNotNull(FieldSuccessPolicy))
}

// StageTypeEQ applies the EQ predicate on the "stage_type" field.
func StageTypeEQ(v StageType) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldStageType, v))
}

// StageTypeNEQ applies the NEQ predicate on the "stage_type" field.
func StageTypeNEQ(v StageType) predicate.Stage {
	return predicate.Stage(sql.FieldNEQ(FieldStageType, v))
}

// StageTypeIn applies the In predicate on the "stage_type" field.
func StageTypeIn(vs ...StageType) predicate.Stage {
	return predicate.Stage(sql.FieldIn(FieldStageType, vs...))
}

// StageTypeNotIn applies the NotIn predicate on the "stage_type" field.
func StageTypeNotIn(vs ...StageType) predicate.Stage {
	return predicate.Stage(sql.FieldNotIn(FieldStageType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Stage {
	return predicate.Stage(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Stage {
	return predicate.Stage(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Stage {
	return predicate.Stage(sql.FieldNotIn(FieldStatus, vs...))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.Stage {
	return predicate.Stage(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.Stage {
	return predicate.Stage(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.Stage {
	return predicate.Stage(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.Stage {
	return predicate.Stage(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.Stage {
	return predicate.Stage(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.Stage {
	return predicate.Stage(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.Stage {
	return predicate.Stage(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.Stage {
	return predicate.Stage(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.Stage {
	return predicate.Stage(sql.FieldNotNull(FieldStartedAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.Stage {
	return predicate.Stage(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.Stage {
	return predicate.Stage(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.Stage {
	return predicate.Stage(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.Stage {
	return predicate.Stage(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.Stage {
	return predicate.Stage(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.Stage {
	return predicate.Stage(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.Stage {
	return predicate.Stage(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.Stage {
	return predicate.Stage(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.Stage {
	return predicate.Stage(sql.FieldNotNull(FieldCompletedAt))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int) predicate.Stage {
	return predicate.Stage(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int) predicate.Stage {
	return predicate.Stage(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int) predicate.Stage {
	return predicate.Stage(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int) predicate.Stage {
	return predicate.Stage(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int) predicate.Stage {
	return predicate.Stage(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int) predicate.Stage {
	return predicate.Stage(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int) predicate.Stage {
	return predicate.Stage(sql.FieldLTE(FieldDurationMs, v))
}

// DurationMsIsNil applies the IsNil predicate on the "duration_ms" field.
func DurationMsIsNil() predicate.Stage {
	return predicate.Stage(sql.FieldIsNull(FieldDurationMs))
}

// DurationMsNotNil applies the NotNil predicate on the "duration_ms" field.
func DurationMsNotNil() predicate.Stage {
	return predicate.Stage(sql.FieldNotNull(FieldDurationMs))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.Stage {
	return predicate.Stage(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.Stage {
	return predicate.Stage(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.Stage {
	return predicate.Stage(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.Stage {
	return predicate.Stage(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.Stage {
	return predicate.Stage(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.Stage {
	return predicate.Stage(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.Stage {
	return predicate.Stage(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.Stage {
	return predicate.Stage(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.Stage {
	return predicate.Stage(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.Stage {
	return predicate.Stage(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.Stage {
	return predicate.Stage(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.Stage {
	return predicate.Stage(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.Stage {
	return predicate.Stage(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.Stage {
	return predicate.Stage(sql.FieldContainsFold(FieldErrorMessage, v))
}

// ChatIDEQ applies the EQ predicate on the "chat_id" field.
func ChatIDEQ(v string) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldChatID, v))
}

// ChatIDNEQ applies the NEQ predicate on the "chat_id" field.
func ChatIDNEQ(v string) predicate.Stage {
	return predicate.Stage(sql.FieldNEQ(FieldChatID, v))
}

// ChatIDIn applies the In predicate on the "chat_id" field.
func ChatIDIn(vs ...string) predicate.Stage {
	return predicate.Stage(sql.FieldIn(FieldChatID, vs...))
}

// ChatIDNotIn applies the NotIn predicate on the "chat_id" field.
func ChatIDNotIn(vs ...string) predicate.Stage {
	return predicate.Stage(sql.FieldNotIn(FieldChatID, vs...))
}

// ChatIDGT applies the GT predicate on the "chat_id" field.
func ChatIDGT(v string) predicate.Stage {
	return predicate.Stage(sql.FieldGT(FieldChatID, v))
}

// ChatIDGTE applies the GTE predicate on the "chat_id" field.
func ChatIDGTE(v string) predicate.Stage {
	return predicate.Stage(sql.FieldGTE(FieldChatID, v))
}

// ChatIDLT applies the LT predicate on the "chat_id" field.
func ChatIDLT(v string) predicate.Stage {
	return predicate.Stage(sql.FieldLT(FieldChatID, v))
}

// ChatIDLTE applies the LTE predicate on the "chat_id" field.
func ChatIDLTE(v string) predicate.Stage {
	return predicate.Stage(sql.FieldLTE(FieldChatID, v))
}

// ChatIDContains applies the Contains predicate on the "chat_id" field.
func ChatIDContains(v string) predicate.Stage {
	return predicate.Stage(sql.FieldContains(FieldChatID, v))
}

// ChatIDHasPrefix applies the HasPrefix predicate on the "chat_id" field.
func ChatIDHasPrefix(v string) predicate.Stage {
	return predicate.Stage(sql.FieldHasPrefix(FieldChatID, v))
}

// ChatIDHasSuffix applies the HasSuffix predicate on the "chat_id" field.
func ChatIDHasSuffix(v string) predicate.Stage {
	return predicate.Stage(sql.FieldHasSuffix(FieldChatID, v))
}

// ChatIDIsNil applies the IsNil predicate on the "chat_id" field.
func ChatIDIsNil() predicate.Stage {
	return predicate.Stage(sql.FieldIsNull(FieldChatID))
}

// ChatIDNotNil applies the NotNil predicate on the "chat_id" field.
func ChatIDNotNil() predicate.Stage {
	return predicate.Stage(sql.FieldNotNull(FieldChatID))
}

// ChatIDEqualFold applies the EqualFold predicate on the "chat_id" field.
func ChatIDEqualFold(v string) predicate.Stage {
	return predicate.Stage(sql.FieldEqualFold(FieldChatID, v))
}

// ChatIDContainsFold applies the ContainsFold predicate on the "chat_id" field.
func ChatIDContainsFold(v string) predicate.Stage {
	return predicate.Stage(sql.FieldContainsFold(FieldChatID, v))
}

// ChatUserMessageIDEQ applies the EQ predicate on the "chat_user_message_id" field.
func ChatUserMessageIDEQ(v string) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldChatUserMessageID, v))
}

// ChatUserMessageIDNEQ applies the NEQ predicate on the "chat_user_message_id" field.
func ChatUserMessageIDNEQ(v string) predicate.Stage {
	return predicate.Stage(sql.FieldNEQ(FieldChatUserMessageID, v))
}

// ChatUserMessageIDIn applies the In predicate on the "chat_user_message_id" field.
func ChatUserMessageIDIn(vs ...string) predicate.Stage {
	return predicate.Stage(sql.FieldIn(FieldChatUserMessageID, vs...))
}

// ChatUserMessageIDNotIn applies the NotIn predicate on the "chat_user_message_id" field.
func ChatUserMessageIDNotIn(vs ...string) predicate.Stage {
	return predicate.Stage(sql.FieldNotIn(FieldChatUserMessageID, vs...))
}

// ChatUserMessageIDGT applies the GT predicate on the "chat_user_message_id" field.
func ChatUserMessageIDGT(v string) predicate.Stage {
	return predicate.Stage(sql.FieldGT(FieldChatUserMessageID, v))
}

// ChatUserMessageIDGTE applies the GTE predicate on the "chat_user_message_id" field.
func ChatUserMessageIDGTE(v string) predicate.Stage {
	return predicate.Stage(sql.FieldGTE(FieldChatUserMessageID, v))
}

// ChatUserMessageIDLT applies the LT predicate on the "chat_user_message_id" field.
func ChatUserMessageIDLT(v string) predicate.Stage {
	return predicate.Stage(sql.FieldLT(FieldChatUserMessageID, v))
}

// ChatUserMessageIDLTE applies the LTE predicate on the "chat_user_message_id" field.
func ChatUserMessageIDLTE(v string) predicate.Stage {
	return predicate.Stage(sql.FieldLTE(FieldChatUserMessageID, v))
}

// ChatUserMessageIDContains applies the Contains predicate on the "chat_user_message_id" field.
func ChatUserMessageIDContains(v string) predicate.Stage {
	return predicate.Stage(sql.FieldContains(FieldChatUserMessageID, v))
}

// ChatUserMessageIDHasPrefix applies the HasPrefix predicate on the "chat_user_message_id" field.
func ChatUserMessageIDHasPrefix(v string) predicate.Stage {
	return predicate.Stage(sql.FieldHasPrefix(FieldChatUserMessageID, v))
}

// ChatUserMessageIDHasSuffix applies the HasSuffix predicate on the "chat_user_message_id" field.
func ChatUserMessageIDHasSuffix(v string) predicate.Stage {
	return predicate.Stage(sql.FieldHasSuffix(FieldChatUserMessageID, v))
}

// ChatUserMessageIDIsNil applies the IsNil predicate on the "chat_user_message_id" field.
func ChatUserMessageIDIsNil() predicate.Stage {
	return predicate.Stage(sql.FieldIsNull(FieldChatUserMessageID))
}

// ChatUserMessageIDNotNil applies the NotNil predicate on the "chat_user_message_id" field.
func ChatUserMessageIDNotNil() predicate.Stage {
	return predicate.Stage(sql.FieldNotNull(FieldChatUserMessageID))
}

// ChatUserMessageIDEqualFold applies the EqualFold predicate on the "chat_user_message_id" field.
func ChatUserMessageIDEqualFold(v string) predicate.Stage {
	return predicate.Stage(sql.FieldEqualFold(FieldChatUserMessageID, v))
}

// ChatUserMessageIDContainsFold applies the ContainsFold predicate on the "chat_user_message_id" field.
func ChatUserMessageIDContainsFold(v string) predicate.Stage {
	return predicate.Stage(sql.FieldContainsFold(FieldChatUserMessageID, v))
}

// ReferencedStageIDEQ applies the EQ predicate on the "referenced_stage_id" field.
func ReferencedStageIDEQ(v string) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldReferencedStageID, v))
}

// ReferencedStageIDNEQ applies the NEQ predicate on the "referenced_stage_id" field.
func ReferencedStageIDNEQ(v string) predicate.Stage {
	return predicate.Stage(sql.FieldNEQ(FieldReferencedStageID, v))
}

// ReferencedStageIDIn applies the In predicate on the "referenced_stage_id" field.
func ReferencedStageIDIn(vs ...string) predicate.Stage {
	return predicate.Stage(sql.FieldIn(FieldReferencedStageID, vs...))
}

// ReferencedStageIDNotIn applies the NotIn predicate on the "referenced_stage_id" field.
func ReferencedStageIDNotIn(vs ...string) predicate.Stage {
	return predicate.Stage(sql.FieldNotIn(FieldReferencedStageID, vs...))
}

// ReferencedStageIDGT applies the GT predicate on the "referenced_stage_id" field.
func ReferencedStageIDGT(v string) predicate.Stage {
	return predicate.Stage(sql.FieldGT(FieldReferencedStageID, v))
}

// ReferencedStageIDGTE applies the GTE predicate on the "referenced_stage_id" field.
func ReferencedStageIDGTE(v string) predicate.Stage {
	return predicate.Stage(sql.FieldGTE(FieldReferencedStageID, v))
}

// ReferencedStageIDLT applies the LT predicate on the "referenced_stage_id" field.
func ReferencedStageIDLT(v string) predicate.Stage {
	return predicate.Stage(sql.FieldLT(FieldReferencedStageID, v))
}

// ReferencedStageIDLTE applies the LTE predicate on the "referenced_stage_id" field.
func ReferencedStageIDLTE(v string) predicate.Stage {
	return predicate.Stage(sql.FieldLTE(FieldReferencedStageID, v))
}

// ReferencedStageIDContains applies the Contains predicate on the "referenced_stage_id" field.
func ReferencedStageIDContains(v string) predicate.Stage {
	return predicate.Stage(sql.FieldContains(FieldReferencedStageID, v))
}

// ReferencedStageIDHasPrefix applies the HasPrefix predicate on the "referenced_stage_id" field.
func ReferencedStageIDHasPrefix(v string) predicate.Stage {
	return predicate.Stage(sql.FieldHasPrefix(FieldReferencedStageID, v))
}

// ReferencedStageIDHasSuffix applies the HasSuffix predicate on the "referenced_stage_id" field.
func ReferencedStageIDHasSuffix(v string) predicate.Stage {
	return predicate.Stage(sql.FieldHasSuffix(FieldReferencedStageID, v))
}

// ReferencedStageIDIsNil applies the IsNil predicate on the "referenced_stage_id" field.
func ReferencedStageIDIsNil() predicate.Stage {
	return predicate.Stage(sql.FieldIsNull(FieldReferencedStageID))
}

// ReferencedStageIDNotNil applies the NotNil predicate on the "referenced_stage_id" field.
func ReferencedStageIDNotNil() predicate.Stage {
	return predicate.Stage(sql.FieldNotNull(FieldReferencedStageID))
}

// ReferencedStageIDEqualFold applies the EqualFold predicate on the "referenced_stage_id" field.
func ReferencedStageIDEqualFold(v string) predicate.Stage {
	return predicate.Stage(sql.FieldEqualFold(FieldReferencedStageID, v))
}

// ReferencedStageIDContainsFold applies the ContainsFold predicate on the "referenced_stage_id" field.
func ReferencedStageIDContainsFold(v string) predicate.Stage {
	return predicate.Stage(sql.FieldContainsFold(FieldReferencedStageID, v))
}

// ActionsExecutedEQ applies the EQ predicate on the "actions_executed" field.
func ActionsExecutedEQ(v bool) predicate.Stage {
	return predicate.Stage(sql.FieldEQ(FieldActionsExecuted, v))
}

// ActionsExecutedNEQ applies the NEQ predicate on the "actions_executed" field.
func ActionsExecutedNEQ(v bool) predicate.Stage {
	return predicate.Stage(sql.FieldNEQ(FieldActionsExecuted, v))
}

// ActionsExecutedIsNil applies the IsNil predicate on the "actions_executed" field.
func ActionsExecutedIsNil() predicate.Stage {
	return predicate.Stage(sql.FieldIsNull(FieldActionsExecuted))
}

// ActionsExecutedNotNil applies the NotNil predicate on the "actions_executed" field.
func ActionsExecutedNotNil() predicate.Stage {
	return predicate.Stage(sql.FieldNotNull(FieldActionsExecuted))
}

// HasSession applies the HasEdge predicate on the "session" edge.
func HasSession() predicate.Stage {
	return predicate.Stage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionWith applies the HasEdge predicate on the "session" edge with a given conditions (other predicates).
func HasSessionWith(preds ...predicate.AlertSession) predicate.Stage {
	return predicate.Stage(func(s *sql.Selector) {
		step := newSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAgentExecutions applies the HasEdge predicate on the "agent_executions" edge.
func HasAgentExecutions() predicate.Stage {
	return predicate.Stage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AgentExecutionsTable, AgentExecutionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentExecutionsWith applies the HasEdge predicate on the "agent_executions" edge with a given conditions (other predicates).
func HasAgentExecutionsWith(preds ...predicate.AgentExecution) predicate.Stage {
	return predicate.Stage(func(s *sql.Selector) {
		step := newAgentExecutionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTimelineEvents applies the HasEdge predicate on the "timeline_events" edge.
func HasTimelineEvents() predicate.Stage {
	return predicate.Stage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TimelineEventsTable, TimelineEventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTimelineEventsWith applies the HasEdge predicate on the "timeline_events" edge with a given conditions (other predicates).
func HasTimelineEventsWith(preds ...predicate.TimelineEvent) predicate.Stage {
	return predicate.Stage(func(s *sql.Selector) {
		step := newTimelineEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMessages applies the HasEdge predicate on the "messages" edge.
func HasMessages() predicate.Stage {
	return predicate.Stage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessagesWith applies the HasEdge predicate on the "messages" edge with a given conditions (other predicates).
func HasMessagesWith(preds ...predicate.Message) predicate.Stage {
	return predicate.Stage(func(s *sql.Selector) {
		step := newMessagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLlmInteractions applies the HasEdge predicate on the "llm_interactions" edge.
func HasLlmInteractions() predicate.Stage {
	return predicate.Stage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LlmInteractionsTable, LlmInteractionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLlmInteractionsWith applies the HasEdge predicate on the "llm_interactions" edge with a given conditions (other predicates).
func HasLlmInteractionsWith(preds ...predicate.LLMInteraction) predicate.Stage {
	return predicate.Stage(func(s *sql.Selector) {
		step := newLlmInteractionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMcpInteractions applies the HasEdge predicate on the "mcp_interactions" edge.
func HasMcpInteractions() predicate.Stage {
	return predicate.Stage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, McpInteractionsTable, McpInteractionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMcpInteractionsWith applies the HasEdge predicate on the "mcp_interactions" edge with a given conditions (other predicates).
func HasMcpInteractionsWith(preds ...predicate.MCPInteraction) predicate.Stage {
	return predicate.Stage(func(s *sql.Selector) {
		step := newMcpInteractionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChat applies the HasEdge predicate on the "chat" edge.
func HasChat() predicate.Stage {
	return predicate.Stage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChatTable, ChatColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChatWith applies the HasEdge predicate on the "chat" edge with a given conditions (other predicates).
func HasChatWith(preds ...predicate.Chat) predicate.Stage {
	return predicate.Stage(func(s *sql.Selector) {
		step := newChatStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChatUserMessage applies the HasEdge predicate on the "chat_user_message" edge.
func HasChatUserMessage() predicate.Stage {
	return predicate.Stage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, ChatUserMessageTable, ChatUserMessageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChatUserMessageWith applies the HasEdge predicate on the "chat_user_message" edge with a given conditions (other predicates).
func HasChatUserMessageWith(preds ...predicate.ChatUserMessage) predicate.Stage {
	return predicate.Stage(func(s *sql.Selector) {
		step := newChatUserMessageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSessionScores applies the HasEdge predicate on the "session_scores" edge.
func HasSessionScores() predicate.Stage {
	return predicate.Stage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SessionScoresTable, SessionScoresColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionScoresWith applies the HasEdge predicate on the "session_scores" edge with a given conditions (other predicates).
func HasSessionScoresWith(preds ...predicate.SessionScore) predicate.Stage {
	return predicate.Stage(func(s *sql.Selector) {
		step := newSessionScoresStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReferencingStages applies the HasEdge predicate on the "referencing_stages" edge.
func HasReferencingStages() predicate.Stage {
	return predicate.Stage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ReferencingStagesTable, ReferencingStagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReferencingStagesWith applies the HasEdge predicate on the "referencing_stages" edge with a given conditions (other predicates).
func HasReferencingStagesWith(preds ...predicate.Stage) predicate.Stage {
	return predicate.Stage(func(s *sql.Selector) {
		step := newReferencingStagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReferencedStage applies the HasEdge predicate on the "referenced_stage" edge.
func HasReferencedStage() predicate.Stage {
	return predicate.Stage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ReferencedStageTable, ReferencedStageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReferencedStageWith applies the HasEdge predicate on the "referenced_stage" edge with a given conditions (other predicates).
func HasReferencedStageWith(preds ...predicate.Stage) predicate.Stage {
	return predicate.Stage(func(s *sql.Selector) {
		step := newReferencedStageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Stage) predicate.Stage {
	return predicate.Stage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Stage) predicate.Stage {
	return predicate.Stage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Stage) predicate.Stage {
	return predicate.Stage(sql.NotPredicates(p))
}
