// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/codeready-toolchain/tarsy/ent/agentexecution"
	"github.com/codeready-toolchain/tarsy/ent/alertsession"
	"github.com/codeready-toolchain/tarsy/ent/chat"
	"github.com/codeready-toolchain/tarsy/ent/event"
	"github.com/codeready-toolchain/tarsy/ent/llminteraction"
	"github.com/codeready-toolchain/tarsy/ent/mcpinteraction"
	"github.com/codeready-toolchain/tarsy/ent/message"
	"github.com/codeready-toolchain/tarsy/ent/sessionreviewactivity"
	"github.com/codeready-toolchain/tarsy/ent/sessionscore"
	"github.com/codeready-toolchain/tarsy/ent/stage"
	"github.com/codeready-toolchain/tarsy/ent/timelineevent"
)

// AlertSessionCreate is the builder for creating a AlertSession entity.
type AlertSessionCreate struct {
	config
	mutation *AlertSessionMutation
	hooks    []Hook
}

// SetAlertData sets the "alert_data" field.
func (_c *AlertSessionCreate) SetAlertData(v string) *AlertSessionCreate {
	_c.mutation.SetAlertData(v)
	return _c
}

// SetAgentType sets the "agent_type" field.
func (_c *AlertSessionCreate) SetAgentType(v string) *AlertSessionCreate {
	_c.mutation.SetAgentType(v)
	return _c
}

// SetAlertType sets the "alert_type" field.
func (_c *AlertSessionCreate) SetAlertType(v string) *AlertSessionCreate {
	_c.mutation.SetAlertType(v)
	return _c
}

// SetNillableAlertType sets the "alert_type" field if the given value is not nil.
func (_c *AlertSessionCreate) SetNillableAlertType(v *string) *AlertSessionCreate {
	if v != nil {
		_c.SetAlertType(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AlertSessionCreate) SetStatus(v alertsession.Status) *AlertSessionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AlertSessionCreate) SetNillableStatus(v *alertsession.Status) *AlertSessionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AlertSessionCreate) SetCreatedAt(v time.Time) *AlertSessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AlertSessionCreate) SetNillableCreatedAt(v *time.Time) *AlertSessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *AlertSessionCreate) SetStartedAt(v time.Time) *AlertSessionCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *AlertSessionCreate) SetNillableStartedAt(v *time.Time) *AlertSessionCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *AlertSessionCreate) SetCompletedAt(v time.Time) *AlertSessionCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *AlertSessionCreate) SetNillableCompletedAt(v *time.Time) *AlertSessionCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *AlertSessionCreate) SetErrorMessage(v string) *AlertSessionCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *AlertSessionCreate) SetNillableErrorMessage(v *string) *AlertSessionCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetFinalAnalysis sets the "final_analysis" field.
func (_c *AlertSessionCreate) SetFinalAnalysis(v string) *AlertSessionCreate {
	_c.mutation.SetFinalAnalysis(v)
	return _c
}

// SetNillableFinalAnalysis sets the "final_analysis" field if the given value is not nil.
func (_c *AlertSessionCreate) SetNillableFinalAnalysis(v *string) *AlertSessionCreate {
	if v != nil {
		_c.SetFinalAnalysis(*v)
	}
	return _c
}

// SetExecutiveSummary sets the "executive_summary" field.
func (_c *AlertSessionCreate) SetExecutiveSummary(v string) *AlertSessionCreate {
	_c.mutation.SetExecutiveSummary(v)
	return _c
}

// SetNillableExecutiveSummary sets the "executive_summary" field if the given value is not nil.
func (_c *AlertSessionCreate) SetNillableExecutiveSummary(v *string) *AlertSessionCreate {
	if v != nil {
		_c.SetExecutiveSummary(*v)
	}
	return _c
}

// SetExecutiveSummaryError sets the "executive_summary_error" field.
func (_c *AlertSessionCreate) SetExecutiveSummaryError(v string) *AlertSessionCreate {
	_c.mutation.SetExecutiveSummaryError(v)
	return _c
}

// SetNillableExecutiveSummaryError sets the "executive_summary_error" field if the given value is not nil.
func (_c *AlertSessionCreate) SetNillableExecutiveSummaryError(v *string) *AlertSessionCreate {
	if v != nil {
		_c.SetExecutiveSummaryError(*v)
	}
	return _c
}

// SetSessionMetadata sets the "session_metadata" field.
func (_c *AlertSessionCreate) SetSessionMetadata(v map[string]interface{}) *AlertSessionCreate {
	_c.mutation.SetSessionMetadata(v)
	return _c
}

// SetAuthor sets the "author" field.
func (_c *AlertSessionCreate) SetAuthor(v string) *AlertSessionCreate {
	_c.mutation.SetAuthor(v)
	return _c
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_c *AlertSessionCreate) SetNillableAuthor(v *string) *AlertSessionCreate {
	if v != nil {
		_c.SetAuthor(*v)
	}
	return _c
}

// SetRunbookURL sets the "runbook_url" field.
func (_c *AlertSessionCreate) SetRunbookURL(v string) *AlertSessionCreate {
	_c.mutation.SetRunbookURL(v)
	return _c
}

// SetNillableRunbookURL sets the "runbook_url" field if the given value is not nil.
func (_c *AlertSessionCreate) SetNillableRunbookURL(v *string) *AlertSessionCreate {
	if v != nil {
		_c.SetRunbookURL(*v)
	}
	return _c
}

// SetMcpSelection sets the "mcp_selection" field.
func (_c *AlertSessionCreate) SetMcpSelection(v map[string]interface{}) *AlertSessionCreate {
	_c.mutation.SetMcpSelection(v)
	return _c
}

// SetChainID sets the "chain_id" field.
func (_c *AlertSessionCreate) SetChainID(v string) *AlertSessionCreate {
	_c.mutation.SetChainID(v)
	return _c
}

// SetCurrentStageIndex sets the "current_stage_index" field.
func (_c *AlertSessionCreate) SetCurrentStageIndex(v int) *AlertSessionCreate {
	_c.mutation.SetCurrentStageIndex(v)
	return _c
}

// SetNillableCurrentStageIndex sets the "current_stage_index" field if the given value is not nil.
func (_c *AlertSessionCreate) SetNillableCurrentStageIndex(v *int) *AlertSessionCreate {
	if v != nil {
		_c.SetCurrentStageIndex(*v)
	}
	return _c
}

// SetCurrentStageID sets the "current_stage_id" field.
func (_c *AlertSessionCreate) SetCurrentStageID(v string) *AlertSessionCreate {
	_c.mutation.SetCurrentStageID(v)
	return _c
}

// SetNillableCurrentStageID sets the "current_stage_id" field if the given value is not nil.
func (_c *AlertSessionCreate) SetNillableCurrentStageID(v *string) *AlertSessionCreate {
	if v != nil {
		_c.SetCurrentStageID(*v)
	}
	return _c
}

// SetPodID sets the "pod_id" field.
func (_c *AlertSessionCreate) SetPodID(v string) *AlertSessionCreate {
	_c.mutation.SetPodID(v)
	return _c
}

// SetNillablePodID sets the "pod_id" field if the given value is not nil.
func (_c *AlertSessionCreate) SetNillablePodID(v *string) *AlertSessionCreate {
	if v != nil {
		_c.SetPodID(*v)
	}
	return _c
}

// SetLastInteractionAt sets the "last_interaction_at" field.
func (_c *AlertSessionCreate) SetLastInteractionAt(v time.Time) *AlertSessionCreate {
	_c.mutation.SetLastInteractionAt(v)
	return _c
}

// SetNillableLastInteractionAt sets the "last_interaction_at" field if the given value is not nil.
func (_c *AlertSessionCreate) SetNillableLastInteractionAt(v *time.Time) *AlertSessionCreate {
	if v != nil {
		_c.SetLastInteractionAt(*v)
	}
	return _c
}

// SetSlackMessageFingerprint sets the "slack_message_fingerprint" field.
func (_c *AlertSessionCreate) SetSlackMessageFingerprint(v string) *AlertSessionCreate {
	_c.mutation.SetSlackMessageFingerprint(v)
	return _c
}

// SetNillableSlackMessageFingerprint sets the "slack_message_fingerprint" field if the given value is not nil.
func (_c *AlertSessionCreate) SetNillableSlackMessageFingerprint(v *string) *AlertSessionCreate {
	if v != nil {
		_c.SetSlackMessageFingerprint(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *AlertSessionCreate) SetDeletedAt(v time.Time) *AlertSessionCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *AlertSessionCreate) SetNillableDeletedAt(v *time.Time) *AlertSessionCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetReviewStatus sets the "review_status" field.
func (_c *AlertSessionCreate) SetReviewStatus(v alertsession.ReviewStatus) *AlertSessionCreate {
	_c.mutation.SetReviewStatus(v)
	return _c
}

// SetNillableReviewStatus sets the "review_status" field if the given value is not nil.
func (_c *AlertSessionCreate) SetNillableReviewStatus(v *alertsession.ReviewStatus) *AlertSessionCreate {
	if v != nil {
		_c.SetReviewStatus(*v)
	}
	return _c
}

// SetAssignee sets the "assignee" field.
func (_c *AlertSessionCreate) SetAssignee(v string) *AlertSessionCreate {
	_c.mutation.SetAssignee(v)
	return _c
}

// SetNillableAssignee sets the "assignee" field if the given value is not nil.
func (_c *AlertSessionCreate) SetNillableAssignee(v *string) *AlertSessionCreate {
	if v != nil {
		_c.SetAssignee(*v)
	}
	return _c
}

// SetAssignedAt sets the "assigned_at" field.
func (_c *AlertSessionCreate) SetAssignedAt(v time.Time) *AlertSessionCreate {
	_c.mutation.SetAssignedAt(v)
	return _c
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_c *AlertSessionCreate) SetNillableAssignedAt(v *time.Time) *AlertSessionCreate {
	if v != nil {
		_c.SetAssignedAt(*v)
	}
	return _c
}

// SetResolvedAt sets the "resolved_at" field.
func (_c *AlertSessionCreate) SetResolvedAt(v time.Time) *AlertSessionCreate {
	_c.mutation.SetResolvedAt(v)
	return _c
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_c *AlertSessionCreate) SetNillableResolvedAt(v *time.Time) *AlertSessionCreate {
	if v != nil {
		_c.SetResolvedAt(*v)
	}
	return _c
}

// SetResolutionReason sets the "resolution_reason" field.
func (_c *AlertSessionCreate) SetResolutionReason(v alertsession.ResolutionReason) *AlertSessionCreate {
	_c.mutation.SetResolutionReason(v)
	return _c
}

// SetNillableResolutionReason sets the "resolution_reason" field if the given value is not nil.
func (_c *AlertSessionCreate) SetNillableResolutionReason(v *alertsession.ResolutionReason) *AlertSessionCreate {
	if v != nil {
		_c.SetResolutionReason(*v)
	}
	return _c
}

// SetResolutionNote sets the "resolution_note" field.
func (_c *AlertSessionCreate) SetResolutionNote(v string) *AlertSessionCreate {
	_c.mutation.SetResolutionNote(v)
	return _c
}

// SetNillableResolutionNote sets the "resolution_note" field if the given value is not nil.
func (_c *AlertSessionCreate) SetNillableResolutionNote(v *string) *AlertSessionCreate {
	if v != nil {
		_c.SetResolutionNote(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AlertSessionCreate) SetID(v string) *AlertSessionCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddStageIDs adds the "stages" edge to the Stage entity by IDs.
func (_c *AlertSessionCreate) AddStageIDs(ids ...string) *AlertSessionCreate {
	_c.mutation.AddStageIDs(ids...)
	return _c
}

// AddStages adds the "stages" edges to the Stage entity.
func (_c *AlertSessionCreate) AddStages(v ...*Stage) *AlertSessionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddStageIDs(ids...)
}

// AddAgentExecutionIDs adds the "agent_executions" edge to the AgentExecution entity by IDs.
func (_c *AlertSessionCreate) AddAgentExecutionIDs(ids ...string) *AlertSessionCreate {
	_c.mutation.AddAgentExecutionIDs(ids...)
	return _c
}

// AddAgentExecutions adds the "agent_executions" edges to the AgentExecution entity.
func (_c *AlertSessionCreate) AddAgentExecutions(v ...*AgentExecution) *AlertSessionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAgentExecutionIDs(ids...)
}

// AddTimelineEventIDs adds the "timeline_events" edge to the TimelineEvent entity by IDs.
func (_c *AlertSessionCreate) AddTimelineEventIDs(ids ...string) *AlertSessionCreate {
	_c.mutation.AddTimelineEventIDs(ids...)
	return _c
}

// AddTimelineEvents adds the "timeline_events" edges to the TimelineEvent entity.
func (_c *AlertSessionCreate) AddTimelineEvents(v ...*TimelineEvent) *AlertSessionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTimelineEventIDs(ids...)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (_c *AlertSessionCreate) AddMessageIDs(ids ...string) *AlertSessionCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the Message entity.
func (_c *AlertSessionCreate) AddMessages(v ...*Message) *AlertSessionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// AddLlmInteractionIDs adds the "llm_interactions" edge to the LLMInteraction entity by IDs.
func (_c *AlertSessionCreate) AddLlmInteractionIDs(ids ...string) *AlertSessionCreate {
	_c.mutation.AddLlmInteractionIDs(ids...)
	return _c
}

// AddLlmInteractions adds the "llm_interactions" edges to the LLMInteraction entity.
func (_c *AlertSessionCreate) AddLlmInteractions(v ...*LLMInteraction) *AlertSessionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLlmInteractionIDs(ids...)
}

// AddMcpInteractionIDs adds the "mcp_interactions" edge to the MCPInteraction entity by IDs.
func (_c *AlertSessionCreate) AddMcpInteractionIDs(ids ...string) *AlertSessionCreate {
	_c.mutation.AddMcpInteractionIDs(ids...)
	return _c
}

// AddMcpInteractions adds the "mcp_interactions" edges to the MCPInteraction entity.
func (_c *AlertSessionCreate) AddMcpInteractions(v ...*MCPInteraction) *AlertSessionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMcpInteractionIDs(ids...)
}

// AddEventIDs adds the "events" edge to the Event entity by IDs.
func (_c *AlertSessionCreate) AddEventIDs(ids ...int) *AlertSessionCreate {
	_c.mutation.AddEventIDs(ids...)
	return _c
}

// AddEvents adds the "events" edges to the Event entity.
func (_c *AlertSessionCreate) AddEvents(v ...*Event) *AlertSessionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEventIDs(ids...)
}

// SetChatID sets the "chat" edge to the Chat entity by ID.
func (_c *AlertSessionCreate) SetChatID(id string) *AlertSessionCreate {
	_c.mutation.SetChatID(id)
	return _c
}

// SetNillableChatID sets the "chat" edge to the Chat entity by ID if the given value is not nil.
func (_c *AlertSessionCreate) SetNillableChatID(id *string) *AlertSessionCreate {
	if id != nil {
		_c = _c.SetChatID(*id)
	}
	return _c
}

// SetChat sets the "chat" edge to the Chat entity.
func (_c *AlertSessionCreate) SetChat(v *Chat) *AlertSessionCreate {
	return _c.SetChatID(v.ID)
}

// AddSessionScoreIDs adds the "session_scores" edge to the SessionScore entity by IDs.
func (_c *AlertSessionCreate) AddSessionScoreIDs(ids ...string) *AlertSessionCreate {
	_c.mutation.AddSessionScoreIDs(ids...)
	return _c
}

// AddSessionScores adds the "session_scores" edges to the SessionScore entity.
func (_c *AlertSessionCreate) AddSessionScores(v ...*SessionScore) *AlertSessionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSessionScoreIDs(ids...)
}

// AddReviewActivityIDs adds the "review_activities" edge to the SessionReviewActivity entity by IDs.
func (_c *AlertSessionCreate) AddReviewActivityIDs(ids ...string) *AlertSessionCreate {
	_c.mutation.AddReviewActivityIDs(ids...)
	return _c
}

// AddReviewActivities adds the "review_activities" edges to the SessionReviewActivity entity.
func (_c *AlertSessionCreate) AddReviewActivities(v ...*SessionReviewActivity) *AlertSessionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddReviewActivityIDs(ids...)
}

// Mutation returns the AlertSessionMutation object of the builder.
func (_c *AlertSessionCreate) Mutation() *AlertSessionMutation {
	return _c.mutation
}

// Save creates the AlertSession in the database.
func (_c *AlertSessionCreate) Save(ctx context.Context) (*AlertSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AlertSessionCreate) SaveX(ctx context.Context) *AlertSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AlertSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AlertSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AlertSessionCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := alertsession.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := alertsession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AlertSessionCreate) check() error {
	if _, ok := _c.mutation.AlertData(); !ok {
		return &ValidationError{Name: "alert_data", err: errors.New(`ent: missing required field "AlertSession.alert_data"`)}
	}
	if _, ok := _c.mutation.AgentType(); !ok {
		return &ValidationError{Name: "agent_type", err: errors.New(`ent: missing required field "AlertSession.agent_type"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AlertSession.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := alertsession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AlertSession.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AlertSession.created_at"`)}
	}
	if _, ok := _c.mutation.ChainID(); !ok {
		return &ValidationError{Name: "chain_id", err: errors.New(`ent: missing required field "AlertSession.chain_id"`)}
	}
	if v, ok := _c.mutation.ReviewStatus(); ok {
		if err := alertsession.ReviewStatusValidator(v); err != nil {
			return &ValidationError{Name: "review_status", err: fmt.Errorf(`ent: validator failed for field "AlertSession.review_status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ResolutionReason(); ok {
		if err := alertsession.ResolutionReasonValidator(v); err != nil {
			return &ValidationError{Name: "resolution_reason", err: fmt.Errorf(`ent: validator failed for field "AlertSession.resolution_reason": %w`, err)}
		}
	}
	return nil
}

func (_c *AlertSessionCreate) sqlSave(ctx context.Context) (*AlertSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AlertSession.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AlertSessionCreate) createSpec() (*AlertSession, *sqlgraph.CreateSpec) {
	var (
		_node = &AlertSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(alertsession.Table, sqlgraph.NewFieldSpec(alertsession.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.AlertData(); ok {
		_spec.SetField(alertsession.FieldAlertData, field.TypeString, value)
		_node.AlertData = value
	}
	if value, ok := _c.mutation.AgentType(); ok {
		_spec.SetField(alertsession.FieldAgentType, field.TypeString, value)
		_node.AgentType = value
	}
	if value, ok := _c.mutation.AlertType(); ok {
		_spec.SetField(alertsession.FieldAlertType, field.TypeString, value)
		_node.AlertType = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(alertsession.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(alertsession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(alertsession.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(alertsession.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(alertsession.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.FinalAnalysis(); ok {
		_spec.SetField(alertsession.FieldFinalAnalysis, field.TypeString, value)
		_node.FinalAnalysis = &value
	}
	if value, ok := _c.mutation.ExecutiveSummary(); ok {
		_spec.SetField(alertsession.FieldExecutiveSummary, field.TypeString, value)
		_node.ExecutiveSummary = &value
	}
	if value, ok := _c.mutation.ExecutiveSummaryError(); ok {
		_spec.SetField(alertsession.FieldExecutiveSummaryError, field.TypeString, value)
		_node.ExecutiveSummaryError = &value
	}
	if value, ok := _c.mutation.SessionMetadata(); ok {
		_spec.SetField(alertsession.FieldSessionMetadata, field.TypeJSON, value)
		_node.SessionMetadata = value
	}
	if value, ok := _c.mutation.Author(); ok {
		_spec.SetField(alertsession.FieldAuthor, field.TypeString, value)
		_node.Author = &value
	}
	if value, ok := _c.mutation.RunbookURL(); ok {
		_spec.SetField(alertsession.FieldRunbookURL, field.TypeString, value)
		_node.RunbookURL = &value
	}
	if value, ok := _c.mutation.McpSelection(); ok {
		_spec.SetField(alertsession.FieldMcpSelection, field.TypeJSON, value)
		_node.McpSelection = value
	}
	if value, ok := _c.mutation.ChainID(); ok {
		_spec.SetField(alertsession.FieldChainID, field.TypeString, value)
		_node.ChainID = value
	}
	if value, ok := _c.mutation.CurrentStageIndex(); ok {
		_spec.SetField(alertsession.FieldCurrentStageIndex, field.TypeInt, value)
		_node.CurrentStageIndex = &value
	}
	if value, ok := _c.mutation.CurrentStageID(); ok {
		_spec.SetField(alertsession.FieldCurrentStageID, field.TypeString, value)
		_node.CurrentStageID = &value
	}
	if value, ok := _c.mutation.PodID(); ok {
		_spec.SetField(alertsession.FieldPodID, field.TypeString, value)
		_node.PodID = &value
	}
	if value, ok := _c.mutation.LastInteractionAt(); ok {
		_spec.SetField(alertsession.FieldLastInteractionAt, field.TypeTime, value)
		_node.LastInteractionAt = &value
	}
	if value, ok := _c.mutation.SlackMessageFingerprint(); ok {
		_spec.SetField(alertsession.FieldSlackMessageFingerprint, field.TypeString, value)
		_node.SlackMessageFingerprint = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(alertsession.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.ReviewStatus(); ok {
		_spec.SetField(alertsession.FieldReviewStatus, field.TypeEnum, value)
		_node.ReviewStatus = &value
	}
	if value, ok := _c.mutation.Assignee(); ok {
		_spec.SetField(alertsession.FieldAssignee, field.TypeString, value)
		_node.Assignee = &value
	}
	if value, ok := _c.mutation.AssignedAt(); ok {
		_spec.SetField(alertsession.FieldAssignedAt, field.TypeTime, value)
		_node.AssignedAt = &value
	}
	if value, ok := _c.mutation.ResolvedAt(); ok {
		_spec.SetField(alertsession.FieldResolvedAt, field.TypeTime, value)
		_node.ResolvedAt = &value
	}
	if value, ok := _c.mutation.ResolutionReason(); ok {
		_spec.SetField(alertsession.FieldResolutionReason, field.TypeEnum, value)
		_node.ResolutionReason = &value
	}
	if value, ok := _c.mutation.ResolutionNote(); ok {
		_spec.SetField(alertsession.FieldResolutionNote, field.TypeString, value)
		_node.ResolutionNote = &value
	}
	if nodes := _c.mutation.StagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alertsession.StagesTable,
			Columns: []string{alertsession.StagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AgentExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alertsession.AgentExecutionsTable,
			Columns: []string{alertsession.AgentExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentexecution.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TimelineEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alertsession.TimelineEventsTable,
			Columns: []string{alertsession.TimelineEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timelineevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alertsession.MessagesTable,
			Columns: []string{alertsession.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LlmInteractionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alertsession.LlmInteractionsTable,
			Columns: []string{alertsession.LlmInteractionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(llminteraction.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.McpInteractionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alertsession.McpInteractionsTable,
			Columns: []string{alertsession.McpInteractionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpinteraction.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alertsession.EventsTable,
			Columns: []string{alertsession.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   alertsession.ChatTable,
			Columns: []string{alertsession.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SessionScoresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alertsession.SessionScoresTable,
			Columns: []string{alertsession.SessionScoresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionscore.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ReviewActivitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alertsession.ReviewActivitiesTable,
			Columns: []string{alertsession.ReviewActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionreviewactivity.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AlertSessionCreateBulk is the builder for creating many AlertSession entities in bulk.
type AlertSessionCreateBulk struct {
	config
	err      error
	builders []*AlertSessionCreate
}

// Save creates the AlertSession entities in the database.
func (_c *AlertSessionCreateBulk) Save(ctx context.Context) ([]*AlertSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AlertSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AlertSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AlertSessionCreateBulk) SaveX(ctx context.Context) []*AlertSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AlertSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AlertSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
