// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/codeready-toolchain/tarsy/ent/agentexecution"
	"github.com/codeready-toolchain/tarsy/ent/alertsession"
	"github.com/codeready-toolchain/tarsy/ent/chat"
	"github.com/codeready-toolchain/tarsy/ent/event"
	"github.com/codeready-toolchain/tarsy/ent/llminteraction"
	"github.com/codeready-toolchain/tarsy/ent/mcpinteraction"
	"github.com/codeready-toolchain/tarsy/ent/message"
	"github.com/codeready-toolchain/tarsy/ent/predicate"
	"github.com/codeready-toolchain/tarsy/ent/sessionreviewactivity"
	"github.com/codeready-toolchain/tarsy/ent/sessionscore"
	"github.com/codeready-toolchain/tarsy/ent/stage"
	"github.com/codeready-toolchain/tarsy/ent/timelineevent"
)

// AlertSessionQuery is the builder for querying AlertSession entities.
type AlertSessionQuery struct {
	config
	ctx                  *QueryContext
	order                []alertsession.OrderOption
	inters               []Interceptor
	predicates           []predicate.AlertSession
	withStages           *StageQuery
	withAgentExecutions  *AgentExecutionQuery
	withTimelineEvents   *TimelineEventQuery
	withMessages         *MessageQuery
	withLlmInteractions  *LLMInteractionQuery
	withMcpInteractions  *MCPInteractionQuery
	withEvents           *EventQuery
	withChat             *ChatQuery
	withSessionScores    *SessionScoreQuery
	withReviewActivities *SessionReviewActivityQuery
	modifiers            []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AlertSessionQuery builder.
func (_q *AlertSessionQuery) Where(ps ...predicate.AlertSession) *AlertSessionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AlertSessionQuery) Limit(limit int) *AlertSessionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AlertSessionQuery) Offset(offset int) *AlertSessionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AlertSessionQuery) Unique(unique bool) *AlertSessionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AlertSessionQuery) Order(o ...alertsession.OrderOption) *AlertSessionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryStages chains the current query on the "stages" edge.
func (_q *AlertSessionQuery) QueryStages() *StageQuery {
	query := (&StageClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(alertsession.Table, alertsession.FieldID, selector),
			sqlgraph.To(stage.Table, stage.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, alertsession.StagesTable, alertsession.StagesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAgentExecutions chains the current query on the "agent_executions" edge.
func (_q *AlertSessionQuery) QueryAgentExecutions() *AgentExecutionQuery {
	query := (&AgentExecutionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(alertsession.Table, alertsession.FieldID, selector),
			sqlgraph.To(agentexecution.Table, agentexecution.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, alertsession.AgentExecutionsTable, alertsession.AgentExecutionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTimelineEvents chains the current query on the "timeline_events" edge.
func (_q *AlertSessionQuery) QueryTimelineEvents() *TimelineEventQuery {
	query := (&TimelineEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(alertsession.Table, alertsession.FieldID, selector),
			sqlgraph.To(timelineevent.Table, timelineevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, alertsession.TimelineEventsTable, alertsession.TimelineEventsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMessages chains the current query on the "messages" edge.
func (_q *AlertSessionQuery) QueryMessages() *MessageQuery {
	query := (&MessageClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(alertsession.Table, alertsession.FieldID, selector),
			sqlgraph.To(message.Table, message.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, alertsession.MessagesTable, alertsession.MessagesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLlmInteractions chains the current query on the "llm_interactions" edge.
func (_q *AlertSessionQuery) QueryLlmInteractions() *LLMInteractionQuery {
	query := (&LLMInteractionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(alertsession.Table, alertsession.FieldID, selector),
			sqlgraph.To(llminteraction.Table, llminteraction.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, alertsession.LlmInteractionsTable, alertsession.LlmInteractionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMcpInteractions chains the current query on the "mcp_interactions" edge.
func (_q *AlertSessionQuery) QueryMcpInteractions() *MCPInteractionQuery {
	query := (&MCPInteractionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(alertsession.Table, alertsession.FieldID, selector),
			sqlgraph.To(mcpinteraction.Table, mcpinteraction.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, alertsession.McpInteractionsTable, alertsession.McpInteractionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEvents chains the current query on the "events" edge.
func (_q *AlertSessionQuery) QueryEvents() *EventQuery {
	query := (&EventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(alertsession.Table, alertsession.FieldID, selector),
			sqlgraph.To(event.Table, event.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, alertsession.EventsTable, alertsession.EventsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChat chains the current query on the "chat" edge.
func (_q *AlertSessionQuery) QueryChat() *ChatQuery {
	query := (&ChatClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(alertsession.Table, alertsession.FieldID, selector),
			sqlgraph.To(chat.Table, chat.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, alertsession.ChatTable, alertsession.ChatColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySessionScores chains the current query on the "session_scores" edge.
func (_q *AlertSessionQuery) QuerySessionScores() *SessionScoreQuery {
	query := (&SessionScoreClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(alertsession.Table, alertsession.FieldID, selector),
			sqlgraph.To(sessionscore.Table, sessionscore.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, alertsession.SessionScoresTable, alertsession.SessionScoresColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryReviewActivities chains the current query on the "review_activities" edge.
func (_q *AlertSessionQuery) QueryReviewActivities() *SessionReviewActivityQuery {
	query := (&SessionReviewActivityClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(alertsession.Table, alertsession.FieldID, selector),
			sqlgraph.To(sessionreviewactivity.Table, sessionreviewactivity.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, alertsession.ReviewActivitiesTable, alertsession.ReviewActivitiesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AlertSession entity from the query.
// Returns a *NotFoundError when no AlertSession was found.
func (_q *AlertSessionQuery) First(ctx context.Context) (*AlertSession, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{alertsession.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AlertSessionQuery) FirstX(ctx context.Context) *AlertSession {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AlertSession ID from the query.
// Returns a *NotFoundError when no AlertSession ID was found.
func (_q *AlertSessionQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{alertsession.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AlertSessionQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AlertSession entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AlertSession entity is found.
// Returns a *NotFoundError when no AlertSession entities are found.
func (_q *AlertSessionQuery) Only(ctx context.Context) (*AlertSession, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{alertsession.Label}
	default:
		return nil, &NotSingularError{alertsession.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AlertSessionQuery) OnlyX(ctx context.Context) *AlertSession {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AlertSession ID in the query.
// Returns a *NotSingularError when more than one AlertSession ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AlertSessionQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{alertsession.Label}
	default:
		err = &NotSingularError{alertsession.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AlertSessionQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AlertSessions.
func (_q *AlertSessionQuery) All(ctx context.Context) ([]*AlertSession, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AlertSession, *AlertSessionQuery]()
	return withInterceptors[[]*AlertSession](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AlertSessionQuery) AllX(ctx context.Context) []*AlertSession {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AlertSession IDs.
func (_q *AlertSessionQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(alertsession.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AlertSessionQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AlertSessionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AlertSessionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AlertSessionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AlertSessionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AlertSessionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AlertSessionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AlertSessionQuery) Clone() *AlertSessionQuery {
	if _q == nil {
		return nil
	}
	return &AlertSessionQuery{
		config:               _q.config,
		ctx:                  _q.ctx.Clone(),
		order:                append([]alertsession.OrderOption{}, _q.order...),
		inters:               append([]Interceptor{}, _q.inters...),
		predicates:           append([]predicate.AlertSession{}, _q.predicates...),
		withStages:           _q.withStages.Clone(),
		withAgentExecutions:  _q.withAgentExecutions.Clone(),
		withTimelineEvents:   _q.withTimelineEvents.Clone(),
		withMessages:         _q.withMessages.Clone(),
		withLlmInteractions:  _q.withLlmInteractions.Clone(),
		withMcpInteractions:  _q.withMcpInteractions.Clone(),
		withEvents:           _q.withEvents.Clone(),
		withChat:             _q.withChat.Clone(),
		withSessionScores:    _q.withSessionScores.Clone(),
		withReviewActivities: _q.withReviewActivities.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithStages tells the query-builder to eager-load the nodes that are connected to
// the "stages" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AlertSessionQuery) WithStages(opts ...func(*StageQuery)) *AlertSessionQuery {
	query := (&StageClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withStages = query
	return _q
}

// WithAgentExecutions tells the query-builder to eager-load the nodes that are connected to
// the "agent_executions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AlertSessionQuery) WithAgentExecutions(opts ...func(*AgentExecutionQuery)) *AlertSessionQuery {
	query := (&AgentExecutionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAgentExecutions = query
	return _q
}

// WithTimelineEvents tells the query-builder to eager-load the nodes that are connected to
// the "timeline_events" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AlertSessionQuery) WithTimelineEvents(opts ...func(*TimelineEventQuery)) *AlertSessionQuery {
	query := (&TimelineEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTimelineEvents = query
	return _q
}

// WithMessages tells the query-builder to eager-load the nodes that are connected to
// the "messages" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AlertSessionQuery) WithMessages(opts ...func(*MessageQuery)) *AlertSessionQuery {
	query := (&MessageClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMessages = query
	return _q
}

// WithLlmInteractions tells the query-builder to eager-load the nodes that are connected to
// the "llm_interactions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AlertSessionQuery) WithLlmInteractions(opts ...func(*LLMInteractionQuery)) *AlertSessionQuery {
	query := (&LLMInteractionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLlmInteractions = query
	return _q
}

// WithMcpInteractions tells the query-builder to eager-load the nodes that are connected to
// the "mcp_interactions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AlertSessionQuery) WithMcpInteractions(opts ...func(*MCPInteractionQuery)) *AlertSessionQuery {
	query := (&MCPInteractionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMcpInteractions = query
	return _q
}

// WithEvents tells the query-builder to eager-load the nodes that are connected to
// the "events" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AlertSessionQuery) WithEvents(opts ...func(*EventQuery)) *AlertSessionQuery {
	query := (&EventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEvents = query
	return _q
}

// WithChat tells the query-builder to eager-load the nodes that are connected to
// the "chat" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AlertSessionQuery) WithChat(opts ...func(*ChatQuery)) *AlertSessionQuery {
	query := (&ChatClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChat = query
	return _q
}

// WithSessionScores tells the query-builder to eager-load the nodes that are connected to
// the "session_scores" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AlertSessionQuery) WithSessionScores(opts ...func(*SessionScoreQuery)) *AlertSessionQuery {
	query := (&SessionScoreClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSessionScores = query
	return _q
}

// WithReviewActivities tells the query-builder to eager-load the nodes that are connected to
// the "review_activities" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AlertSessionQuery) WithReviewActivities(opts ...func(*SessionReviewActivityQuery)) *AlertSessionQuery {
	query := (&SessionReviewActivityClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withReviewActivities = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AlertData string `json:"alert_data,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AlertSession.Query().
//		GroupBy(alertsession.FieldAlertData).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AlertSessionQuery) GroupBy(field string, fields ...string) *AlertSessionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AlertSessionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = alertsession.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AlertData string `json:"alert_data,omitempty"`
//	}
//
//	client.AlertSession.Query().
//		Select(alertsession.FieldAlertData).
//		Scan(ctx, &v)
func (_q *AlertSessionQuery) Select(fields ...string) *AlertSessionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AlertSessionSelect{AlertSessionQuery: _q}
	sbuild.label = alertsession.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AlertSessionSelect configured with the given aggregations.
func (_q *AlertSessionQuery) Aggregate(fns ...AggregateFunc) *AlertSessionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AlertSessionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !alertsession.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AlertSessionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AlertSession, error) {
	var (
		nodes       = []*AlertSession{}
		_spec       = _q.querySpec()
		loadedTypes = [10]bool{
			_q.withStages != nil,
			_q.withAgentExecutions != nil,
			_q.withTimelineEvents != nil,
			_q.withMessages != nil,
			_q.withLlmInteractions != nil,
			_q.withMcpInteractions != nil,
			_q.withEvents != nil,
			_q.withChat != nil,
			_q.withSessionScores != nil,
			_q.withReviewActivities != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AlertSession).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AlertSession{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withStages; query != nil {
		if err := _q.loadStages(ctx, query, nodes,
			func(n *AlertSession) { n.Edges.Stages = []*Stage{} },
			func(n *AlertSession, e *Stage) { n.Edges.Stages = append(n.Edges.Stages, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAgentExecutions; query != nil {
		if err := _q.loadAgentExecutions(ctx, query, nodes,
			func(n *AlertSession) { n.Edges.AgentExecutions = []*AgentExecution{} },
			func(n *AlertSession, e *AgentExecution) { n.Edges.AgentExecutions = append(n.Edges.AgentExecutions, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTimelineEvents; query != nil {
		if err := _q.loadTimelineEvents(ctx, query, nodes,
			func(n *AlertSession) { n.Edges.TimelineEvents = []*TimelineEvent{} },
			func(n *AlertSession, e *TimelineEvent) { n.Edges.TimelineEvents = append(n.Edges.TimelineEvents, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMessages; query != nil {
		if err := _q.loadMessages(ctx, query, nodes,
			func(n *AlertSession) { n.Edges.Messages = []*Message{} },
			func(n *AlertSession, e *Message) { n.Edges.Messages = append(n.Edges.Messages, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withLlmInteractions; query != nil {
		if err := _q.loadLlmInteractions(ctx, query, nodes,
			func(n *AlertSession) { n.Edges.LlmInteractions = []*LLMInteraction{} },
			func(n *AlertSession, e *LLMInteraction) { n.Edges.LlmInteractions = append(n.Edges.LlmInteractions, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMcpInteractions; query != nil {
		if err := _q.loadMcpInteractions(ctx, query, nodes,
			func(n *AlertSession) { n.Edges.McpInteractions = []*MCPInteraction{} },
			func(n *AlertSession, e *MCPInteraction) { n.Edges.McpInteractions = append(n.Edges.McpInteractions, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withEvents; query != nil {
		if err := _q.loadEvents(ctx, query, nodes,
			func(n *AlertSession) { n.Edges.Events = []*Event{} },
			func(n *AlertSession, e *Event) { n.Edges.Events = append(n.Edges.Events, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withChat; query != nil {
		if err := _q.loadChat(ctx, query, nodes, nil,
			func(n *AlertSession, e *Chat) { n.Edges.Chat = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSessionScores; query != nil {
		if err := _q.loadSessionScores(ctx, query, nodes,
			func(n *AlertSession) { n.Edges.SessionScores = []*SessionScore{} },
			func(n *AlertSession, e *SessionScore) { n.Edges.SessionScores = append(n.Edges.SessionScores, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withReviewActivities; query != nil {
		if err := _q.loadReviewActivities(ctx, query, nodes,
			func(n *AlertSession) { n.Edges.ReviewActivities = []*SessionReviewActivity{} },
			func(n *AlertSession, e *SessionReviewActivity) {
				n.Edges.ReviewActivities = append(n.Edges.ReviewActivities, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AlertSessionQuery) loadStages(ctx context.Context, query *StageQuery, nodes []*AlertSession, init func(*AlertSession), assign func(*AlertSession, *Stage)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*AlertSession)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(stage.FieldSessionID)
	}
	query.Where(predicate.Stage(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(alertsession.StagesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SessionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "session_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *AlertSessionQuery) loadAgentExecutions(ctx context.Context, query *AgentExecutionQuery, nodes []*AlertSession, init func(*AlertSession), assign func(*AlertSession, *AgentExecution)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*AlertSession)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(agentexecution.FieldSessionID)
	}
	query.Where(predicate.AgentExecution(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(alertsession.AgentExecutionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SessionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "session_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *AlertSessionQuery) loadTimelineEvents(ctx context.Context, query *TimelineEventQuery, nodes []*AlertSession, init func(*AlertSession), assign func(*AlertSession, *TimelineEvent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*AlertSession)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(timelineevent.FieldSessionID)
	}
	query.Where(predicate.TimelineEvent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(alertsession.TimelineEventsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SessionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "session_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *AlertSessionQuery) loadMessages(ctx context.Context, query *MessageQuery, nodes []*AlertSession, init func(*AlertSession), assign func(*AlertSession, *Message)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*AlertSession)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(message.FieldSessionID)
	}
	query.Where(predicate.Message(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(alertsession.MessagesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SessionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "session_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *AlertSessionQuery) loadLlmInteractions(ctx context.Context, query *LLMInteractionQuery, nodes []*AlertSession, init func(*AlertSession), assign func(*AlertSession, *LLMInteraction)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*AlertSession)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(llminteraction.FieldSessionID)
	}
	query.Where(predicate.LLMInteraction(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(alertsession.LlmInteractionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SessionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "session_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *AlertSessionQuery) loadMcpInteractions(ctx context.Context, query *MCPInteractionQuery, nodes []*AlertSession, init func(*AlertSession), assign func(*AlertSession, *MCPInteraction)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*AlertSession)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(mcpinteraction.FieldSessionID)
	}
	query.Where(predicate.MCPInteraction(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(alertsession.McpInteractionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SessionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "session_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *AlertSessionQuery) loadEvents(ctx context.Context, query *EventQuery, nodes []*AlertSession, init func(*AlertSession), assign func(*AlertSession, *Event)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*AlertSession)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(event.FieldSessionID)
	}
	query.Where(predicate.Event(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(alertsession.EventsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SessionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "session_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *AlertSessionQuery) loadChat(ctx context.Context, query *ChatQuery, nodes []*AlertSession, init func(*AlertSession), assign func(*AlertSession, *Chat)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*AlertSession)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(chat.FieldSessionID)
	}
	query.Where(predicate.Chat(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(alertsession.ChatColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SessionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "session_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *AlertSessionQuery) loadSessionScores(ctx context.Context, query *SessionScoreQuery, nodes []*AlertSession, init func(*AlertSession), assign func(*AlertSession, *SessionScore)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*AlertSession)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(sessionscore.FieldSessionID)
	}
	query.Where(predicate.SessionScore(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(alertsession.SessionScoresColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SessionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "session_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *AlertSessionQuery) loadReviewActivities(ctx context.Context, query *SessionReviewActivityQuery, nodes []*AlertSession, init func(*AlertSession), assign func(*AlertSession, *SessionReviewActivity)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*AlertSession)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(sessionreviewactivity.FieldSessionID)
	}
	query.Where(predicate.SessionReviewActivity(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(alertsession.ReviewActivitiesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SessionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "session_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *AlertSessionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AlertSessionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(alertsession.Table, alertsession.Columns, sqlgraph.NewFieldSpec(alertsession.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, alertsession.FieldID)
		for i := range fields {
			if fields[i] != alertsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AlertSessionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(alertsession.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = alertsession.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *AlertSessionQuery) ForUpdate(opts ...sql.LockOption) *AlertSessionQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *AlertSessionQuery) ForShare(opts ...sql.LockOption) *AlertSessionQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *AlertSessionQuery) Modify(modifiers ...func(s *sql.Selector)) *AlertSessionSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// AlertSessionGroupBy is the group-by builder for AlertSession entities.
type AlertSessionGroupBy struct {
	selector
	build *AlertSessionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AlertSessionGroupBy) Aggregate(fns ...AggregateFunc) *AlertSessionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AlertSessionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AlertSessionQuery, *AlertSessionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AlertSessionGroupBy) sqlScan(ctx context.Context, root *AlertSessionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AlertSessionSelect is the builder for selecting fields of AlertSession entities.
type AlertSessionSelect struct {
	*AlertSessionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AlertSessionSelect) Aggregate(fns ...AggregateFunc) *AlertSessionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AlertSessionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AlertSessionQuery, *AlertSessionSelect](ctx, _s.AlertSessionQuery, _s, _s.inters, v)
}

func (_s *AlertSessionSelect) sqlScan(ctx context.Context, root *AlertSessionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *AlertSessionSelect) Modify(modifiers ...func(s *sql.Selector)) *AlertSessionSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
