// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/codeready-toolchain/tarsy/ent/alertsession"
	"github.com/codeready-toolchain/tarsy/ent/investigationmemory"
)

// InvestigationMemoryCreate is the builder for creating a InvestigationMemory entity.
type InvestigationMemoryCreate struct {
	config
	mutation *InvestigationMemoryMutation
	hooks    []Hook
}

// SetProject sets the "project" field.
func (_c *InvestigationMemoryCreate) SetProject(v string) *InvestigationMemoryCreate {
	_c.mutation.SetProject(v)
	return _c
}

// SetNillableProject sets the "project" field if the given value is not nil.
func (_c *InvestigationMemoryCreate) SetNillableProject(v *string) *InvestigationMemoryCreate {
	if v != nil {
		_c.SetProject(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *InvestigationMemoryCreate) SetContent(v string) *InvestigationMemoryCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *InvestigationMemoryCreate) SetCategory(v investigationmemory.Category) *InvestigationMemoryCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetValence sets the "valence" field.
func (_c *InvestigationMemoryCreate) SetValence(v investigationmemory.Valence) *InvestigationMemoryCreate {
	_c.mutation.SetValence(v)
	return _c
}

// SetConfidence sets the "confidence" field.
func (_c *InvestigationMemoryCreate) SetConfidence(v float64) *InvestigationMemoryCreate {
	_c.mutation.SetConfidence(v)
	return _c
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_c *InvestigationMemoryCreate) SetNillableConfidence(v *float64) *InvestigationMemoryCreate {
	if v != nil {
		_c.SetConfidence(*v)
	}
	return _c
}

// SetSeenCount sets the "seen_count" field.
func (_c *InvestigationMemoryCreate) SetSeenCount(v int) *InvestigationMemoryCreate {
	_c.mutation.SetSeenCount(v)
	return _c
}

// SetNillableSeenCount sets the "seen_count" field if the given value is not nil.
func (_c *InvestigationMemoryCreate) SetNillableSeenCount(v *int) *InvestigationMemoryCreate {
	if v != nil {
		_c.SetSeenCount(*v)
	}
	return _c
}

// SetSourceSessionID sets the "source_session_id" field.
func (_c *InvestigationMemoryCreate) SetSourceSessionID(v string) *InvestigationMemoryCreate {
	_c.mutation.SetSourceSessionID(v)
	return _c
}

// SetAlertType sets the "alert_type" field.
func (_c *InvestigationMemoryCreate) SetAlertType(v string) *InvestigationMemoryCreate {
	_c.mutation.SetAlertType(v)
	return _c
}

// SetNillableAlertType sets the "alert_type" field if the given value is not nil.
func (_c *InvestigationMemoryCreate) SetNillableAlertType(v *string) *InvestigationMemoryCreate {
	if v != nil {
		_c.SetAlertType(*v)
	}
	return _c
}

// SetChainID sets the "chain_id" field.
func (_c *InvestigationMemoryCreate) SetChainID(v string) *InvestigationMemoryCreate {
	_c.mutation.SetChainID(v)
	return _c
}

// SetNillableChainID sets the "chain_id" field if the given value is not nil.
func (_c *InvestigationMemoryCreate) SetNillableChainID(v *string) *InvestigationMemoryCreate {
	if v != nil {
		_c.SetChainID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvestigationMemoryCreate) SetCreatedAt(v time.Time) *InvestigationMemoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvestigationMemoryCreate) SetNillableCreatedAt(v *time.Time) *InvestigationMemoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InvestigationMemoryCreate) SetUpdatedAt(v time.Time) *InvestigationMemoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InvestigationMemoryCreate) SetNillableUpdatedAt(v *time.Time) *InvestigationMemoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *InvestigationMemoryCreate) SetLastSeenAt(v time.Time) *InvestigationMemoryCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_c *InvestigationMemoryCreate) SetNillableLastSeenAt(v *time.Time) *InvestigationMemoryCreate {
	if v != nil {
		_c.SetLastSeenAt(*v)
	}
	return _c
}

// SetDeprecated sets the "deprecated" field.
func (_c *InvestigationMemoryCreate) SetDeprecated(v bool) *InvestigationMemoryCreate {
	_c.mutation.SetDeprecated(v)
	return _c
}

// SetNillableDeprecated sets the "deprecated" field if the given value is not nil.
func (_c *InvestigationMemoryCreate) SetNillableDeprecated(v *bool) *InvestigationMemoryCreate {
	if v != nil {
		_c.SetDeprecated(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *InvestigationMemoryCreate) SetID(v string) *InvestigationMemoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSourceSession sets the "source_session" edge to the AlertSession entity.
func (_c *InvestigationMemoryCreate) SetSourceSession(v *AlertSession) *InvestigationMemoryCreate {
	return _c.SetSourceSessionID(v.ID)
}

// AddInjectedIntoSessionIDs adds the "injected_into_sessions" edge to the AlertSession entity by IDs.
func (_c *InvestigationMemoryCreate) AddInjectedIntoSessionIDs(ids ...string) *InvestigationMemoryCreate {
	_c.mutation.AddInjectedIntoSessionIDs(ids...)
	return _c
}

// AddInjectedIntoSessions adds the "injected_into_sessions" edges to the AlertSession entity.
func (_c *InvestigationMemoryCreate) AddInjectedIntoSessions(v ...*AlertSession) *InvestigationMemoryCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddInjectedIntoSessionIDs(ids...)
}

// Mutation returns the InvestigationMemoryMutation object of the builder.
func (_c *InvestigationMemoryCreate) Mutation() *InvestigationMemoryMutation {
	return _c.mutation
}

// Save creates the InvestigationMemory in the database.
func (_c *InvestigationMemoryCreate) Save(ctx context.Context) (*InvestigationMemory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvestigationMemoryCreate) SaveX(ctx context.Context) *InvestigationMemory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvestigationMemoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvestigationMemoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvestigationMemoryCreate) defaults() {
	if _, ok := _c.mutation.Project(); !ok {
		v := investigationmemory.DefaultProject
		_c.mutation.SetProject(v)
	}
	if _, ok := _c.mutation.Confidence(); !ok {
		v := investigationmemory.DefaultConfidence
		_c.mutation.SetConfidence(v)
	}
	if _, ok := _c.mutation.SeenCount(); !ok {
		v := investigationmemory.DefaultSeenCount
		_c.mutation.SetSeenCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := investigationmemory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := investigationmemory.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		v := investigationmemory.DefaultLastSeenAt()
		_c.mutation.SetLastSeenAt(v)
	}
	if _, ok := _c.mutation.Deprecated(); !ok {
		v := investigationmemory.DefaultDeprecated
		_c.mutation.SetDeprecated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvestigationMemoryCreate) check() error {
	if _, ok := _c.mutation.Project(); !ok {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required field "InvestigationMemory.project"`)}
	}
	if v, ok := _c.mutation.Project(); ok {
		if err := investigationmemory.ProjectValidator(v); err != nil {
			return &ValidationError{Name: "project", err: fmt.Errorf(`ent: validator failed for field "InvestigationMemory.project": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "InvestigationMemory.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := investigationmemory.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "InvestigationMemory.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "InvestigationMemory.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := investigationmemory.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "InvestigationMemory.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Valence(); !ok {
		return &ValidationError{Name: "valence", err: errors.New(`ent: missing required field "InvestigationMemory.valence"`)}
	}
	if v, ok := _c.mutation.Valence(); ok {
		if err := investigationmemory.ValenceValidator(v); err != nil {
			return &ValidationError{Name: "valence", err: fmt.Errorf(`ent: validator failed for field "InvestigationMemory.valence": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Confidence(); !ok {
		return &ValidationError{Name: "confidence", err: errors.New(`ent: missing required field "InvestigationMemory.confidence"`)}
	}
	if v, ok := _c.mutation.Confidence(); ok {
		if err := investigationmemory.ConfidenceValidator(v); err != nil {
			return &ValidationError{Name: "confidence", err: fmt.Errorf(`ent: validator failed for field "InvestigationMemory.confidence": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SeenCount(); !ok {
		return &ValidationError{Name: "seen_count", err: errors.New(`ent: missing required field "InvestigationMemory.seen_count"`)}
	}
	if v, ok := _c.mutation.SeenCount(); ok {
		if err := investigationmemory.SeenCountValidator(v); err != nil {
			return &ValidationError{Name: "seen_count", err: fmt.Errorf(`ent: validator failed for field "InvestigationMemory.seen_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceSessionID(); !ok {
		return &ValidationError{Name: "source_session_id", err: errors.New(`ent: missing required field "InvestigationMemory.source_session_id"`)}
	}
	if v, ok := _c.mutation.SourceSessionID(); ok {
		if err := investigationmemory.SourceSessionIDValidator(v); err != nil {
			return &ValidationError{Name: "source_session_id", err: fmt.Errorf(`ent: validator failed for field "InvestigationMemory.source_session_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InvestigationMemory.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InvestigationMemory.updated_at"`)}
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		return &ValidationError{Name: "last_seen_at", err: errors.New(`ent: missing required field "InvestigationMemory.last_seen_at"`)}
	}
	if _, ok := _c.mutation.Deprecated(); !ok {
		return &ValidationError{Name: "deprecated", err: errors.New(`ent: missing required field "InvestigationMemory.deprecated"`)}
	}
	if len(_c.mutation.SourceSessionIDs()) == 0 {
		return &ValidationError{Name: "source_session", err: errors.New(`ent: missing required edge "InvestigationMemory.source_session"`)}
	}
	return nil
}

func (_c *InvestigationMemoryCreate) sqlSave(ctx context.Context) (*InvestigationMemory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected InvestigationMemory.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvestigationMemoryCreate) createSpec() (*InvestigationMemory, *sqlgraph.CreateSpec) {
	var (
		_node = &InvestigationMemory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(investigationmemory.Table, sqlgraph.NewFieldSpec(investigationmemory.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Project(); ok {
		_spec.SetField(investigationmemory.FieldProject, field.TypeString, value)
		_node.Project = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(investigationmemory.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(investigationmemory.FieldCategory, field.TypeEnum, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Valence(); ok {
		_spec.SetField(investigationmemory.FieldValence, field.TypeEnum, value)
		_node.Valence = value
	}
	if value, ok := _c.mutation.Confidence(); ok {
		_spec.SetField(investigationmemory.FieldConfidence, field.TypeFloat64, value)
		_node.Confidence = value
	}
	if value, ok := _c.mutation.SeenCount(); ok {
		_spec.SetField(investigationmemory.FieldSeenCount, field.TypeInt, value)
		_node.SeenCount = value
	}
	if value, ok := _c.mutation.AlertType(); ok {
		_spec.SetField(investigationmemory.FieldAlertType, field.TypeString, value)
		_node.AlertType = &value
	}
	if value, ok := _c.mutation.ChainID(); ok {
		_spec.SetField(investigationmemory.FieldChainID, field.TypeString, value)
		_node.ChainID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(investigationmemory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(investigationmemory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(investigationmemory.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = value
	}
	if value, ok := _c.mutation.Deprecated(); ok {
		_spec.SetField(investigationmemory.FieldDeprecated, field.TypeBool, value)
		_node.Deprecated = value
	}
	if nodes := _c.mutation.SourceSessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   investigationmemory.SourceSessionTable,
			Columns: []string{investigationmemory.SourceSessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertsession.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SourceSessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InjectedIntoSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   investigationmemory.InjectedIntoSessionsTable,
			Columns: investigationmemory.InjectedIntoSessionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertsession.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InvestigationMemoryCreateBulk is the builder for creating many InvestigationMemory entities in bulk.
type InvestigationMemoryCreateBulk struct {
	config
	err      error
	builders []*InvestigationMemoryCreate
}

// Save creates the InvestigationMemory entities in the database.
func (_c *InvestigationMemoryCreateBulk) Save(ctx context.Context) ([]*InvestigationMemory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvestigationMemory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvestigationMemoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvestigationMemoryCreateBulk) SaveX(ctx context.Context) []*InvestigationMemory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvestigationMemoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvestigationMemoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
