// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/codeready-toolchain/tarsy/ent/investigationmemory"
	"github.com/codeready-toolchain/tarsy/ent/predicate"
)

// InvestigationMemoryDelete is the builder for deleting a InvestigationMemory entity.
type InvestigationMemoryDelete struct {
	config
	hooks    []Hook
	mutation *InvestigationMemoryMutation
}

// Where appends a list predicates to the InvestigationMemoryDelete builder.
func (_d *InvestigationMemoryDelete) Where(ps ...predicate.InvestigationMemory) *InvestigationMemoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *InvestigationMemoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InvestigationMemoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *InvestigationMemoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(investigationmemory.Table, sqlgraph.NewFieldSpec(investigationmemory.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// InvestigationMemoryDeleteOne is the builder for deleting a single InvestigationMemory entity.
type InvestigationMemoryDeleteOne struct {
	_d *InvestigationMemoryDelete
}

// Where appends a list predicates to the InvestigationMemoryDelete builder.
func (_d *InvestigationMemoryDeleteOne) Where(ps ...predicate.InvestigationMemory) *InvestigationMemoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *InvestigationMemoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{investigationmemory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InvestigationMemoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
