// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/codeready-toolchain/tarsy/ent/alertsession"
	"github.com/codeready-toolchain/tarsy/ent/chat"
	"github.com/codeready-toolchain/tarsy/ent/chatusermessage"
	"github.com/codeready-toolchain/tarsy/ent/event"
	"github.com/codeready-toolchain/tarsy/ent/investigationmemory"
	"github.com/codeready-toolchain/tarsy/ent/llminteraction"
	"github.com/codeready-toolchain/tarsy/ent/mcpinteraction"
	"github.com/codeready-toolchain/tarsy/ent/message"
	"github.com/codeready-toolchain/tarsy/ent/schema"
	"github.com/codeready-toolchain/tarsy/ent/sessionreviewactivity"
	"github.com/codeready-toolchain/tarsy/ent/sessionscore"
	"github.com/codeready-toolchain/tarsy/ent/timelineevent"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	agentexecutionFields := schema.AgentExecution{}.Fields()
	_ = agentexecutionFields
	alertsessionFields := schema.AlertSession{}.Fields()
	_ = alertsessionFields
	// alertsessionDescCreatedAt is the schema descriptor for created_at field.
	alertsessionDescCreatedAt := alertsessionFields[5].Descriptor()
	// alertsession.DefaultCreatedAt holds the default value on creation for the created_at field.
	alertsession.DefaultCreatedAt = alertsessionDescCreatedAt.Default.(func() time.Time)
	chatFields := schema.Chat{}.Fields()
	_ = chatFields
	// chatDescCreatedAt is the schema descriptor for created_at field.
	chatDescCreatedAt := chatFields[2].Descriptor()
	// chat.DefaultCreatedAt holds the default value on creation for the created_at field.
	chat.DefaultCreatedAt = chatDescCreatedAt.Default.(func() time.Time)
	chatusermessageFields := schema.ChatUserMessage{}.Fields()
	_ = chatusermessageFields
	// chatusermessageDescCreatedAt is the schema descriptor for created_at field.
	chatusermessageDescCreatedAt := chatusermessageFields[4].Descriptor()
	// chatusermessage.DefaultCreatedAt holds the default value on creation for the created_at field.
	chatusermessage.DefaultCreatedAt = chatusermessageDescCreatedAt.Default.(func() time.Time)
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescCreatedAt is the schema descriptor for created_at field.
	eventDescCreatedAt := eventFields[3].Descriptor()
	// event.DefaultCreatedAt holds the default value on creation for the created_at field.
	event.DefaultCreatedAt = eventDescCreatedAt.Default.(func() time.Time)
	investigationmemoryFields := schema.InvestigationMemory{}.Fields()
	_ = investigationmemoryFields
	// investigationmemoryDescProject is the schema descriptor for project field.
	investigationmemoryDescProject := investigationmemoryFields[1].Descriptor()
	// investigationmemory.DefaultProject holds the default value on creation for the project field.
	investigationmemory.DefaultProject = investigationmemoryDescProject.Default.(string)
	// investigationmemory.ProjectValidator is a validator for the "project" field. It is called by the builders before save.
	investigationmemory.ProjectValidator = investigationmemoryDescProject.Validators[0].(func(string) error)
	// investigationmemoryDescContent is the schema descriptor for content field.
	investigationmemoryDescContent := investigationmemoryFields[2].Descriptor()
	// investigationmemory.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	investigationmemory.ContentValidator = investigationmemoryDescContent.Validators[0].(func(string) error)
	// investigationmemoryDescConfidence is the schema descriptor for confidence field.
	investigationmemoryDescConfidence := investigationmemoryFields[5].Descriptor()
	// investigationmemory.DefaultConfidence holds the default value on creation for the confidence field.
	investigationmemory.DefaultConfidence = investigationmemoryDescConfidence.Default.(float64)
	// investigationmemory.ConfidenceValidator is a validator for the "confidence" field. It is called by the builders before save.
	investigationmemory.ConfidenceValidator = func() func(float64) error {
		validators := investigationmemoryDescConfidence.Validators
		fns := [...]func(float64) error{
			validators[0].(func(float64) error),
			validators[1].(func(float64) error),
		}
		return func(confidence float64) error {
			for _, fn := range fns {
				if err := fn(confidence); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// investigationmemoryDescSeenCount is the schema descriptor for seen_count field.
	investigationmemoryDescSeenCount := investigationmemoryFields[6].Descriptor()
	// investigationmemory.DefaultSeenCount holds the default value on creation for the seen_count field.
	investigationmemory.DefaultSeenCount = investigationmemoryDescSeenCount.Default.(int)
	// investigationmemory.SeenCountValidator is a validator for the "seen_count" field. It is called by the builders before save.
	investigationmemory.SeenCountValidator = investigationmemoryDescSeenCount.Validators[0].(func(int) error)
	// investigationmemoryDescSourceSessionID is the schema descriptor for source_session_id field.
	investigationmemoryDescSourceSessionID := investigationmemoryFields[7].Descriptor()
	// investigationmemory.SourceSessionIDValidator is a validator for the "source_session_id" field. It is called by the builders before save.
	investigationmemory.SourceSessionIDValidator = investigationmemoryDescSourceSessionID.Validators[0].(func(string) error)
	// investigationmemoryDescCreatedAt is the schema descriptor for created_at field.
	investigationmemoryDescCreatedAt := investigationmemoryFields[10].Descriptor()
	// investigationmemory.DefaultCreatedAt holds the default value on creation for the created_at field.
	investigationmemory.DefaultCreatedAt = investigationmemoryDescCreatedAt.Default.(func() time.Time)
	// investigationmemoryDescUpdatedAt is the schema descriptor for updated_at field.
	investigationmemoryDescUpdatedAt := investigationmemoryFields[11].Descriptor()
	// investigationmemory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	investigationmemory.DefaultUpdatedAt = investigationmemoryDescUpdatedAt.Default.(func() time.Time)
	// investigationmemory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	investigationmemory.UpdateDefaultUpdatedAt = investigationmemoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// investigationmemoryDescLastSeenAt is the schema descriptor for last_seen_at field.
	investigationmemoryDescLastSeenAt := investigationmemoryFields[12].Descriptor()
	// investigationmemory.DefaultLastSeenAt holds the default value on creation for the last_seen_at field.
	investigationmemory.DefaultLastSeenAt = investigationmemoryDescLastSeenAt.Default.(func() time.Time)
	// investigationmemoryDescDeprecated is the schema descriptor for deprecated field.
	investigationmemoryDescDeprecated := investigationmemoryFields[13].Descriptor()
	// investigationmemory.DefaultDeprecated holds the default value on creation for the deprecated field.
	investigationmemory.DefaultDeprecated = investigationmemoryDescDeprecated.Default.(bool)
	llminteractionFields := schema.LLMInteraction{}.Fields()
	_ = llminteractionFields
	// llminteractionDescCreatedAt is the schema descriptor for created_at field.
	llminteractionDescCreatedAt := llminteractionFields[4].Descriptor()
	// llminteraction.DefaultCreatedAt holds the default value on creation for the created_at field.
	llminteraction.DefaultCreatedAt = llminteractionDescCreatedAt.Default.(func() time.Time)
	mcpinteractionFields := schema.MCPInteraction{}.Fields()
	_ = mcpinteractionFields
	// mcpinteractionDescCreatedAt is the schema descriptor for created_at field.
	mcpinteractionDescCreatedAt := mcpinteractionFields[4].Descriptor()
	// mcpinteraction.DefaultCreatedAt holds the default value on creation for the created_at field.
	mcpinteraction.DefaultCreatedAt = mcpinteractionDescCreatedAt.Default.(func() time.Time)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageFields[10].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
	sessionreviewactivityFields := schema.SessionReviewActivity{}.Fields()
	_ = sessionreviewactivityFields
	// sessionreviewactivityDescCreatedAt is the schema descriptor for created_at field.
	sessionreviewactivityDescCreatedAt := sessionreviewactivityFields[9].Descriptor()
	// sessionreviewactivity.DefaultCreatedAt holds the default value on creation for the created_at field.
	sessionreviewactivity.DefaultCreatedAt = sessionreviewactivityDescCreatedAt.Default.(func() time.Time)
	sessionscoreFields := schema.SessionScore{}.Fields()
	_ = sessionscoreFields
	// sessionscoreDescStartedAt is the schema descriptor for started_at field.
	sessionscoreDescStartedAt := sessionscoreFields[9].Descriptor()
	// sessionscore.DefaultStartedAt holds the default value on creation for the started_at field.
	sessionscore.DefaultStartedAt = sessionscoreDescStartedAt.Default.(func() time.Time)
	stageFields := schema.Stage{}.Fields()
	_ = stageFields
	timelineeventFields := schema.TimelineEvent{}.Fields()
	_ = timelineeventFields
	// timelineeventDescCreatedAt is the schema descriptor for created_at field.
	timelineeventDescCreatedAt := timelineeventFields[6].Descriptor()
	// timelineevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	timelineevent.DefaultCreatedAt = timelineeventDescCreatedAt.Default.(func() time.Time)
	// timelineeventDescUpdatedAt is the schema descriptor for updated_at field.
	timelineeventDescUpdatedAt := timelineeventFields[7].Descriptor()
	// timelineevent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	timelineevent.DefaultUpdatedAt = timelineeventDescUpdatedAt.Default.(func() time.Time)
	// timelineevent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	timelineevent.UpdateDefaultUpdatedAt = timelineeventDescUpdatedAt.UpdateDefault.(func() time.Time)
}
