// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/codeready-toolchain/tarsy/ent/alertsession"
	"github.com/codeready-toolchain/tarsy/ent/chat"
	"github.com/codeready-toolchain/tarsy/ent/chatusermessage"
	"github.com/codeready-toolchain/tarsy/ent/event"
	"github.com/codeready-toolchain/tarsy/ent/llminteraction"
	"github.com/codeready-toolchain/tarsy/ent/mcpinteraction"
	"github.com/codeready-toolchain/tarsy/ent/message"
	"github.com/codeready-toolchain/tarsy/ent/schema"
	"github.com/codeready-toolchain/tarsy/ent/sessionreviewactivity"
	"github.com/codeready-toolchain/tarsy/ent/sessionscore"
	"github.com/codeready-toolchain/tarsy/ent/timelineevent"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	agentexecutionFields := schema.AgentExecution{}.Fields()
	_ = agentexecutionFields
	alertsessionFields := schema.AlertSession{}.Fields()
	_ = alertsessionFields
	// alertsessionDescCreatedAt is the schema descriptor for created_at field.
	alertsessionDescCreatedAt := alertsessionFields[5].Descriptor()
	// alertsession.DefaultCreatedAt holds the default value on creation for the created_at field.
	alertsession.DefaultCreatedAt = alertsessionDescCreatedAt.Default.(func() time.Time)
	chatFields := schema.Chat{}.Fields()
	_ = chatFields
	// chatDescCreatedAt is the schema descriptor for created_at field.
	chatDescCreatedAt := chatFields[2].Descriptor()
	// chat.DefaultCreatedAt holds the default value on creation for the created_at field.
	chat.DefaultCreatedAt = chatDescCreatedAt.Default.(func() time.Time)
	chatusermessageFields := schema.ChatUserMessage{}.Fields()
	_ = chatusermessageFields
	// chatusermessageDescCreatedAt is the schema descriptor for created_at field.
	chatusermessageDescCreatedAt := chatusermessageFields[4].Descriptor()
	// chatusermessage.DefaultCreatedAt holds the default value on creation for the created_at field.
	chatusermessage.DefaultCreatedAt = chatusermessageDescCreatedAt.Default.(func() time.Time)
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescCreatedAt is the schema descriptor for created_at field.
	eventDescCreatedAt := eventFields[3].Descriptor()
	// event.DefaultCreatedAt holds the default value on creation for the created_at field.
	event.DefaultCreatedAt = eventDescCreatedAt.Default.(func() time.Time)
	llminteractionFields := schema.LLMInteraction{}.Fields()
	_ = llminteractionFields
	// llminteractionDescCreatedAt is the schema descriptor for created_at field.
	llminteractionDescCreatedAt := llminteractionFields[4].Descriptor()
	// llminteraction.DefaultCreatedAt holds the default value on creation for the created_at field.
	llminteraction.DefaultCreatedAt = llminteractionDescCreatedAt.Default.(func() time.Time)
	mcpinteractionFields := schema.MCPInteraction{}.Fields()
	_ = mcpinteractionFields
	// mcpinteractionDescCreatedAt is the schema descriptor for created_at field.
	mcpinteractionDescCreatedAt := mcpinteractionFields[4].Descriptor()
	// mcpinteraction.DefaultCreatedAt holds the default value on creation for the created_at field.
	mcpinteraction.DefaultCreatedAt = mcpinteractionDescCreatedAt.Default.(func() time.Time)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageFields[10].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
	sessionreviewactivityFields := schema.SessionReviewActivity{}.Fields()
	_ = sessionreviewactivityFields
	// sessionreviewactivityDescCreatedAt is the schema descriptor for created_at field.
	sessionreviewactivityDescCreatedAt := sessionreviewactivityFields[8].Descriptor()
	// sessionreviewactivity.DefaultCreatedAt holds the default value on creation for the created_at field.
	sessionreviewactivity.DefaultCreatedAt = sessionreviewactivityDescCreatedAt.Default.(func() time.Time)
	sessionscoreFields := schema.SessionScore{}.Fields()
	_ = sessionscoreFields
	// sessionscoreDescStartedAt is the schema descriptor for started_at field.
	sessionscoreDescStartedAt := sessionscoreFields[8].Descriptor()
	// sessionscore.DefaultStartedAt holds the default value on creation for the started_at field.
	sessionscore.DefaultStartedAt = sessionscoreDescStartedAt.Default.(func() time.Time)
	stageFields := schema.Stage{}.Fields()
	_ = stageFields
	timelineeventFields := schema.TimelineEvent{}.Fields()
	_ = timelineeventFields
	// timelineeventDescCreatedAt is the schema descriptor for created_at field.
	timelineeventDescCreatedAt := timelineeventFields[6].Descriptor()
	// timelineevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	timelineevent.DefaultCreatedAt = timelineeventDescCreatedAt.Default.(func() time.Time)
	// timelineeventDescUpdatedAt is the schema descriptor for updated_at field.
	timelineeventDescUpdatedAt := timelineeventFields[7].Descriptor()
	// timelineevent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	timelineevent.DefaultUpdatedAt = timelineeventDescUpdatedAt.Default.(func() time.Time)
	// timelineevent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	timelineevent.UpdateDefaultUpdatedAt = timelineeventDescUpdatedAt.UpdateDefault.(func() time.Time)
}
