// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/codeready-toolchain/tarsy/ent/predicate"
	"github.com/codeready-toolchain/tarsy/ent/sessionscore"
)

// SessionScoreUpdate is the builder for updating SessionScore entities.
type SessionScoreUpdate struct {
	config
	hooks     []Hook
	mutation  *SessionScoreMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SessionScoreUpdate builder.
func (_u *SessionScoreUpdate) Where(ps ...predicate.SessionScore) *SessionScoreUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPromptHash sets the "prompt_hash" field.
func (_u *SessionScoreUpdate) SetPromptHash(v string) *SessionScoreUpdate {
	_u.mutation.SetPromptHash(v)
	return _u
}

// SetNillablePromptHash sets the "prompt_hash" field if the given value is not nil.
func (_u *SessionScoreUpdate) SetNillablePromptHash(v *string) *SessionScoreUpdate {
	if v != nil {
		_u.SetPromptHash(*v)
	}
	return _u
}

// ClearPromptHash clears the value of the "prompt_hash" field.
func (_u *SessionScoreUpdate) ClearPromptHash() *SessionScoreUpdate {
	_u.mutation.ClearPromptHash()
	return _u
}

// SetTotalScore sets the "total_score" field.
func (_u *SessionScoreUpdate) SetTotalScore(v int) *SessionScoreUpdate {
	_u.mutation.ResetTotalScore()
	_u.mutation.SetTotalScore(v)
	return _u
}

// SetNillableTotalScore sets the "total_score" field if the given value is not nil.
func (_u *SessionScoreUpdate) SetNillableTotalScore(v *int) *SessionScoreUpdate {
	if v != nil {
		_u.SetTotalScore(*v)
	}
	return _u
}

// AddTotalScore adds value to the "total_score" field.
func (_u *SessionScoreUpdate) AddTotalScore(v int) *SessionScoreUpdate {
	_u.mutation.AddTotalScore(v)
	return _u
}

// ClearTotalScore clears the value of the "total_score" field.
func (_u *SessionScoreUpdate) ClearTotalScore() *SessionScoreUpdate {
	_u.mutation.ClearTotalScore()
	return _u
}

// SetScoreAnalysis sets the "score_analysis" field.
func (_u *SessionScoreUpdate) SetScoreAnalysis(v string) *SessionScoreUpdate {
	_u.mutation.SetScoreAnalysis(v)
	return _u
}

// SetNillableScoreAnalysis sets the "score_analysis" field if the given value is not nil.
func (_u *SessionScoreUpdate) SetNillableScoreAnalysis(v *string) *SessionScoreUpdate {
	if v != nil {
		_u.SetScoreAnalysis(*v)
	}
	return _u
}

// ClearScoreAnalysis clears the value of the "score_analysis" field.
func (_u *SessionScoreUpdate) ClearScoreAnalysis() *SessionScoreUpdate {
	_u.mutation.ClearScoreAnalysis()
	return _u
}

// SetToolImprovementReport sets the "tool_improvement_report" field.
func (_u *SessionScoreUpdate) SetToolImprovementReport(v string) *SessionScoreUpdate {
	_u.mutation.SetToolImprovementReport(v)
	return _u
}

// SetNillableToolImprovementReport sets the "tool_improvement_report" field if the given value is not nil.
func (_u *SessionScoreUpdate) SetNillableToolImprovementReport(v *string) *SessionScoreUpdate {
	if v != nil {
		_u.SetToolImprovementReport(*v)
	}
	return _u
}

// ClearToolImprovementReport clears the value of the "tool_improvement_report" field.
func (_u *SessionScoreUpdate) ClearToolImprovementReport() *SessionScoreUpdate {
	_u.mutation.ClearToolImprovementReport()
	return _u
}

// SetFailureTags sets the "failure_tags" field.
func (_u *SessionScoreUpdate) SetFailureTags(v []string) *SessionScoreUpdate {
	_u.mutation.SetFailureTags(v)
	return _u
}

// AppendFailureTags appends value to the "failure_tags" field.
func (_u *SessionScoreUpdate) AppendFailureTags(v []string) *SessionScoreUpdate {
	_u.mutation.AppendFailureTags(v)
	return _u
}

// ClearFailureTags clears the value of the "failure_tags" field.
func (_u *SessionScoreUpdate) ClearFailureTags() *SessionScoreUpdate {
	_u.mutation.ClearFailureTags()
	return _u
}

// SetScoreTriggeredBy sets the "score_triggered_by" field.
func (_u *SessionScoreUpdate) SetScoreTriggeredBy(v string) *SessionScoreUpdate {
	_u.mutation.SetScoreTriggeredBy(v)
	return _u
}

// SetNillableScoreTriggeredBy sets the "score_triggered_by" field if the given value is not nil.
func (_u *SessionScoreUpdate) SetNillableScoreTriggeredBy(v *string) *SessionScoreUpdate {
	if v != nil {
		_u.SetScoreTriggeredBy(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SessionScoreUpdate) SetStatus(v sessionscore.Status) *SessionScoreUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SessionScoreUpdate) SetNillableStatus(v *sessionscore.Status) *SessionScoreUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *SessionScoreUpdate) SetCompletedAt(v time.Time) *SessionScoreUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *SessionScoreUpdate) SetNillableCompletedAt(v *time.Time) *SessionScoreUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *SessionScoreUpdate) ClearCompletedAt() *SessionScoreUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *SessionScoreUpdate) SetErrorMessage(v string) *SessionScoreUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *SessionScoreUpdate) SetNillableErrorMessage(v *string) *SessionScoreUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *SessionScoreUpdate) ClearErrorMessage() *SessionScoreUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// Mutation returns the SessionScoreMutation object of the builder.
func (_u *SessionScoreUpdate) Mutation() *SessionScoreMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SessionScoreUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionScoreUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SessionScoreUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionScoreUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionScoreUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := sessionscore.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SessionScore.status": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SessionScore.session"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SessionScoreUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SessionScoreUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SessionScoreUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sessionscore.Table, sessionscore.Columns, sqlgraph.NewFieldSpec(sessionscore.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PromptHash(); ok {
		_spec.SetField(sessionscore.FieldPromptHash, field.TypeString, value)
	}
	if _u.mutation.PromptHashCleared() {
		_spec.ClearField(sessionscore.FieldPromptHash, field.TypeString)
	}
	if value, ok := _u.mutation.TotalScore(); ok {
		_spec.SetField(sessionscore.FieldTotalScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalScore(); ok {
		_spec.AddField(sessionscore.FieldTotalScore, field.TypeInt, value)
	}
	if _u.mutation.TotalScoreCleared() {
		_spec.ClearField(sessionscore.FieldTotalScore, field.TypeInt)
	}
	if value, ok := _u.mutation.ScoreAnalysis(); ok {
		_spec.SetField(sessionscore.FieldScoreAnalysis, field.TypeString, value)
	}
	if _u.mutation.ScoreAnalysisCleared() {
		_spec.ClearField(sessionscore.FieldScoreAnalysis, field.TypeString)
	}
	if value, ok := _u.mutation.ToolImprovementReport(); ok {
		_spec.SetField(sessionscore.FieldToolImprovementReport, field.TypeString, value)
	}
	if _u.mutation.ToolImprovementReportCleared() {
		_spec.ClearField(sessionscore.FieldToolImprovementReport, field.TypeString)
	}
	if value, ok := _u.mutation.FailureTags(); ok {
		_spec.SetField(sessionscore.FieldFailureTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFailureTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, sessionscore.FieldFailureTags, value)
		})
	}
	if _u.mutation.FailureTagsCleared() {
		_spec.ClearField(sessionscore.FieldFailureTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.ScoreTriggeredBy(); ok {
		_spec.SetField(sessionscore.FieldScoreTriggeredBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sessionscore.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(sessionscore.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(sessionscore.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(sessionscore.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(sessionscore.FieldErrorMessage, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sessionscore.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SessionScoreUpdateOne is the builder for updating a single SessionScore entity.
type SessionScoreUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SessionScoreMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetPromptHash sets the "prompt_hash" field.
func (_u *SessionScoreUpdateOne) SetPromptHash(v string) *SessionScoreUpdateOne {
	_u.mutation.SetPromptHash(v)
	return _u
}

// SetNillablePromptHash sets the "prompt_hash" field if the given value is not nil.
func (_u *SessionScoreUpdateOne) SetNillablePromptHash(v *string) *SessionScoreUpdateOne {
	if v != nil {
		_u.SetPromptHash(*v)
	}
	return _u
}

// ClearPromptHash clears the value of the "prompt_hash" field.
func (_u *SessionScoreUpdateOne) ClearPromptHash() *SessionScoreUpdateOne {
	_u.mutation.ClearPromptHash()
	return _u
}

// SetTotalScore sets the "total_score" field.
func (_u *SessionScoreUpdateOne) SetTotalScore(v int) *SessionScoreUpdateOne {
	_u.mutation.ResetTotalScore()
	_u.mutation.SetTotalScore(v)
	return _u
}

// SetNillableTotalScore sets the "total_score" field if the given value is not nil.
func (_u *SessionScoreUpdateOne) SetNillableTotalScore(v *int) *SessionScoreUpdateOne {
	if v != nil {
		_u.SetTotalScore(*v)
	}
	return _u
}

// AddTotalScore adds value to the "total_score" field.
func (_u *SessionScoreUpdateOne) AddTotalScore(v int) *SessionScoreUpdateOne {
	_u.mutation.AddTotalScore(v)
	return _u
}

// ClearTotalScore clears the value of the "total_score" field.
func (_u *SessionScoreUpdateOne) ClearTotalScore() *SessionScoreUpdateOne {
	_u.mutation.ClearTotalScore()
	return _u
}

// SetScoreAnalysis sets the "score_analysis" field.
func (_u *SessionScoreUpdateOne) SetScoreAnalysis(v string) *SessionScoreUpdateOne {
	_u.mutation.SetScoreAnalysis(v)
	return _u
}

// SetNillableScoreAnalysis sets the "score_analysis" field if the given value is not nil.
func (_u *SessionScoreUpdateOne) SetNillableScoreAnalysis(v *string) *SessionScoreUpdateOne {
	if v != nil {
		_u.SetScoreAnalysis(*v)
	}
	return _u
}

// ClearScoreAnalysis clears the value of the "score_analysis" field.
func (_u *SessionScoreUpdateOne) ClearScoreAnalysis() *SessionScoreUpdateOne {
	_u.mutation.ClearScoreAnalysis()
	return _u
}

// SetToolImprovementReport sets the "tool_improvement_report" field.
func (_u *SessionScoreUpdateOne) SetToolImprovementReport(v string) *SessionScoreUpdateOne {
	_u.mutation.SetToolImprovementReport(v)
	return _u
}

// SetNillableToolImprovementReport sets the "tool_improvement_report" field if the given value is not nil.
func (_u *SessionScoreUpdateOne) SetNillableToolImprovementReport(v *string) *SessionScoreUpdateOne {
	if v != nil {
		_u.SetToolImprovementReport(*v)
	}
	return _u
}

// ClearToolImprovementReport clears the value of the "tool_improvement_report" field.
func (_u *SessionScoreUpdateOne) ClearToolImprovementReport() *SessionScoreUpdateOne {
	_u.mutation.ClearToolImprovementReport()
	return _u
}

// SetFailureTags sets the "failure_tags" field.
func (_u *SessionScoreUpdateOne) SetFailureTags(v []string) *SessionScoreUpdateOne {
	_u.mutation.SetFailureTags(v)
	return _u
}

// AppendFailureTags appends value to the "failure_tags" field.
func (_u *SessionScoreUpdateOne) AppendFailureTags(v []string) *SessionScoreUpdateOne {
	_u.mutation.AppendFailureTags(v)
	return _u
}

// ClearFailureTags clears the value of the "failure_tags" field.
func (_u *SessionScoreUpdateOne) ClearFailureTags() *SessionScoreUpdateOne {
	_u.mutation.ClearFailureTags()
	return _u
}

// SetScoreTriggeredBy sets the "score_triggered_by" field.
func (_u *SessionScoreUpdateOne) SetScoreTriggeredBy(v string) *SessionScoreUpdateOne {
	_u.mutation.SetScoreTriggeredBy(v)
	return _u
}

// SetNillableScoreTriggeredBy sets the "score_triggered_by" field if the given value is not nil.
func (_u *SessionScoreUpdateOne) SetNillableScoreTriggeredBy(v *string) *SessionScoreUpdateOne {
	if v != nil {
		_u.SetScoreTriggeredBy(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SessionScoreUpdateOne) SetStatus(v sessionscore.Status) *SessionScoreUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SessionScoreUpdateOne) SetNillableStatus(v *sessionscore.Status) *SessionScoreUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *SessionScoreUpdateOne) SetCompletedAt(v time.Time) *SessionScoreUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *SessionScoreUpdateOne) SetNillableCompletedAt(v *time.Time) *SessionScoreUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *SessionScoreUpdateOne) ClearCompletedAt() *SessionScoreUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *SessionScoreUpdateOne) SetErrorMessage(v string) *SessionScoreUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *SessionScoreUpdateOne) SetNillableErrorMessage(v *string) *SessionScoreUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *SessionScoreUpdateOne) ClearErrorMessage() *SessionScoreUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// Mutation returns the SessionScoreMutation object of the builder.
func (_u *SessionScoreUpdateOne) Mutation() *SessionScoreMutation {
	return _u.mutation
}

// Where appends a list predicates to the SessionScoreUpdate builder.
func (_u *SessionScoreUpdateOne) Where(ps ...predicate.SessionScore) *SessionScoreUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SessionScoreUpdateOne) Select(field string, fields ...string) *SessionScoreUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SessionScore entity.
func (_u *SessionScoreUpdateOne) Save(ctx context.Context) (*SessionScore, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionScoreUpdateOne) SaveX(ctx context.Context) *SessionScore {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SessionScoreUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionScoreUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionScoreUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := sessionscore.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SessionScore.status": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SessionScore.session"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SessionScoreUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SessionScoreUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SessionScoreUpdateOne) sqlSave(ctx context.Context) (_node *SessionScore, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sessionscore.Table, sessionscore.Columns, sqlgraph.NewFieldSpec(sessionscore.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SessionScore.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sessionscore.FieldID)
		for _, f := range fields {
			if !sessionscore.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sessionscore.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PromptHash(); ok {
		_spec.SetField(sessionscore.FieldPromptHash, field.TypeString, value)
	}
	if _u.mutation.PromptHashCleared() {
		_spec.ClearField(sessionscore.FieldPromptHash, field.TypeString)
	}
	if value, ok := _u.mutation.TotalScore(); ok {
		_spec.SetField(sessionscore.FieldTotalScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalScore(); ok {
		_spec.AddField(sessionscore.FieldTotalScore, field.TypeInt, value)
	}
	if _u.mutation.TotalScoreCleared() {
		_spec.ClearField(sessionscore.FieldTotalScore, field.TypeInt)
	}
	if value, ok := _u.mutation.ScoreAnalysis(); ok {
		_spec.SetField(sessionscore.FieldScoreAnalysis, field.TypeString, value)
	}
	if _u.mutation.ScoreAnalysisCleared() {
		_spec.ClearField(sessionscore.FieldScoreAnalysis, field.TypeString)
	}
	if value, ok := _u.mutation.ToolImprovementReport(); ok {
		_spec.SetField(sessionscore.FieldToolImprovementReport, field.TypeString, value)
	}
	if _u.mutation.ToolImprovementReportCleared() {
		_spec.ClearField(sessionscore.FieldToolImprovementReport, field.TypeString)
	}
	if value, ok := _u.mutation.FailureTags(); ok {
		_spec.SetField(sessionscore.FieldFailureTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFailureTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, sessionscore.FieldFailureTags, value)
		})
	}
	if _u.mutation.FailureTagsCleared() {
		_spec.ClearField(sessionscore.FieldFailureTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.ScoreTriggeredBy(); ok {
		_spec.SetField(sessionscore.FieldScoreTriggeredBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sessionscore.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(sessionscore.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(sessionscore.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(sessionscore.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(sessionscore.FieldErrorMessage, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &SessionScore{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sessionscore.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
