// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/codeready-toolchain/tarsy/ent/alertsession"
	"github.com/codeready-toolchain/tarsy/ent/sessionscore"
	"github.com/codeready-toolchain/tarsy/ent/stage"
)

// SessionScoreCreate is the builder for creating a SessionScore entity.
type SessionScoreCreate struct {
	config
	mutation *SessionScoreMutation
	hooks    []Hook
}

// SetSessionID sets the "session_id" field.
func (_c *SessionScoreCreate) SetSessionID(v string) *SessionScoreCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetPromptHash sets the "prompt_hash" field.
func (_c *SessionScoreCreate) SetPromptHash(v string) *SessionScoreCreate {
	_c.mutation.SetPromptHash(v)
	return _c
}

// SetNillablePromptHash sets the "prompt_hash" field if the given value is not nil.
func (_c *SessionScoreCreate) SetNillablePromptHash(v *string) *SessionScoreCreate {
	if v != nil {
		_c.SetPromptHash(*v)
	}
	return _c
}

// SetTotalScore sets the "total_score" field.
func (_c *SessionScoreCreate) SetTotalScore(v int) *SessionScoreCreate {
	_c.mutation.SetTotalScore(v)
	return _c
}

// SetNillableTotalScore sets the "total_score" field if the given value is not nil.
func (_c *SessionScoreCreate) SetNillableTotalScore(v *int) *SessionScoreCreate {
	if v != nil {
		_c.SetTotalScore(*v)
	}
	return _c
}

// SetScoreAnalysis sets the "score_analysis" field.
func (_c *SessionScoreCreate) SetScoreAnalysis(v string) *SessionScoreCreate {
	_c.mutation.SetScoreAnalysis(v)
	return _c
}

// SetNillableScoreAnalysis sets the "score_analysis" field if the given value is not nil.
func (_c *SessionScoreCreate) SetNillableScoreAnalysis(v *string) *SessionScoreCreate {
	if v != nil {
		_c.SetScoreAnalysis(*v)
	}
	return _c
}

// SetToolImprovementReport sets the "tool_improvement_report" field.
func (_c *SessionScoreCreate) SetToolImprovementReport(v string) *SessionScoreCreate {
	_c.mutation.SetToolImprovementReport(v)
	return _c
}

// SetNillableToolImprovementReport sets the "tool_improvement_report" field if the given value is not nil.
func (_c *SessionScoreCreate) SetNillableToolImprovementReport(v *string) *SessionScoreCreate {
	if v != nil {
		_c.SetToolImprovementReport(*v)
	}
	return _c
}

// SetFailureTags sets the "failure_tags" field.
func (_c *SessionScoreCreate) SetFailureTags(v []string) *SessionScoreCreate {
	_c.mutation.SetFailureTags(v)
	return _c
}

// SetScoreTriggeredBy sets the "score_triggered_by" field.
func (_c *SessionScoreCreate) SetScoreTriggeredBy(v string) *SessionScoreCreate {
	_c.mutation.SetScoreTriggeredBy(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *SessionScoreCreate) SetStatus(v sessionscore.Status) *SessionScoreCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SessionScoreCreate) SetNillableStatus(v *sessionscore.Status) *SessionScoreCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *SessionScoreCreate) SetStartedAt(v time.Time) *SessionScoreCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *SessionScoreCreate) SetNillableStartedAt(v *time.Time) *SessionScoreCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *SessionScoreCreate) SetCompletedAt(v time.Time) *SessionScoreCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *SessionScoreCreate) SetNillableCompletedAt(v *time.Time) *SessionScoreCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *SessionScoreCreate) SetErrorMessage(v string) *SessionScoreCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *SessionScoreCreate) SetNillableErrorMessage(v *string) *SessionScoreCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetStageID sets the "stage_id" field.
func (_c *SessionScoreCreate) SetStageID(v string) *SessionScoreCreate {
	_c.mutation.SetStageID(v)
	return _c
}

// SetNillableStageID sets the "stage_id" field if the given value is not nil.
func (_c *SessionScoreCreate) SetNillableStageID(v *string) *SessionScoreCreate {
	if v != nil {
		_c.SetStageID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SessionScoreCreate) SetID(v string) *SessionScoreCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSession sets the "session" edge to the AlertSession entity.
func (_c *SessionScoreCreate) SetSession(v *AlertSession) *SessionScoreCreate {
	return _c.SetSessionID(v.ID)
}

// SetStage sets the "stage" edge to the Stage entity.
func (_c *SessionScoreCreate) SetStage(v *Stage) *SessionScoreCreate {
	return _c.SetStageID(v.ID)
}

// Mutation returns the SessionScoreMutation object of the builder.
func (_c *SessionScoreCreate) Mutation() *SessionScoreMutation {
	return _c.mutation
}

// Save creates the SessionScore in the database.
func (_c *SessionScoreCreate) Save(ctx context.Context) (*SessionScore, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SessionScoreCreate) SaveX(ctx context.Context) *SessionScore {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionScoreCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionScoreCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SessionScoreCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := sessionscore.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		v := sessionscore.DefaultStartedAt()
		_c.mutation.SetStartedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SessionScoreCreate) check() error {
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "SessionScore.session_id"`)}
	}
	if _, ok := _c.mutation.ScoreTriggeredBy(); !ok {
		return &ValidationError{Name: "score_triggered_by", err: errors.New(`ent: missing required field "SessionScore.score_triggered_by"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SessionScore.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := sessionscore.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SessionScore.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "SessionScore.started_at"`)}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "SessionScore.session"`)}
	}
	return nil
}

func (_c *SessionScoreCreate) sqlSave(ctx context.Context) (*SessionScore, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SessionScore.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SessionScoreCreate) createSpec() (*SessionScore, *sqlgraph.CreateSpec) {
	var (
		_node = &SessionScore{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sessionscore.Table, sqlgraph.NewFieldSpec(sessionscore.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PromptHash(); ok {
		_spec.SetField(sessionscore.FieldPromptHash, field.TypeString, value)
		_node.PromptHash = &value
	}
	if value, ok := _c.mutation.TotalScore(); ok {
		_spec.SetField(sessionscore.FieldTotalScore, field.TypeInt, value)
		_node.TotalScore = &value
	}
	if value, ok := _c.mutation.ScoreAnalysis(); ok {
		_spec.SetField(sessionscore.FieldScoreAnalysis, field.TypeString, value)
		_node.ScoreAnalysis = &value
	}
	if value, ok := _c.mutation.ToolImprovementReport(); ok {
		_spec.SetField(sessionscore.FieldToolImprovementReport, field.TypeString, value)
		_node.ToolImprovementReport = &value
	}
	if value, ok := _c.mutation.FailureTags(); ok {
		_spec.SetField(sessionscore.FieldFailureTags, field.TypeJSON, value)
		_node.FailureTags = value
	}
	if value, ok := _c.mutation.ScoreTriggeredBy(); ok {
		_spec.SetField(sessionscore.FieldScoreTriggeredBy, field.TypeString, value)
		_node.ScoreTriggeredBy = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(sessionscore.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(sessionscore.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(sessionscore.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(sessionscore.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sessionscore.SessionTable,
			Columns: []string{sessionscore.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertsession.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sessionscore.StageTable,
			Columns: []string{sessionscore.StageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.StageID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SessionScoreCreateBulk is the builder for creating many SessionScore entities in bulk.
type SessionScoreCreateBulk struct {
	config
	err      error
	builders []*SessionScoreCreate
}

// Save creates the SessionScore entities in the database.
func (_c *SessionScoreCreateBulk) Save(ctx context.Context) ([]*SessionScore, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SessionScore, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SessionScoreMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SessionScoreCreateBulk) SaveX(ctx context.Context) []*SessionScore {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionScoreCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionScoreCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
