// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/codeready-toolchain/tarsy/ent/predicate"
	"github.com/codeready-toolchain/tarsy/ent/sessionreviewactivity"
)

// SessionReviewActivityUpdate is the builder for updating SessionReviewActivity entities.
type SessionReviewActivityUpdate struct {
	config
	hooks     []Hook
	mutation  *SessionReviewActivityMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SessionReviewActivityUpdate builder.
func (_u *SessionReviewActivityUpdate) Where(ps ...predicate.SessionReviewActivity) *SessionReviewActivityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the SessionReviewActivityMutation object of the builder.
func (_u *SessionReviewActivityUpdate) Mutation() *SessionReviewActivityMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SessionReviewActivityUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionReviewActivityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SessionReviewActivityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionReviewActivityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionReviewActivityUpdate) check() error {
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SessionReviewActivity.session"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SessionReviewActivityUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SessionReviewActivityUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SessionReviewActivityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sessionreviewactivity.Table, sessionreviewactivity.Columns, sqlgraph.NewFieldSpec(sessionreviewactivity.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.FromStatusCleared() {
		_spec.ClearField(sessionreviewactivity.FieldFromStatus, field.TypeEnum)
	}
	if _u.mutation.ResolutionReasonCleared() {
		_spec.ClearField(sessionreviewactivity.FieldResolutionReason, field.TypeEnum)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(sessionreviewactivity.FieldNote, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sessionreviewactivity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SessionReviewActivityUpdateOne is the builder for updating a single SessionReviewActivity entity.
type SessionReviewActivityUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SessionReviewActivityMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Mutation returns the SessionReviewActivityMutation object of the builder.
func (_u *SessionReviewActivityUpdateOne) Mutation() *SessionReviewActivityMutation {
	return _u.mutation
}

// Where appends a list predicates to the SessionReviewActivityUpdate builder.
func (_u *SessionReviewActivityUpdateOne) Where(ps ...predicate.SessionReviewActivity) *SessionReviewActivityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SessionReviewActivityUpdateOne) Select(field string, fields ...string) *SessionReviewActivityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SessionReviewActivity entity.
func (_u *SessionReviewActivityUpdateOne) Save(ctx context.Context) (*SessionReviewActivity, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionReviewActivityUpdateOne) SaveX(ctx context.Context) *SessionReviewActivity {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SessionReviewActivityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionReviewActivityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionReviewActivityUpdateOne) check() error {
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SessionReviewActivity.session"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SessionReviewActivityUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SessionReviewActivityUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SessionReviewActivityUpdateOne) sqlSave(ctx context.Context) (_node *SessionReviewActivity, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sessionreviewactivity.Table, sessionreviewactivity.Columns, sqlgraph.NewFieldSpec(sessionreviewactivity.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SessionReviewActivity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sessionreviewactivity.FieldID)
		for _, f := range fields {
			if !sessionreviewactivity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sessionreviewactivity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.FromStatusCleared() {
		_spec.ClearField(sessionreviewactivity.FieldFromStatus, field.TypeEnum)
	}
	if _u.mutation.ResolutionReasonCleared() {
		_spec.ClearField(sessionreviewactivity.FieldResolutionReason, field.TypeEnum)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(sessionreviewactivity.FieldNote, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &SessionReviewActivity{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sessionreviewactivity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
