// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/codeready-toolchain/tarsy/ent/agentexecution"
	"github.com/codeready-toolchain/tarsy/ent/chat"
	"github.com/codeready-toolchain/tarsy/ent/chatusermessage"
	"github.com/codeready-toolchain/tarsy/ent/llminteraction"
	"github.com/codeready-toolchain/tarsy/ent/mcpinteraction"
	"github.com/codeready-toolchain/tarsy/ent/message"
	"github.com/codeready-toolchain/tarsy/ent/predicate"
	"github.com/codeready-toolchain/tarsy/ent/sessionscore"
	"github.com/codeready-toolchain/tarsy/ent/stage"
	"github.com/codeready-toolchain/tarsy/ent/timelineevent"
)

// StageUpdate is the builder for updating Stage entities.
type StageUpdate struct {
	config
	hooks     []Hook
	mutation  *StageMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the StageUpdate builder.
func (_u *StageUpdate) Where(ps ...predicate.Stage) *StageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStageName sets the "stage_name" field.
func (_u *StageUpdate) SetStageName(v string) *StageUpdate {
	_u.mutation.SetStageName(v)
	return _u
}

// SetNillableStageName sets the "stage_name" field if the given value is not nil.
func (_u *StageUpdate) SetNillableStageName(v *string) *StageUpdate {
	if v != nil {
		_u.SetStageName(*v)
	}
	return _u
}

// SetStageIndex sets the "stage_index" field.
func (_u *StageUpdate) SetStageIndex(v int) *StageUpdate {
	_u.mutation.ResetStageIndex()
	_u.mutation.SetStageIndex(v)
	return _u
}

// SetNillableStageIndex sets the "stage_index" field if the given value is not nil.
func (_u *StageUpdate) SetNillableStageIndex(v *int) *StageUpdate {
	if v != nil {
		_u.SetStageIndex(*v)
	}
	return _u
}

// AddStageIndex adds value to the "stage_index" field.
func (_u *StageUpdate) AddStageIndex(v int) *StageUpdate {
	_u.mutation.AddStageIndex(v)
	return _u
}

// SetExpectedAgentCount sets the "expected_agent_count" field.
func (_u *StageUpdate) SetExpectedAgentCount(v int) *StageUpdate {
	_u.mutation.ResetExpectedAgentCount()
	_u.mutation.SetExpectedAgentCount(v)
	return _u
}

// SetNillableExpectedAgentCount sets the "expected_agent_count" field if the given value is not nil.
func (_u *StageUpdate) SetNillableExpectedAgentCount(v *int) *StageUpdate {
	if v != nil {
		_u.SetExpectedAgentCount(*v)
	}
	return _u
}

// AddExpectedAgentCount adds value to the "expected_agent_count" field.
func (_u *StageUpdate) AddExpectedAgentCount(v int) *StageUpdate {
	_u.mutation.AddExpectedAgentCount(v)
	return _u
}

// SetParallelType sets the "parallel_type" field.
func (_u *StageUpdate) SetParallelType(v stage.ParallelType) *StageUpdate {
	_u.mutation.SetParallelType(v)
	return _u
}

// SetNillableParallelType sets the "parallel_type" field if the given value is not nil.
func (_u *StageUpdate) SetNillableParallelType(v *stage.ParallelType) *StageUpdate {
	if v != nil {
		_u.SetParallelType(*v)
	}
	return _u
}

// ClearParallelType clears the value of the "parallel_type" field.
func (_u *StageUpdate) ClearParallelType() *StageUpdate {
	_u.mutation.ClearParallelType()
	return _u
}

// SetSuccessPolicy sets the "success_policy" field.
func (_u *StageUpdate) SetSuccessPolicy(v stage.SuccessPolicy) *StageUpdate {
	_u.mutation.SetSuccessPolicy(v)
	return _u
}

// SetNillableSuccessPolicy sets the "success_policy" field if the given value is not nil.
func (_u *StageUpdate) SetNillableSuccessPolicy(v *stage.SuccessPolicy) *StageUpdate {
	if v != nil {
		_u.SetSuccessPolicy(*v)
	}
	return _u
}

// ClearSuccessPolicy clears the value of the "success_policy" field.
func (_u *StageUpdate) ClearSuccessPolicy() *StageUpdate {
	_u.mutation.ClearSuccessPolicy()
	return _u
}

// SetStageType sets the "stage_type" field.
func (_u *StageUpdate) SetStageType(v stage.StageType) *StageUpdate {
	_u.mutation.SetStageType(v)
	return _u
}

// SetNillableStageType sets the "stage_type" field if the given value is not nil.
func (_u *StageUpdate) SetNillableStageType(v *stage.StageType) *StageUpdate {
	if v != nil {
		_u.SetStageType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *StageUpdate) SetStatus(v stage.Status) *StageUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *StageUpdate) SetNillableStatus(v *stage.Status) *StageUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *StageUpdate) SetStartedAt(v time.Time) *StageUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *StageUpdate) SetNillableStartedAt(v *time.Time) *StageUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *StageUpdate) ClearStartedAt() *StageUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *StageUpdate) SetCompletedAt(v time.Time) *StageUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *StageUpdate) SetNillableCompletedAt(v *time.Time) *StageUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *StageUpdate) ClearCompletedAt() *StageUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *StageUpdate) SetDurationMs(v int) *StageUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *StageUpdate) SetNillableDurationMs(v *int) *StageUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *StageUpdate) AddDurationMs(v int) *StageUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *StageUpdate) ClearDurationMs() *StageUpdate {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *StageUpdate) SetErrorMessage(v string) *StageUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *StageUpdate) SetNillableErrorMessage(v *string) *StageUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *StageUpdate) ClearErrorMessage() *StageUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *StageUpdate) SetChatID(v string) *StageUpdate {
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *StageUpdate) SetNillableChatID(v *string) *StageUpdate {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// ClearChatID clears the value of the "chat_id" field.
func (_u *StageUpdate) ClearChatID() *StageUpdate {
	_u.mutation.ClearChatID()
	return _u
}

// SetChatUserMessageID sets the "chat_user_message_id" field.
func (_u *StageUpdate) SetChatUserMessageID(v string) *StageUpdate {
	_u.mutation.SetChatUserMessageID(v)
	return _u
}

// SetNillableChatUserMessageID sets the "chat_user_message_id" field if the given value is not nil.
func (_u *StageUpdate) SetNillableChatUserMessageID(v *string) *StageUpdate {
	if v != nil {
		_u.SetChatUserMessageID(*v)
	}
	return _u
}

// ClearChatUserMessageID clears the value of the "chat_user_message_id" field.
func (_u *StageUpdate) ClearChatUserMessageID() *StageUpdate {
	_u.mutation.ClearChatUserMessageID()
	return _u
}

// SetReferencedStageID sets the "referenced_stage_id" field.
func (_u *StageUpdate) SetReferencedStageID(v string) *StageUpdate {
	_u.mutation.SetReferencedStageID(v)
	return _u
}

// SetNillableReferencedStageID sets the "referenced_stage_id" field if the given value is not nil.
func (_u *StageUpdate) SetNillableReferencedStageID(v *string) *StageUpdate {
	if v != nil {
		_u.SetReferencedStageID(*v)
	}
	return _u
}

// ClearReferencedStageID clears the value of the "referenced_stage_id" field.
func (_u *StageUpdate) ClearReferencedStageID() *StageUpdate {
	_u.mutation.ClearReferencedStageID()
	return _u
}

// SetActionsExecuted sets the "actions_executed" field.
func (_u *StageUpdate) SetActionsExecuted(v bool) *StageUpdate {
	_u.mutation.SetActionsExecuted(v)
	return _u
}

// SetNillableActionsExecuted sets the "actions_executed" field if the given value is not nil.
func (_u *StageUpdate) SetNillableActionsExecuted(v *bool) *StageUpdate {
	if v != nil {
		_u.SetActionsExecuted(*v)
	}
	return _u
}

// ClearActionsExecuted clears the value of the "actions_executed" field.
func (_u *StageUpdate) ClearActionsExecuted() *StageUpdate {
	_u.mutation.ClearActionsExecuted()
	return _u
}

// AddAgentExecutionIDs adds the "agent_executions" edge to the AgentExecution entity by IDs.
func (_u *StageUpdate) AddAgentExecutionIDs(ids ...string) *StageUpdate {
	_u.mutation.AddAgentExecutionIDs(ids...)
	return _u
}

// AddAgentExecutions adds the "agent_executions" edges to the AgentExecution entity.
func (_u *StageUpdate) AddAgentExecutions(v ...*AgentExecution) *StageUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAgentExecutionIDs(ids...)
}

// AddTimelineEventIDs adds the "timeline_events" edge to the TimelineEvent entity by IDs.
func (_u *StageUpdate) AddTimelineEventIDs(ids ...string) *StageUpdate {
	_u.mutation.AddTimelineEventIDs(ids...)
	return _u
}

// AddTimelineEvents adds the "timeline_events" edges to the TimelineEvent entity.
func (_u *StageUpdate) AddTimelineEvents(v ...*TimelineEvent) *StageUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTimelineEventIDs(ids...)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (_u *StageUpdate) AddMessageIDs(ids ...string) *StageUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the Message entity.
func (_u *StageUpdate) AddMessages(v ...*Message) *StageUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// AddLlmInteractionIDs adds the "llm_interactions" edge to the LLMInteraction entity by IDs.
func (_u *StageUpdate) AddLlmInteractionIDs(ids ...string) *StageUpdate {
	_u.mutation.AddLlmInteractionIDs(ids...)
	return _u
}

// AddLlmInteractions adds the "llm_interactions" edges to the LLMInteraction entity.
func (_u *StageUpdate) AddLlmInteractions(v ...*LLMInteraction) *StageUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLlmInteractionIDs(ids...)
}

// AddMcpInteractionIDs adds the "mcp_interactions" edge to the MCPInteraction entity by IDs.
func (_u *StageUpdate) AddMcpInteractionIDs(ids ...string) *StageUpdate {
	_u.mutation.AddMcpInteractionIDs(ids...)
	return _u
}

// AddMcpInteractions adds the "mcp_interactions" edges to the MCPInteraction entity.
func (_u *StageUpdate) AddMcpInteractions(v ...*MCPInteraction) *StageUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMcpInteractionIDs(ids...)
}

// SetChat sets the "chat" edge to the Chat entity.
func (_u *StageUpdate) SetChat(v *Chat) *StageUpdate {
	return _u.SetChatID(v.ID)
}

// SetChatUserMessage sets the "chat_user_message" edge to the ChatUserMessage entity.
func (_u *StageUpdate) SetChatUserMessage(v *ChatUserMessage) *StageUpdate {
	return _u.SetChatUserMessageID(v.ID)
}

// AddSessionScoreIDs adds the "session_scores" edge to the SessionScore entity by IDs.
func (_u *StageUpdate) AddSessionScoreIDs(ids ...string) *StageUpdate {
	_u.mutation.AddSessionScoreIDs(ids...)
	return _u
}

// AddSessionScores adds the "session_scores" edges to the SessionScore entity.
func (_u *StageUpdate) AddSessionScores(v ...*SessionScore) *StageUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSessionScoreIDs(ids...)
}

// AddReferencingStageIDs adds the "referencing_stages" edge to the Stage entity by IDs.
func (_u *StageUpdate) AddReferencingStageIDs(ids ...string) *StageUpdate {
	_u.mutation.AddReferencingStageIDs(ids...)
	return _u
}

// AddReferencingStages adds the "referencing_stages" edges to the Stage entity.
func (_u *StageUpdate) AddReferencingStages(v ...*Stage) *StageUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReferencingStageIDs(ids...)
}

// SetReferencedStage sets the "referenced_stage" edge to the Stage entity.
func (_u *StageUpdate) SetReferencedStage(v *Stage) *StageUpdate {
	return _u.SetReferencedStageID(v.ID)
}

// Mutation returns the StageMutation object of the builder.
func (_u *StageUpdate) Mutation() *StageMutation {
	return _u.mutation
}

// ClearAgentExecutions clears all "agent_executions" edges to the AgentExecution entity.
func (_u *StageUpdate) ClearAgentExecutions() *StageUpdate {
	_u.mutation.ClearAgentExecutions()
	return _u
}

// RemoveAgentExecutionIDs removes the "agent_executions" edge to AgentExecution entities by IDs.
func (_u *StageUpdate) RemoveAgentExecutionIDs(ids ...string) *StageUpdate {
	_u.mutation.RemoveAgentExecutionIDs(ids...)
	return _u
}

// RemoveAgentExecutions removes "agent_executions" edges to AgentExecution entities.
func (_u *StageUpdate) RemoveAgentExecutions(v ...*AgentExecution) *StageUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAgentExecutionIDs(ids...)
}

// ClearTimelineEvents clears all "timeline_events" edges to the TimelineEvent entity.
func (_u *StageUpdate) ClearTimelineEvents() *StageUpdate {
	_u.mutation.ClearTimelineEvents()
	return _u
}

// RemoveTimelineEventIDs removes the "timeline_events" edge to TimelineEvent entities by IDs.
func (_u *StageUpdate) RemoveTimelineEventIDs(ids ...string) *StageUpdate {
	_u.mutation.RemoveTimelineEventIDs(ids...)
	return _u
}

// RemoveTimelineEvents removes "timeline_events" edges to TimelineEvent entities.
func (_u *StageUpdate) RemoveTimelineEvents(v ...*TimelineEvent) *StageUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTimelineEventIDs(ids...)
}

// ClearMessages clears all "messages" edges to the Message entity.
func (_u *StageUpdate) ClearMessages() *StageUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (_u *StageUpdate) RemoveMessageIDs(ids ...string) *StageUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to Message entities.
func (_u *StageUpdate) RemoveMessages(v ...*Message) *StageUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// ClearLlmInteractions clears all "llm_interactions" edges to the LLMInteraction entity.
func (_u *StageUpdate) ClearLlmInteractions() *StageUpdate {
	_u.mutation.ClearLlmInteractions()
	return _u
}

// RemoveLlmInteractionIDs removes the "llm_interactions" edge to LLMInteraction entities by IDs.
func (_u *StageUpdate) RemoveLlmInteractionIDs(ids ...string) *StageUpdate {
	_u.mutation.RemoveLlmInteractionIDs(ids...)
	return _u
}

// RemoveLlmInteractions removes "llm_interactions" edges to LLMInteraction entities.
func (_u *StageUpdate) RemoveLlmInteractions(v ...*LLMInteraction) *StageUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLlmInteractionIDs(ids...)
}

// ClearMcpInteractions clears all "mcp_interactions" edges to the MCPInteraction entity.
func (_u *StageUpdate) ClearMcpInteractions() *StageUpdate {
	_u.mutation.ClearMcpInteractions()
	return _u
}

// RemoveMcpInteractionIDs removes the "mcp_interactions" edge to MCPInteraction entities by IDs.
func (_u *StageUpdate) RemoveMcpInteractionIDs(ids ...string) *StageUpdate {
	_u.mutation.RemoveMcpInteractionIDs(ids...)
	return _u
}

// RemoveMcpInteractions removes "mcp_interactions" edges to MCPInteraction entities.
func (_u *StageUpdate) RemoveMcpInteractions(v ...*MCPInteraction) *StageUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMcpInteractionIDs(ids...)
}

// ClearChat clears the "chat" edge to the Chat entity.
func (_u *StageUpdate) ClearChat() *StageUpdate {
	_u.mutation.ClearChat()
	return _u
}

// ClearChatUserMessage clears the "chat_user_message" edge to the ChatUserMessage entity.
func (_u *StageUpdate) ClearChatUserMessage() *StageUpdate {
	_u.mutation.ClearChatUserMessage()
	return _u
}

// ClearSessionScores clears all "session_scores" edges to the SessionScore entity.
func (_u *StageUpdate) ClearSessionScores() *StageUpdate {
	_u.mutation.ClearSessionScores()
	return _u
}

// RemoveSessionScoreIDs removes the "session_scores" edge to SessionScore entities by IDs.
func (_u *StageUpdate) RemoveSessionScoreIDs(ids ...string) *StageUpdate {
	_u.mutation.RemoveSessionScoreIDs(ids...)
	return _u
}

// RemoveSessionScores removes "session_scores" edges to SessionScore entities.
func (_u *StageUpdate) RemoveSessionScores(v ...*SessionScore) *StageUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSessionScoreIDs(ids...)
}

// ClearReferencingStages clears all "referencing_stages" edges to the Stage entity.
func (_u *StageUpdate) ClearReferencingStages() *StageUpdate {
	_u.mutation.ClearReferencingStages()
	return _u
}

// RemoveReferencingStageIDs removes the "referencing_stages" edge to Stage entities by IDs.
func (_u *StageUpdate) RemoveReferencingStageIDs(ids ...string) *StageUpdate {
	_u.mutation.RemoveReferencingStageIDs(ids...)
	return _u
}

// RemoveReferencingStages removes "referencing_stages" edges to Stage entities.
func (_u *StageUpdate) RemoveReferencingStages(v ...*Stage) *StageUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReferencingStageIDs(ids...)
}

// ClearReferencedStage clears the "referenced_stage" edge to the Stage entity.
func (_u *StageUpdate) ClearReferencedStage() *StageUpdate {
	_u.mutation.ClearReferencedStage()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StageUpdate) check() error {
	if v, ok := _u.mutation.ParallelType(); ok {
		if err := stage.ParallelTypeValidator(v); err != nil {
			return &ValidationError{Name: "parallel_type", err: fmt.Errorf(`ent: validator failed for field "Stage.parallel_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SuccessPolicy(); ok {
		if err := stage.SuccessPolicyValidator(v); err != nil {
			return &ValidationError{Name: "success_policy", err: fmt.Errorf(`ent: validator failed for field "Stage.success_policy": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StageType(); ok {
		if err := stage.StageTypeValidator(v); err != nil {
			return &ValidationError{Name: "stage_type", err: fmt.Errorf(`ent: validator failed for field "Stage.stage_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := stage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Stage.status": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Stage.session"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *StageUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *StageUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *StageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(stage.Table, stage.Columns, sqlgraph.NewFieldSpec(stage.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StageName(); ok {
		_spec.SetField(stage.FieldStageName, field.TypeString, value)
	}
	if value, ok := _u.mutation.StageIndex(); ok {
		_spec.SetField(stage.FieldStageIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStageIndex(); ok {
		_spec.AddField(stage.FieldStageIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpectedAgentCount(); ok {
		_spec.SetField(stage.FieldExpectedAgentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExpectedAgentCount(); ok {
		_spec.AddField(stage.FieldExpectedAgentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ParallelType(); ok {
		_spec.SetField(stage.FieldParallelType, field.TypeEnum, value)
	}
	if _u.mutation.ParallelTypeCleared() {
		_spec.ClearField(stage.FieldParallelType, field.TypeEnum)
	}
	if value, ok := _u.mutation.SuccessPolicy(); ok {
		_spec.SetField(stage.FieldSuccessPolicy, field.TypeEnum, value)
	}
	if _u.mutation.SuccessPolicyCleared() {
		_spec.ClearField(stage.FieldSuccessPolicy, field.TypeEnum)
	}
	if value, ok := _u.mutation.StageType(); ok {
		_spec.SetField(stage.FieldStageType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(stage.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(stage.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(stage.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(stage.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(stage.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(stage.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(stage.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(stage.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(stage.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(stage.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ActionsExecuted(); ok {
		_spec.SetField(stage.FieldActionsExecuted, field.TypeBool, value)
	}
	if _u.mutation.ActionsExecutedCleared() {
		_spec.ClearField(stage.FieldActionsExecuted, field.TypeBool)
	}
	if _u.mutation.AgentExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.AgentExecutionsTable,
			Columns: []string{stage.AgentExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentexecution.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAgentExecutionsIDs(); len(nodes) > 0 && !_u.mutation.AgentExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.AgentExecutionsTable,
			Columns: []string{stage.AgentExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentexecution.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.AgentExecutionsTable,
			Columns: []string{stage.AgentExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentexecution.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TimelineEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.TimelineEventsTable,
			Columns: []string{stage.TimelineEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timelineevent.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTimelineEventsIDs(); len(nodes) > 0 && !_u.mutation.TimelineEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.TimelineEventsTable,
			Columns: []string{stage.TimelineEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timelineevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TimelineEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.TimelineEventsTable,
			Columns: []string{stage.TimelineEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timelineevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.MessagesTable,
			Columns: []string{stage.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.MessagesTable,
			Columns: []string{stage.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.MessagesTable,
			Columns: []string{stage.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LlmInteractionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.LlmInteractionsTable,
			Columns: []string{stage.LlmInteractionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(llminteraction.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLlmInteractionsIDs(); len(nodes) > 0 && !_u.mutation.LlmInteractionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.LlmInteractionsTable,
			Columns: []string{stage.LlmInteractionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(llminteraction.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LlmInteractionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.LlmInteractionsTable,
			Columns: []string{stage.LlmInteractionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(llminteraction.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.McpInteractionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.McpInteractionsTable,
			Columns: []string{stage.McpInteractionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpinteraction.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMcpInteractionsIDs(); len(nodes) > 0 && !_u.mutation.McpInteractionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.McpInteractionsTable,
			Columns: []string{stage.McpInteractionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpinteraction.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.McpInteractionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.McpInteractionsTable,
			Columns: []string{stage.McpInteractionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpinteraction.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   stage.ChatTable,
			Columns: []string{stage.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   stage.ChatTable,
			Columns: []string{stage.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChatUserMessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   stage.ChatUserMessageTable,
			Columns: []string{stage.ChatUserMessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatusermessage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatUserMessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   stage.ChatUserMessageTable,
			Columns: []string{stage.ChatUserMessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatusermessage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionScoresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.SessionScoresTable,
			Columns: []string{stage.SessionScoresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionscore.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSessionScoresIDs(); len(nodes) > 0 && !_u.mutation.SessionScoresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.SessionScoresTable,
			Columns: []string{stage.SessionScoresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionscore.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionScoresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.SessionScoresTable,
			Columns: []string{stage.SessionScoresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionscore.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReferencingStagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.ReferencingStagesTable,
			Columns: []string{stage.ReferencingStagesColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReferencingStagesIDs(); len(nodes) > 0 && !_u.mutation.ReferencingStagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.ReferencingStagesTable,
			Columns: []string{stage.ReferencingStagesColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReferencingStagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.ReferencingStagesTable,
			Columns: []string{stage.ReferencingStagesColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReferencedStageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   stage.ReferencedStageTable,
			Columns: []string{stage.ReferencedStageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReferencedStageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   stage.ReferencedStageTable,
			Columns: []string{stage.ReferencedStageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StageUpdateOne is the builder for updating a single Stage entity.
type StageUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *StageMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetStageName sets the "stage_name" field.
func (_u *StageUpdateOne) SetStageName(v string) *StageUpdateOne {
	_u.mutation.SetStageName(v)
	return _u
}

// SetNillableStageName sets the "stage_name" field if the given value is not nil.
func (_u *StageUpdateOne) SetNillableStageName(v *string) *StageUpdateOne {
	if v != nil {
		_u.SetStageName(*v)
	}
	return _u
}

// SetStageIndex sets the "stage_index" field.
func (_u *StageUpdateOne) SetStageIndex(v int) *StageUpdateOne {
	_u.mutation.ResetStageIndex()
	_u.mutation.SetStageIndex(v)
	return _u
}

// SetNillableStageIndex sets the "stage_index" field if the given value is not nil.
func (_u *StageUpdateOne) SetNillableStageIndex(v *int) *StageUpdateOne {
	if v != nil {
		_u.SetStageIndex(*v)
	}
	return _u
}

// AddStageIndex adds value to the "stage_index" field.
func (_u *StageUpdateOne) AddStageIndex(v int) *StageUpdateOne {
	_u.mutation.AddStageIndex(v)
	return _u
}

// SetExpectedAgentCount sets the "expected_agent_count" field.
func (_u *StageUpdateOne) SetExpectedAgentCount(v int) *StageUpdateOne {
	_u.mutation.ResetExpectedAgentCount()
	_u.mutation.SetExpectedAgentCount(v)
	return _u
}

// SetNillableExpectedAgentCount sets the "expected_agent_count" field if the given value is not nil.
func (_u *StageUpdateOne) SetNillableExpectedAgentCount(v *int) *StageUpdateOne {
	if v != nil {
		_u.SetExpectedAgentCount(*v)
	}
	return _u
}

// AddExpectedAgentCount adds value to the "expected_agent_count" field.
func (_u *StageUpdateOne) AddExpectedAgentCount(v int) *StageUpdateOne {
	_u.mutation.AddExpectedAgentCount(v)
	return _u
}

// SetParallelType sets the "parallel_type" field.
func (_u *StageUpdateOne) SetParallelType(v stage.ParallelType) *StageUpdateOne {
	_u.mutation.SetParallelType(v)
	return _u
}

// SetNillableParallelType sets the "parallel_type" field if the given value is not nil.
func (_u *StageUpdateOne) SetNillableParallelType(v *stage.ParallelType) *StageUpdateOne {
	if v != nil {
		_u.SetParallelType(*v)
	}
	return _u
}

// ClearParallelType clears the value of the "parallel_type" field.
func (_u *StageUpdateOne) ClearParallelType() *StageUpdateOne {
	_u.mutation.ClearParallelType()
	return _u
}

// SetSuccessPolicy sets the "success_policy" field.
func (_u *StageUpdateOne) SetSuccessPolicy(v stage.SuccessPolicy) *StageUpdateOne {
	_u.mutation.SetSuccessPolicy(v)
	return _u
}

// SetNillableSuccessPolicy sets the "success_policy" field if the given value is not nil.
func (_u *StageUpdateOne) SetNillableSuccessPolicy(v *stage.SuccessPolicy) *StageUpdateOne {
	if v != nil {
		_u.SetSuccessPolicy(*v)
	}
	return _u
}

// ClearSuccessPolicy clears the value of the "success_policy" field.
func (_u *StageUpdateOne) ClearSuccessPolicy() *StageUpdateOne {
	_u.mutation.ClearSuccessPolicy()
	return _u
}

// SetStageType sets the "stage_type" field.
func (_u *StageUpdateOne) SetStageType(v stage.StageType) *StageUpdateOne {
	_u.mutation.SetStageType(v)
	return _u
}

// SetNillableStageType sets the "stage_type" field if the given value is not nil.
func (_u *StageUpdateOne) SetNillableStageType(v *stage.StageType) *StageUpdateOne {
	if v != nil {
		_u.SetStageType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *StageUpdateOne) SetStatus(v stage.Status) *StageUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *StageUpdateOne) SetNillableStatus(v *stage.Status) *StageUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *StageUpdateOne) SetStartedAt(v time.Time) *StageUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *StageUpdateOne) SetNillableStartedAt(v *time.Time) *StageUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *StageUpdateOne) ClearStartedAt() *StageUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *StageUpdateOne) SetCompletedAt(v time.Time) *StageUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *StageUpdateOne) SetNillableCompletedAt(v *time.Time) *StageUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *StageUpdateOne) ClearCompletedAt() *StageUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *StageUpdateOne) SetDurationMs(v int) *StageUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *StageUpdateOne) SetNillableDurationMs(v *int) *StageUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *StageUpdateOne) AddDurationMs(v int) *StageUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *StageUpdateOne) ClearDurationMs() *StageUpdateOne {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *StageUpdateOne) SetErrorMessage(v string) *StageUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *StageUpdateOne) SetNillableErrorMessage(v *string) *StageUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *StageUpdateOne) ClearErrorMessage() *StageUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *StageUpdateOne) SetChatID(v string) *StageUpdateOne {
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *StageUpdateOne) SetNillableChatID(v *string) *StageUpdateOne {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// ClearChatID clears the value of the "chat_id" field.
func (_u *StageUpdateOne) ClearChatID() *StageUpdateOne {
	_u.mutation.ClearChatID()
	return _u
}

// SetChatUserMessageID sets the "chat_user_message_id" field.
func (_u *StageUpdateOne) SetChatUserMessageID(v string) *StageUpdateOne {
	_u.mutation.SetChatUserMessageID(v)
	return _u
}

// SetNillableChatUserMessageID sets the "chat_user_message_id" field if the given value is not nil.
func (_u *StageUpdateOne) SetNillableChatUserMessageID(v *string) *StageUpdateOne {
	if v != nil {
		_u.SetChatUserMessageID(*v)
	}
	return _u
}

// ClearChatUserMessageID clears the value of the "chat_user_message_id" field.
func (_u *StageUpdateOne) ClearChatUserMessageID() *StageUpdateOne {
	_u.mutation.ClearChatUserMessageID()
	return _u
}

// SetReferencedStageID sets the "referenced_stage_id" field.
func (_u *StageUpdateOne) SetReferencedStageID(v string) *StageUpdateOne {
	_u.mutation.SetReferencedStageID(v)
	return _u
}

// SetNillableReferencedStageID sets the "referenced_stage_id" field if the given value is not nil.
func (_u *StageUpdateOne) SetNillableReferencedStageID(v *string) *StageUpdateOne {
	if v != nil {
		_u.SetReferencedStageID(*v)
	}
	return _u
}

// ClearReferencedStageID clears the value of the "referenced_stage_id" field.
func (_u *StageUpdateOne) ClearReferencedStageID() *StageUpdateOne {
	_u.mutation.ClearReferencedStageID()
	return _u
}

// SetActionsExecuted sets the "actions_executed" field.
func (_u *StageUpdateOne) SetActionsExecuted(v bool) *StageUpdateOne {
	_u.mutation.SetActionsExecuted(v)
	return _u
}

// SetNillableActionsExecuted sets the "actions_executed" field if the given value is not nil.
func (_u *StageUpdateOne) SetNillableActionsExecuted(v *bool) *StageUpdateOne {
	if v != nil {
		_u.SetActionsExecuted(*v)
	}
	return _u
}

// ClearActionsExecuted clears the value of the "actions_executed" field.
func (_u *StageUpdateOne) ClearActionsExecuted() *StageUpdateOne {
	_u.mutation.ClearActionsExecuted()
	return _u
}

// AddAgentExecutionIDs adds the "agent_executions" edge to the AgentExecution entity by IDs.
func (_u *StageUpdateOne) AddAgentExecutionIDs(ids ...string) *StageUpdateOne {
	_u.mutation.AddAgentExecutionIDs(ids...)
	return _u
}

// AddAgentExecutions adds the "agent_executions" edges to the AgentExecution entity.
func (_u *StageUpdateOne) AddAgentExecutions(v ...*AgentExecution) *StageUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAgentExecutionIDs(ids...)
}

// AddTimelineEventIDs adds the "timeline_events" edge to the TimelineEvent entity by IDs.
func (_u *StageUpdateOne) AddTimelineEventIDs(ids ...string) *StageUpdateOne {
	_u.mutation.AddTimelineEventIDs(ids...)
	return _u
}

// AddTimelineEvents adds the "timeline_events" edges to the TimelineEvent entity.
func (_u *StageUpdateOne) AddTimelineEvents(v ...*TimelineEvent) *StageUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTimelineEventIDs(ids...)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (_u *StageUpdateOne) AddMessageIDs(ids ...string) *StageUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the Message entity.
func (_u *StageUpdateOne) AddMessages(v ...*Message) *StageUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// AddLlmInteractionIDs adds the "llm_interactions" edge to the LLMInteraction entity by IDs.
func (_u *StageUpdateOne) AddLlmInteractionIDs(ids ...string) *StageUpdateOne {
	_u.mutation.AddLlmInteractionIDs(ids...)
	return _u
}

// AddLlmInteractions adds the "llm_interactions" edges to the LLMInteraction entity.
func (_u *StageUpdateOne) AddLlmInteractions(v ...*LLMInteraction) *StageUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLlmInteractionIDs(ids...)
}

// AddMcpInteractionIDs adds the "mcp_interactions" edge to the MCPInteraction entity by IDs.
func (_u *StageUpdateOne) AddMcpInteractionIDs(ids ...string) *StageUpdateOne {
	_u.mutation.AddMcpInteractionIDs(ids...)
	return _u
}

// AddMcpInteractions adds the "mcp_interactions" edges to the MCPInteraction entity.
func (_u *StageUpdateOne) AddMcpInteractions(v ...*MCPInteraction) *StageUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMcpInteractionIDs(ids...)
}

// SetChat sets the "chat" edge to the Chat entity.
func (_u *StageUpdateOne) SetChat(v *Chat) *StageUpdateOne {
	return _u.SetChatID(v.ID)
}

// SetChatUserMessage sets the "chat_user_message" edge to the ChatUserMessage entity.
func (_u *StageUpdateOne) SetChatUserMessage(v *ChatUserMessage) *StageUpdateOne {
	return _u.SetChatUserMessageID(v.ID)
}

// AddSessionScoreIDs adds the "session_scores" edge to the SessionScore entity by IDs.
func (_u *StageUpdateOne) AddSessionScoreIDs(ids ...string) *StageUpdateOne {
	_u.mutation.AddSessionScoreIDs(ids...)
	return _u
}

// AddSessionScores adds the "session_scores" edges to the SessionScore entity.
func (_u *StageUpdateOne) AddSessionScores(v ...*SessionScore) *StageUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSessionScoreIDs(ids...)
}

// AddReferencingStageIDs adds the "referencing_stages" edge to the Stage entity by IDs.
func (_u *StageUpdateOne) AddReferencingStageIDs(ids ...string) *StageUpdateOne {
	_u.mutation.AddReferencingStageIDs(ids...)
	return _u
}

// AddReferencingStages adds the "referencing_stages" edges to the Stage entity.
func (_u *StageUpdateOne) AddReferencingStages(v ...*Stage) *StageUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReferencingStageIDs(ids...)
}

// SetReferencedStage sets the "referenced_stage" edge to the Stage entity.
func (_u *StageUpdateOne) SetReferencedStage(v *Stage) *StageUpdateOne {
	return _u.SetReferencedStageID(v.ID)
}

// Mutation returns the StageMutation object of the builder.
func (_u *StageUpdateOne) Mutation() *StageMutation {
	return _u.mutation
}

// ClearAgentExecutions clears all "agent_executions" edges to the AgentExecution entity.
func (_u *StageUpdateOne) ClearAgentExecutions() *StageUpdateOne {
	_u.mutation.ClearAgentExecutions()
	return _u
}

// RemoveAgentExecutionIDs removes the "agent_executions" edge to AgentExecution entities by IDs.
func (_u *StageUpdateOne) RemoveAgentExecutionIDs(ids ...string) *StageUpdateOne {
	_u.mutation.RemoveAgentExecutionIDs(ids...)
	return _u
}

// RemoveAgentExecutions removes "agent_executions" edges to AgentExecution entities.
func (_u *StageUpdateOne) RemoveAgentExecutions(v ...*AgentExecution) *StageUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAgentExecutionIDs(ids...)
}

// ClearTimelineEvents clears all "timeline_events" edges to the TimelineEvent entity.
func (_u *StageUpdateOne) ClearTimelineEvents() *StageUpdateOne {
	_u.mutation.ClearTimelineEvents()
	return _u
}

// RemoveTimelineEventIDs removes the "timeline_events" edge to TimelineEvent entities by IDs.
func (_u *StageUpdateOne) RemoveTimelineEventIDs(ids ...string) *StageUpdateOne {
	_u.mutation.RemoveTimelineEventIDs(ids...)
	return _u
}

// RemoveTimelineEvents removes "timeline_events" edges to TimelineEvent entities.
func (_u *StageUpdateOne) RemoveTimelineEvents(v ...*TimelineEvent) *StageUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTimelineEventIDs(ids...)
}

// ClearMessages clears all "messages" edges to the Message entity.
func (_u *StageUpdateOne) ClearMessages() *StageUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (_u *StageUpdateOne) RemoveMessageIDs(ids ...string) *StageUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to Message entities.
func (_u *StageUpdateOne) RemoveMessages(v ...*Message) *StageUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// ClearLlmInteractions clears all "llm_interactions" edges to the LLMInteraction entity.
func (_u *StageUpdateOne) ClearLlmInteractions() *StageUpdateOne {
	_u.mutation.ClearLlmInteractions()
	return _u
}

// RemoveLlmInteractionIDs removes the "llm_interactions" edge to LLMInteraction entities by IDs.
func (_u *StageUpdateOne) RemoveLlmInteractionIDs(ids ...string) *StageUpdateOne {
	_u.mutation.RemoveLlmInteractionIDs(ids...)
	return _u
}

// RemoveLlmInteractions removes "llm_interactions" edges to LLMInteraction entities.
func (_u *StageUpdateOne) RemoveLlmInteractions(v ...*LLMInteraction) *StageUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLlmInteractionIDs(ids...)
}

// ClearMcpInteractions clears all "mcp_interactions" edges to the MCPInteraction entity.
func (_u *StageUpdateOne) ClearMcpInteractions() *StageUpdateOne {
	_u.mutation.ClearMcpInteractions()
	return _u
}

// RemoveMcpInteractionIDs removes the "mcp_interactions" edge to MCPInteraction entities by IDs.
func (_u *StageUpdateOne) RemoveMcpInteractionIDs(ids ...string) *StageUpdateOne {
	_u.mutation.RemoveMcpInteractionIDs(ids...)
	return _u
}

// RemoveMcpInteractions removes "mcp_interactions" edges to MCPInteraction entities.
func (_u *StageUpdateOne) RemoveMcpInteractions(v ...*MCPInteraction) *StageUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMcpInteractionIDs(ids...)
}

// ClearChat clears the "chat" edge to the Chat entity.
func (_u *StageUpdateOne) ClearChat() *StageUpdateOne {
	_u.mutation.ClearChat()
	return _u
}

// ClearChatUserMessage clears the "chat_user_message" edge to the ChatUserMessage entity.
func (_u *StageUpdateOne) ClearChatUserMessage() *StageUpdateOne {
	_u.mutation.ClearChatUserMessage()
	return _u
}

// ClearSessionScores clears all "session_scores" edges to the SessionScore entity.
func (_u *StageUpdateOne) ClearSessionScores() *StageUpdateOne {
	_u.mutation.ClearSessionScores()
	return _u
}

// RemoveSessionScoreIDs removes the "session_scores" edge to SessionScore entities by IDs.
func (_u *StageUpdateOne) RemoveSessionScoreIDs(ids ...string) *StageUpdateOne {
	_u.mutation.RemoveSessionScoreIDs(ids...)
	return _u
}

// RemoveSessionScores removes "session_scores" edges to SessionScore entities.
func (_u *StageUpdateOne) RemoveSessionScores(v ...*SessionScore) *StageUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSessionScoreIDs(ids...)
}

// ClearReferencingStages clears all "referencing_stages" edges to the Stage entity.
func (_u *StageUpdateOne) ClearReferencingStages() *StageUpdateOne {
	_u.mutation.ClearReferencingStages()
	return _u
}

// RemoveReferencingStageIDs removes the "referencing_stages" edge to Stage entities by IDs.
func (_u *StageUpdateOne) RemoveReferencingStageIDs(ids ...string) *StageUpdateOne {
	_u.mutation.RemoveReferencingStageIDs(ids...)
	return _u
}

// RemoveReferencingStages removes "referencing_stages" edges to Stage entities.
func (_u *StageUpdateOne) RemoveReferencingStages(v ...*Stage) *StageUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReferencingStageIDs(ids...)
}

// ClearReferencedStage clears the "referenced_stage" edge to the Stage entity.
func (_u *StageUpdateOne) ClearReferencedStage() *StageUpdateOne {
	_u.mutation.ClearReferencedStage()
	return _u
}

// Where appends a list predicates to the StageUpdate builder.
func (_u *StageUpdateOne) Where(ps ...predicate.Stage) *StageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StageUpdateOne) Select(field string, fields ...string) *StageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Stage entity.
func (_u *StageUpdateOne) Save(ctx context.Context) (*Stage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StageUpdateOne) SaveX(ctx context.Context) *Stage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StageUpdateOne) check() error {
	if v, ok := _u.mutation.ParallelType(); ok {
		if err := stage.ParallelTypeValidator(v); err != nil {
			return &ValidationError{Name: "parallel_type", err: fmt.Errorf(`ent: validator failed for field "Stage.parallel_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SuccessPolicy(); ok {
		if err := stage.SuccessPolicyValidator(v); err != nil {
			return &ValidationError{Name: "success_policy", err: fmt.Errorf(`ent: validator failed for field "Stage.success_policy": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StageType(); ok {
		if err := stage.StageTypeValidator(v); err != nil {
			return &ValidationError{Name: "stage_type", err: fmt.Errorf(`ent: validator failed for field "Stage.stage_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := stage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Stage.status": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Stage.session"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *StageUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *StageUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *StageUpdateOne) sqlSave(ctx context.Context) (_node *Stage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(stage.Table, stage.Columns, sqlgraph.NewFieldSpec(stage.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Stage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stage.FieldID)
		for _, f := range fields {
			if !stage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != stage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StageName(); ok {
		_spec.SetField(stage.FieldStageName, field.TypeString, value)
	}
	if value, ok := _u.mutation.StageIndex(); ok {
		_spec.SetField(stage.FieldStageIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStageIndex(); ok {
		_spec.AddField(stage.FieldStageIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpectedAgentCount(); ok {
		_spec.SetField(stage.FieldExpectedAgentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExpectedAgentCount(); ok {
		_spec.AddField(stage.FieldExpectedAgentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ParallelType(); ok {
		_spec.SetField(stage.FieldParallelType, field.TypeEnum, value)
	}
	if _u.mutation.ParallelTypeCleared() {
		_spec.ClearField(stage.FieldParallelType, field.TypeEnum)
	}
	if value, ok := _u.mutation.SuccessPolicy(); ok {
		_spec.SetField(stage.FieldSuccessPolicy, field.TypeEnum, value)
	}
	if _u.mutation.SuccessPolicyCleared() {
		_spec.ClearField(stage.FieldSuccessPolicy, field.TypeEnum)
	}
	if value, ok := _u.mutation.StageType(); ok {
		_spec.SetField(stage.FieldStageType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(stage.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(stage.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(stage.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(stage.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(stage.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(stage.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(stage.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(stage.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(stage.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(stage.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ActionsExecuted(); ok {
		_spec.SetField(stage.FieldActionsExecuted, field.TypeBool, value)
	}
	if _u.mutation.ActionsExecutedCleared() {
		_spec.ClearField(stage.FieldActionsExecuted, field.TypeBool)
	}
	if _u.mutation.AgentExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.AgentExecutionsTable,
			Columns: []string{stage.AgentExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentexecution.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAgentExecutionsIDs(); len(nodes) > 0 && !_u.mutation.AgentExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.AgentExecutionsTable,
			Columns: []string{stage.AgentExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentexecution.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.AgentExecutionsTable,
			Columns: []string{stage.AgentExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentexecution.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TimelineEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.TimelineEventsTable,
			Columns: []string{stage.TimelineEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timelineevent.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTimelineEventsIDs(); len(nodes) > 0 && !_u.mutation.TimelineEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.TimelineEventsTable,
			Columns: []string{stage.TimelineEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timelineevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TimelineEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.TimelineEventsTable,
			Columns: []string{stage.TimelineEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timelineevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.MessagesTable,
			Columns: []string{stage.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.MessagesTable,
			Columns: []string{stage.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.MessagesTable,
			Columns: []string{stage.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LlmInteractionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.LlmInteractionsTable,
			Columns: []string{stage.LlmInteractionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(llminteraction.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLlmInteractionsIDs(); len(nodes) > 0 && !_u.mutation.LlmInteractionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.LlmInteractionsTable,
			Columns: []string{stage.LlmInteractionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(llminteraction.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LlmInteractionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.LlmInteractionsTable,
			Columns: []string{stage.LlmInteractionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(llminteraction.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.McpInteractionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.McpInteractionsTable,
			Columns: []string{stage.McpInteractionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpinteraction.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMcpInteractionsIDs(); len(nodes) > 0 && !_u.mutation.McpInteractionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.McpInteractionsTable,
			Columns: []string{stage.McpInteractionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpinteraction.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.McpInteractionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.McpInteractionsTable,
			Columns: []string{stage.McpInteractionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpinteraction.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   stage.ChatTable,
			Columns: []string{stage.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   stage.ChatTable,
			Columns: []string{stage.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChatUserMessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   stage.ChatUserMessageTable,
			Columns: []string{stage.ChatUserMessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatusermessage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatUserMessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   stage.ChatUserMessageTable,
			Columns: []string{stage.ChatUserMessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatusermessage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionScoresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.SessionScoresTable,
			Columns: []string{stage.SessionScoresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionscore.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSessionScoresIDs(); len(nodes) > 0 && !_u.mutation.SessionScoresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.SessionScoresTable,
			Columns: []string{stage.SessionScoresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionscore.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionScoresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.SessionScoresTable,
			Columns: []string{stage.SessionScoresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionscore.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReferencingStagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.ReferencingStagesTable,
			Columns: []string{stage.ReferencingStagesColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReferencingStagesIDs(); len(nodes) > 0 && !_u.mutation.ReferencingStagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.ReferencingStagesTable,
			Columns: []string{stage.ReferencingStagesColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReferencingStagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stage.ReferencingStagesTable,
			Columns: []string{stage.ReferencingStagesColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReferencedStageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   stage.ReferencedStageTable,
			Columns: []string{stage.ReferencedStageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReferencedStageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   stage.ReferencedStageTable,
			Columns: []string{stage.ReferencedStageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Stage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
