// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AgentExecution is the predicate function for agentexecution builders.
type AgentExecution func(*sql.Selector)

// AlertSession is the predicate function for alertsession builders.
type AlertSession func(*sql.Selector)

// Chat is the predicate function for chat builders.
type Chat func(*sql.Selector)

// ChatUserMessage is the predicate function for chatusermessage builders.
type ChatUserMessage func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// InvestigationMemory is the predicate function for investigationmemory builders.
type InvestigationMemory func(*sql.Selector)

// LLMInteraction is the predicate function for llminteraction builders.
type LLMInteraction func(*sql.Selector)

// MCPInteraction is the predicate function for mcpinteraction builders.
type MCPInteraction func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// SessionReviewActivity is the predicate function for sessionreviewactivity builders.
type SessionReviewActivity func(*sql.Selector)

// SessionScore is the predicate function for sessionscore builders.
type SessionScore func(*sql.Selector)

// Stage is the predicate function for stage builders.
type Stage func(*sql.Selector)

// TimelineEvent is the predicate function for timelineevent builders.
type TimelineEvent func(*sql.Selector)
